<?php
  $appinfo = new AppInfo("KOffice Workspace");
  $appinfo->setIcon( "../pics/hi32-app-koshell.png", "32", "32");
  $appinfo->setVersion($koshellversion);
  $appinfo->setLicense("gpl");
  $appinfo->setCopyright("2001", "the KOffice Workspace Team");
  $appinfo->addMaintainer("Sven Lüppken", "sven@kde.org");
  $appinfo->addAuthor("Torben Weis",  "weis@kde.org");
  $appinfo->addAuthor("David Faure", "faure@kde.org");
?>
