    <b>Krita</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="index.phtml">Information</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="screenshots.phtml">Screenshots</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="faq.phtml">Krita FAQ</a>
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/developer/krita/index.phtml">Hacking Krita</a>
    <p />

    <? include("../applinks.inc"); ?>


