    <b>Krita</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="index.phtml">Information</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="screenshots.phtml">Screenshots</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="faq.phtml">Krita FAQ</a>
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/developer/krita/index.phtml">Hacking Krita</a>
    
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://www.valdyas.org/fading/index.cgi/hacking/krita">Fading Memories blog on Krita, by Boudewijn Rempt</a>
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://cyrilleberger.blogspot.com">One Day One Feature: A Guided Tour of Krita Features in Daily Installments, by Cyrille Berger</a>
    <p />

    <? include("../applinks.inc"); ?>


