<?php
$this->appendLink("Information","index.php");
$this->appendLink("Screenshots","screenshots.php");
$this->appendLink("Videos","videos.php");
$this->appendLink("FAQ","faq.php");
$this->appendLink("HandBook", "http://docs.kde.org/development/en/koffice/krita/", false );
$this->appendLink("More Info","more_info.php");
$this->appendLink("User Gallery","gallery.php");
$this->appendLink("Troubleshooting","http://wiki.koffice.org/index.php?title=Krita/Known_problem_with_packages", false);
?>
