<p align="justify">
    Also available in:
    <table border="0">
      <tr>
        <td>
          <a href="http://cat.kde.org/index.php/Notes_de_premsa/KOffice_1.6"><img src="flag_spain_catalunya.png"></img></a>
        </td>
        <td>
          <a href="http://www.kde.nl/koffice/aankondiging-1.6.0.html"><img src="flag_netherlands.png"></img></a>
        </td>
        <td>
          <a href="announce-1.6.php"><img src="flag_united_kingdom.png" height="48"></img></a>
        </td>
        <td>
          <a href="http://fr.kde.org/koffice/announcements/announce-1.6.php"><img src="flag_france.png"></img></a>
        </td>
        <td>
          <a href="announce-1.6-de.php"><img src="flag_germany.png"></img></a>
        </td>
        <td>
          <a href="http://www.kde-it.org/news.php?extend.22.2"><img src="flag_italy.png"></img></a>
        </td>
        <td>
          <a href="http://koffice.org.pl/ogloszenia/ogloszenie-1.6.php"><img src="flag_poland.png"/></a>
        </td>
        <td>
          <a href="announce-1.6-pt.php"><img src="flag_portugal.png"></img></a>
        </td>
      </tr>
      <tr>
        <td style="text-align:center;">
          <a href="http://cat.kde.org/index.php/Notes_de_premsa/KOffice_1.6">Catalan</a>
        </td>
        <td style="text-align:center;">
          <a href="http://www.kde.nl/koffice/aankondiging-1.6.0.html">Dutch</a>
        </td>
        <td style="text-align:center;">
          <a href="announce-1.6.php">English</a>
        </td>
        <td style="text-align:center;">
          <a href="http://fr.kde.org/koffice/announcements/announce-1.6.php">French</a>
        </td>
        <td style="text-align:center;">
          <a href="announce-1.6-de.php">German</a>
        </td>
        <td style="text-align:center;">
          <a href="http://www.kde-it.org/news.php?extend.22.2">Italian</a>
        </td>
        <td style="text-align:center;">
          <a href="http://koffice.org.pl/ogloszenia/ogloszenie-1.6.php">Polish</a>
        </td>
        <td style="text-align:center;">
          <a href="announce-1.6-pt.php">Portuguese</a>
        </td>
      </tr>
    </table>
</p>

