<?php
$this->addLink("Information", "index.php");
$this->addLink("KOffice 1.4", "announce-1.4.php");
$this->addLink("KOffice 1.4rc1", "announce-1.4-rc1.php");
$this->addLink("KOffice 1.4beta1", "announce-1.4-beta1.php");
$this->addLink("KOffice 1.3", "announce-1.3.php");
$this->addLink("KOffice 1.3beta1", "announce-1.3-beta1.php");
$this->addLink("KOffice 1.2.1", "announce-1.2.1.php");
$this->addLink("KOffice 1.2", "announce-1.2.php");
$this->addLink("KOffice 1.2rc1", "announce-1.2-rc1.php");
$this->addLink("KOffice 1.2beta2", "announce-1.2-beta2.php");
$this->addLink("KOffice 1.2beta1", "announce-1.2-beta1.php");
$this->addLink("KOffice 1.1.1", "announce-1.1.1.php");
$this->addLink("KOffice 1.1", "announce-1.1.php");
$this->addLink("KOffice 1.1rc1", "announce-1.1-rc1.php");
$this->addLink("KOffice 1.1beta3", "announce-1.1-beta3.php");
$this->addLink("KOffice 1.1beta2", "announce-1.1-beta2.php");
$this->addLink("KOffice 1.1beta1", "announce-1.1-beta1.php");
?>
