<?php
  $appinfo = new AppInfo("KPlato");
  $appinfo->setIcon( "pics/cr48-app-kplato.png", "48", "48");
  $appinfo->setVersion($kplatoversion);
  $appinfo->setLicense("lgpl");
  $appinfo->setCopyright("2001", "the KPlato Team");
  $appinfo->addAuthor("Thomas Zander", "z&#x61;n&#x64;e&#00114;&#x40;&#107;&#x64;e&#x2e;&#x6f;&#0114;&#103;");
  $appinfo->addAuthor("Jim Sabatke", "jsa&#x62;atk&#x65;&#x40;&#00101;&#120;&#101;&#099;&#112;c&#046;&#99;o&#109;");
  $appinfo->addAuthor("Bo Thorsen", "bo&#64;&#0116;&#0104;&#00111;&#114;se&#110;-&#99;&#111;&#00110;s&#117;lti&#110;&#103;&#x2e;dk");
  $appinfo->addContributor("Nuno Pinheiro and Danny Allen", "danny@dannyallen.co.uk", "Application icon for KPlato");
?>
