<?php

// promote which site we are!
$site = "koffice";

// promote title to use
$site_title = i18n_var("The KOffice Project");

$name = "koffice.org Web Team";
$mail = "webmaster@kde.org";
$currentversion='1.5';
// $develversion='1.5-rc1';
// $oldversion='1.3.5';
$kwordversion='1.5.0';
$kspreadversion='1.5.0';
$kpresenterversion='1.5.0';
$kritaversion='1.5.0';
$kchartversion='1.5.0';
$kformulaversion='1.5.0';
$kugarversion='1.5.0';
$kivioversion='1.5.0';
$karbonversion='1.5.0';
$kexiversion='1.0.0';
$kplatoversion='0.5.0';
?>
