<?php

// promote which site we are!
$site = "koffice";

// promote title to use
$site_title = i18n_var("The KOffice Project");

$name = "koffice.org Web Team";
$mail = "webmaster@kde.org";
$currentversion='1.4.2';
$develversion='1.5-rc1';
// $oldversion='1.3.5';
$kwordversion='1.4.2';
$kspreadversion='1.4.2';
$kpresenterversion='1.4.2';
$kritaversion='1.4.2';
$kchartversion='1.4.2';
$kformulaversion='1.4.2';
$kugarversion='1.4.2';
$kivioversion='1.4.2';
$karbonversion='0.2';
$kexiversion='0.9';
$kplatoversion='0.5.0';
?>
