<?php

// promote which site we are!
$site = "koffice";

// promote title to use
$site_title = i18n_var("The KOffice Project");

$name = "koffice.org Web Team";
$mail = "webmaster@kde.org";
$currentversion='1.6';
// $develversion='1.6';
$koshellversion='1.6.0';
$kwordversion='1.6.0';
$kspreadversion='1.6.0';
$kpresenterversion='1.6.0';
$kritaversion='1.6.0';
$kchartversion='1.6.0';
$kformulaversion='1.6.0';
$kugarversion='1.6.0';
$kivioversion='1.6.0';
$karbonversion='1.6.0';
$kexiversion='1.1.0';
$kplatoversion='0.6.0';
?>
