<?php
 // Here we define the version numbers. This should be updated as new releases of KOffice are made. The changes will (should) be automatically reflected as required throughout the site
  $currentversion='1.2.1';
  $develversion='1.3beta2';
  $oldversion='1.2';
  $kwordversion='1.2.1';
  $kspreadversion='1.2.1';
  $kpresenterversion='1.2.1';
  $kontourversion='1.2.1';
  $kritaversion='pre-development';
  $kchartversion='1.2.1';
  $kformulaversion='1.2.1';
  $kugarversion='1.2.1';
  $kivioversion='1.2.1';
  $karbonversion='0.1';
  $currentyear='2003';
 ?>
