<?php
  $page_title='Discover KOffice - Kugar';
  $site_root='../../';
  include("koffice.inc");
  include("header.inc");
  ?>
<a href="kformula.php">Previous: KFormula</a>
<h2>Kugar</h2>
<p>
Kugar is a highly useful application for generating business-quality reports to be viewed or printed. Any report generated by Kugar can either be viewed using a standalone viewer or optionally use the KPart report viewer which allows reports to be viewed in other KDE applications, e.g. the Konqueror browser. Other features boasted by Kugar include:
</p>
<ul>
	<li>A fully-functional report designer</li>
	<li>An unlimited amount of detail levels</li>
	<li>"Grand total" listing for things like sums and averages</li>
</ul>
<a href="kformula.php">Previous: KFormula</a>
<?php include("footer.inc"); ?>