<?php
  $appinfo = new AppInfo("KChart");
  $appinfo->setIcon( "pics/hi48-app-kchart.png", "48", "48");
  $appinfo->setVersion($kchartversion);
  $appinfo->setLicense("gpl");
  $appinfo->setCopyright("1998-2005", "the KChart Team");
  $appinfo->addMaintainer("Inge Wallin", "&#105;&#110;&#x67;e&#064;&#108;&#0121;&#115;a&#x74;o&#114;&#x2e;l&#105;&#x75;&#0046;&#115;e");
  $appinfo->addAuthor("Kalle Dalheimer", "k&#97;lle&#x40;&#107;&#100;&#x65;&#x2e;&#111;&#114;&#x67;");
  $appinfo->addAuthor("Torben Weis", "&#00119;&#101;i&#115;&#64;kde&#046;org");
  $appinfo->addContributor("Laurent Montel", "&#x6d;o&#110;&#116;&#101;l&#064;kd&#x65;.o&#00114;g");
  $appinfo->addContributor("Karl-Heinz Zimmer", "&#107;&#x68;&#122;&#x40;kd&#101;.&#111;r&#103;");
  $appinfo->addContributor("Inge Wallin", "&#105;&#110;&#x67;e&#064;&#108;&#0121;&#115;a&#x74;o&#114;&#x2e;l&#105;&#x75;&#0046;&#115;e");
  $appinfo->addContributor("Raphael Langerhorst", "raphael.&#108;&#0097;&#110;ger&#104;&#x6f;rst&#064;&#x6b;demai&#x6c;&#046;&#x6e;&#101;&#x74;");
?>
