<?php
  $appinfo = new AppInfo("Karbon14");
  $appinfo->setIcon( "pics/hi48-app-karbon.png", "48", "48");
  $appinfo->setVersion("0.2");
  $appinfo->setLicense("gpl");
  $appinfo->setCopyright("1998", "the Karbon Team");
  $appinfo->addAuthor("Rob Buis", "buis&#x40;&#x6b;&#100;e.or&#103;");
  $appinfo->addAuthor("Lenny Kudling", ""); // Email removed at developer's request
  $appinfo->addAuthor("Tomislav Lukman", "tomislav.lukman@ck.t-com.hr"); 
  $appinfo->addAuthor("Beno&icirc;t Vautrin", "benoit.vautrin@free.fr"); 
  $appinfo->addContributor("Jan Hambrecht", "jaham@gmx.net", "Bug fixes and improvements");
  $appinfo->addContributor("Peter Simonsson", "psn@linux.se", "Bug fixes and improvements"); 
  $appinfo->addContributor("Tim Beaulen", "tbscope@gmail.com", "Bug fixes and improvements" );
  $appinfo->addContributor("Boudewijn Rempt", "boud@valdyas.org", "Bug fixes and improvements");
  $appinfo->addContributor("Pierre Stirnweiss", "pierre.stirnweiss_kde@gadz.org", "Bug fixes and improvements");
  $appinfo->addContributor("Inge Wallin", "inge@lysator.liu.se", "Bug fixes");
  $appinfo->addContributor("Alan Horkan", "", "Helpfull patches and advice");
?>
