<?php
  $appinfo = new AppInfo("Karbon14");
  $appinfo->setIcon( "pics/hi48-app-karbon.png", "48", "48");
  $appinfo->setVersion("0.2");
  $appinfo->setLicense("gpl");
  $appinfo->setCopyright("1998", "the Karbon Team");
  $appinfo->addAuthor("Rob Buis", "buis&#x40;&#x6b;&#100;e.or&#103;");
  $appinfo->addAuthor("Lenny Kudling", ""); // Email removed at developer's request
  $appinfo->addContributor("Rob Buis", "b&#117;i&#x73;&#064;k&#100;&#101;&#0046;org");
  $appinfo->addContributor("Lenny Kudling", ""); // Email removed at developer's request
  $appinfo->addContributor("Benoit Vautrin", "benoit.&#118;a&#117;t&#114;&#x69;n&#00064;free&#46;f&#114;");
  $appinfo->addContributor("Tomislav Lukman", "tomislav.l&#117;kma&#0110;&#064;c&#107;&#x2e;h&#x69;&#110;e&#x74;.h&#0114;");
?>
