    <b>Learn</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/info/">Information</a><br />
    <!-- img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/#schedule">Release Schedule</a><br / -->
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/faq/">FAQ</a><br />
<!--<img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/documentation/">Documentation</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/screenshots/">Screenshots</a><br />-->
        <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/downloads/">Downloads</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/developers.phtml">Developers</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/contact.phtml">Mailing lists</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/support.phtml">Supporting KOffice</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/supporters.phtml">KOffice Supporters</a><br />
    <p />

    <b>Latest release</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a href="/releases/<?php echo $currentversion; ?>-release.phtml">KOffice <?php echo $currentversion; ?></a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/releases/">Release Notes</a><br />
    <p />

  
    <?php include("../applinks.inc") ?>
    <p />

    <b>Download</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/install-binaries.phtml">Binaries</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/install-source.phtml">Source</a><br />
    <p />

    <b>Develop</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/developer/">Developer Resources</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://developer.kde.org">Developer Information</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://bugs.kde.org">Bug Reports</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="/getinvolved/">Getting Involved</a><br />
    <p />

    <b>Family</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://www.kde.org">www.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://www.konqueror.org">www.konqueror.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://www.kdevelop.org">www.kdevelop.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://www.kdeleague.org">www.kdeleague.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://devel-home.kde.org">devel-home.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://developer.kde.org">developer.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://lists.kde.org">lists.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://artist.kde.org">artist.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://bugs.kde.org">bugs.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://i18n.kde.org">i18n.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://kde.themes.org">kde.themes.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://dot.kde.org">dot.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://webcvs.kde.org/cgi-bin/cvsweb.cgi">webcvs.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://lxr.kde.org">lxr.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://multimedia.kde.org">multimedia.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://games.kde.org">games.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://women.kde.org">women.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://usability.kde.org">usability.kde.org</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="http://edu.kde.org">edu.kde.org</a>
