<?php
  $appinfo = new AppInfo("Kexi");
  $appinfo->setIcon( "pics/cr48-app-kexi.png", "48", "48");
  $appinfo->setVersion($kexiversion);
  $appinfo->setLicense("lgpl");
  $appinfo->setCopyright("2002", "the Kexi Team");
  $appinfo->addAuthor("Lucijan Busch", "&#108;&#x75;c&#00105;ja&#110;&#064;k&#100;&#x65;.&#x6f;&#114;g");
  $appinfo->addAuthor("Peter Simonsson", "psn&#x40;&#0108;i&#00110;&#0117;&#x78;.&#x73;e");
  $appinfo->addAuthor("Joseph Wenninger", "&#00106;o&#00119;enn&#x40;&#x6b;&#x64;&#x65;&#46;org");
  $appinfo->addMaintainer("Jaros&#322;aw Staniek", "mailt&#x6f;&#x3a;&#115;&#116;&#97;&#110;&#105;&#101;&#107;&#64;&#107;&#100;&#101;&#46;&#111;&#114;&#103;");
  $appinfo->addContributor("Adam Pigg", "adam @ piggz . fsnet . co . uk");
  $appinfo->addContributor("C&eacute;dric Pasteur", "cedric . pasteur @ free . fr");
  $appinfo->addContributor("Martin Ellis", "martin .  ellis @ kdemail . net");
  $appinfo->addContributor("Sebastian Sauer", "mail @ dipe . org");
  $appinfo->addContributor("Christian Nitschkowski", "segfault_ii @ web . de");
?>