<?php
$this->appendLink("Information","index.php");
$this->appendLink("Screenshots","screenshots.php");
$this->appendLink("Features","features.php");
$this->appendLink("Kexi FAQ","http://www.kexi-project.org/wiki/wikiview/index.php?KexiFAQ", false);
$this->appendLink("Current Version","versions.php");
$this->appendLink("Development","development.php");
$this->appendLink("HandBook", "http://docs.kde.org/development/en/koffice/kexi/", false );
$this->appendLink("More Info","more_info.php",false);
?>
