<?php
$this->appendLink("Information","index.php");
$this->appendLink("Screenshots","screenshots.php");
$this->appendLink("Features","features.php");
$this->appendLink("Screenshots","screenshots.php");
$this->appendLink("Kexi FAQ","http://www.kexi-project.org/wiki/wikiview/index.php?KexiFAQ");
$this->appendLink("Current Version","versions.php");
$this->appendLink("Development","development.php");
$this->appendLink("More Info","more_info.php",false);
?>
