<?php
  $appinfo = new AppInfo("KWord");
  $appinfo->setIcon( "pics/hi48-app-kword.png", "48", "48");
  $appinfo->setVersion($kwordversion);
  $appinfo->setLicense("lgpl");
  $appinfo->setCopyright("1998", "the KWord Team");
  $appinfo->addAuthor("Reginald Stadlbauer", "&#114;eggi&#101;&#0064;k&#0100;e&#x2e;&#111;&#x72;g");
  $appinfo->addAuthor("Torben Weis", "&#0119;e&#x69;&#115;&#64;&#x6b;de.o&#x72;&#103;");
  $appinfo->addContributor("David Faure", "&#0102;a&#117;r&#101;&#x40;k&#100;e&#x2e;org");
  $appinfo->addContributor("Thomas Zander", "&#x7a;&#x61;n&#x64;&#101;r&#00064;&#107;&#x64;&#101;&#46;or&#00103;");
  $appinfo->addContributor("Shaheed Haque", "sr&#104;a&#x71;&#x75;e&#x40;&#105;&#00101;&#x65;e.o&#0114;&#103;");
  $appinfo->addContributor("Laurent Montel", "&#x6d;&#x6f;&#x6e;tel&#x40;kde&#x2e;&#111;&#00114;g");
  $appinfo->addContributor("Sven L&uuml;ppken", "s&#x76;e&#00110;&#x40;kd&#101;.o&#114;&#103;");
?>