<?php
$this->appendLink("Information","index.php");
$this->appendLink("Screenshots","screenshots.php");
$this->appendLink("Features","features.php");
$this->appendLink("Templates","templates.php");
$this->appendLink("Euro Sign","euro.php");
$this->appendLink("Screenshots&nbsp;(1.3)","oldscreenshots.php");
$this->appendLink("HandBook", "http://docs.kde.org/development/en/koffice/kword/", false );
$this->appendLink("More Info","more_info.php");
?>
