    <b>KPresenter</b><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="index.phtml">Information</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="screenshots.phtml">Screenshots</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="jobs.phtml">Jobs</a><br />
    <img src="/pics/clear-dot.png" width="15" height="1" alt=" " border="0" /><a class="sidebar" href="implemented.phtml">Features</a><br />
    <p />

    <? include("../applinks.inc"); ?>




