<?php
  $appinfo = new AppInfo("Kivio");
  $appinfo->setIcon( "pics/hi48-app-kivio.png", "48", "48");
  $appinfo->setVersion($kivioversion);
  $appinfo->setLicense("gpl");
  $appinfo->setCopyright("1998", "the Kivio Team");
  $appinfo->addAuthor("Dave Marotti", "landshark666@gmail.com");
  $appinfo->addMaintainer("Peter Simonsson", "p&#115;&#110;&#x40;li&#x6e;ux&#x2e;&#115;&#x65;");
  $appinfo->addContributor("Ian Reinhart Geiser", "ge&#105;&#00115;&#101;&#114;i&#64;kd&#101;&#046;or&#103;");
  $appinfo->addContributor("Laurent Montel", "&#109;o&#x6e;tel&#064;k&#x64;&#101;.&#111;rg");
  $appinfo->addContributor("Frauke Oster", "&#x6f;s&#x74;er&#64;kde.o&#114;g");
?>
