<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-1.2.93.tar.bz2">
koffice-1.2.93.tar.bz2</a></td>
<td><tt>f7635262fbbfb334c32f798233cfc91c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-1.2.93.tar.bz2">
koffice-i18n-1.2.93.tar.bz2</a></td>
<td><tt>cae9a33ecccacf8ef44fd6ad54e23c03</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-af-1.2.93.tar.bz2">
koffice-i18n-af-1.2.93.tar.bz2</a></td>
<td><tt>4f68dace82b9f65ee7b7b0d537e43c88</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-bg-1.2.93.tar.bz2">
koffice-i18n-bg-1.2.93.tar.bz2</a></td>
<td><tt>248df9fd4a51d565a319a982f3c125c4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-ca-1.2.93.tar.bz2">
koffice-i18n-ca-1.2.93.tar.bz2</a></td>
<td><tt>4b9a611e0ae97987930bc1747f36c50f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-cs-1.2.93.tar.bz2">
koffice-i18n-cs-1.2.93.tar.bz2</a></td>
<td><tt>672703b2e3ba31366799f23f577ad17a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-cy-1.2.93.tar.bz2">
koffice-i18n-cy-1.2.93.tar.bz2</a></td>
<td><tt>dadcde6af6cdb62295d5e46d768b6f28</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-da-1.2.93.tar.bz2">
koffice-i18n-da-1.2.93.tar.bz2</a></td>
<td><tt>d9c1a49571f120e22311f7499963afd4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-de-1.2.93.tar.bz2">
koffice-i18n-de-1.2.93.tar.bz2</a></td>
<td><tt>a9f541f1f4932f6651abe225001e0448</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-el-1.2.93.tar.bz2">
koffice-i18n-el-1.2.93.tar.bz2</a></td>
<td><tt>ee9d17bc092f1b0e8f4d8c9ff892cb2f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-en_GB-1.2.93.tar.bz2">
koffice-i18n-en_GB-1.2.93.tar.bz2</a></td>
<td><tt>3757c7e72c273087ae444c9b1b06a461</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-eo-1.2.93.tar.bz2">
koffice-i18n-eo-1.2.93.tar.bz2</a></td>
<td><tt>1fb884c9cec60546514785592043678c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-es-1.2.93.tar.bz2">
koffice-i18n-es-1.2.93.tar.bz2</a></td>
<td><tt>7ad263e5adcbee7fa10ce4bf20c7f190</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-et-1.2.93.tar.bz2">
koffice-i18n-et-1.2.93.tar.bz2</a></td>
<td><tt>23475ea7274e48e954c3cc9e9f810ff9</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-fa-1.2.93.tar.bz2">
koffice-i18n-fa-1.2.93.tar.bz2</a></td>
<td><tt>ce7f96caa443806019cb4491c304d578</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-fr-1.2.93.tar.bz2">
koffice-i18n-fr-1.2.93.tar.bz2</a></td>
<td><tt>a8c6e5a30f3eac73e5bd9460051f9c40</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-he-1.2.93.tar.bz2">
koffice-i18n-he-1.2.93.tar.bz2</a></td>
<td><tt>cb1f878ef816708dc713903b390316ce</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-hu-1.2.93.tar.bz2">
koffice-i18n-hu-1.2.93.tar.bz2</a></td>
<td><tt>b71f8c103995a8d2539cf0d397fbeb8a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-it-1.2.93.tar.bz2">
koffice-i18n-it-1.2.93.tar.bz2</a></td>
<td><tt>70ca3d208414a9decb73370afe60b530</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-ja-1.2.93.tar.bz2">
koffice-i18n-ja-1.2.93.tar.bz2</a></td>
<td><tt>1b15fd7e77a564464a31bf95105f22f1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-nb-1.2.93.tar.bz2">
koffice-i18n-nb-1.2.93.tar.bz2</a></td>
<td><tt>93a94676afc5e01186c90ba371c2eabd</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-nl-1.2.93.tar.bz2">
koffice-i18n-nl-1.2.93.tar.bz2</a></td>
<td><tt>9e31d56b8ced5f145da38c60dc466019</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-nn-1.2.93.tar.bz2">
koffice-i18n-nn-1.2.93.tar.bz2</a></td>
<td><tt>cb32e182eb4da6adb0df023c32e8e1f1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-pl-1.2.93.tar.bz2">
koffice-i18n-pl-1.2.93.tar.bz2</a></td>
<td><tt>ed82bf7b2712fef5cebe52319860c707</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-pt-1.2.93.tar.bz2">
koffice-i18n-pt-1.2.93.tar.bz2</a></td>
<td><tt>0c320248aef209f8ae087ad264c7970a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-pt_BR-1.2.93.tar.bz2">
koffice-i18n-pt_BR-1.2.93.tar.bz2</a></td>
<td><tt>c6ad15be00b2cf5c35169461d34e3574</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-ru-1.2.93.tar.bz2">
koffice-i18n-ru-1.2.93.tar.bz2</a></td>
<td><tt>eb34162625da8cead9ba144cf4be9ff2</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-se-1.2.93.tar.bz2">
koffice-i18n-se-1.2.93.tar.bz2</a></td>
<td><tt>46d65fb6222a0751c96082a5815e7a7c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-sk-1.2.93.tar.bz2">
koffice-i18n-sk-1.2.93.tar.bz2</a></td>
<td><tt>14059b1778e5c4d065cc37cdd26ff8b4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-sl-1.2.93.tar.bz2">
koffice-i18n-sl-1.2.93.tar.bz2</a></td>
<td><tt>921b2e0710262581355b42bd9e7a51fa</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-sr-1.2.93.tar.bz2">
koffice-i18n-sr-1.2.93.tar.bz2</a></td>
<td><tt>004b501167a411c6909d9234673da430</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-sv-1.2.93.tar.bz2">
koffice-i18n-sv-1.2.93.tar.bz2</a></td>
<td><tt>569613e6cbe4ca79b5812762398a18d8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-tr-1.2.93.tar.bz2">
koffice-i18n-tr-1.2.93.tar.bz2</a></td>
<td><tt>84a1f9ef140dff65ef447570e880ba07</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-ven-1.2.93.tar.bz2">
koffice-i18n-ven-1.2.93.tar.bz2</a></td>
<td><tt>cae6fe8f310ded9274695064ef600b85</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-xh-1.2.93.tar.bz2">
koffice-i18n-xh-1.2.93.tar.bz2</a></td>
<td><tt>9df5b66fbc64462f74a4e04ed96921f7</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-zh_CN-1.2.93.tar.bz2">
koffice-i18n-zh_CN-1.2.93.tar.bz2</a></td>
<td><tt>f5dca5414fbb609f396d98518f87fb98</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.93/src/koffice-i18n-zh_TW-1.2.93.tar.bz2">
koffice-i18n-zh_TW-1.2.93.tar.bz2</a></td>
<td><tt>34676a28dc843d5a7a170fbb70a8e5ec</tt></td></tr>
</table>
