<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-1.2.91.tar.bz2">
koffice-1.2.91.tar.bz2</a></td>
<td><tt>901c01e4c6e301a76155b5e73f141608</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-1.2.91.tar.bz2">
koffice-i18n-1.2.91.tar.bz2</a></td>
<td><tt>c9df3de027d729e8597cb8fc408bf114</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-af-1.2.91.tar.bz2">
koffice-i18n-af-1.2.91.tar.bz2</a></td>
<td><tt>aaded13451883cb25dbe95cd341a30ea</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-bg-1.2.91.tar.bz2">
koffice-i18n-bg-1.2.91.tar.bz2</a></td>
<td><tt>b9bcb84d1acf0d3c7d1e6994b6a720ca</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-ca-1.2.91.tar.bz2">
koffice-i18n-ca-1.2.91.tar.bz2</a></td>
<td><tt>38a82cf714574146e82a0c2ca36cae29</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-cs-1.2.91.tar.bz2">
koffice-i18n-cs-1.2.91.tar.bz2</a></td>
<td><tt>bc3004b2763d00e79766984a16c2d4ac</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-da-1.2.91.tar.bz2">
koffice-i18n-da-1.2.91.tar.bz2</a></td>
<td><tt>edd4b108e98e4fe58ae2761255a490f5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-de-1.2.91.tar.bz2">
koffice-i18n-de-1.2.91.tar.bz2</a></td>
<td><tt>ce16ee6f8bdc3ca5db4972c3dd795343</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-el-1.2.91.tar.bz2">
koffice-i18n-el-1.2.91.tar.bz2</a></td>
<td><tt>55926f7dfc033cf742e3adfff8e20272</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-en_GB-1.2.91.tar.bz2">
koffice-i18n-en_GB-1.2.91.tar.bz2</a></td>
<td><tt>e70b9850118faf063a4b371e39727352</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-eo-1.2.91.tar.bz2">
koffice-i18n-eo-1.2.91.tar.bz2</a></td>
<td><tt>3731ec785338fa733739600976e930a4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-es-1.2.91.tar.bz2">
koffice-i18n-es-1.2.91.tar.bz2</a></td>
<td><tt>c37ce78d0f776c180187299ae88b045d</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-et-1.2.91.tar.bz2">
koffice-i18n-et-1.2.91.tar.bz2</a></td>
<td><tt>9e85a62822d9e3b2629335b6b885a1eb</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-fa-1.2.91.tar.bz2">
koffice-i18n-fa-1.2.91.tar.bz2</a></td>
<td><tt>d56bcaded194633db3f6494bbb4cb8ed</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-fr-1.2.91.tar.bz2">
koffice-i18n-fr-1.2.91.tar.bz2</a></td>
<td><tt>e22c87d147804e4ecfea4744936a90af</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-he-1.2.91.tar.bz2">
koffice-i18n-he-1.2.91.tar.bz2</a></td>
<td><tt>36eb0aa2cc7a4ea98eb27f14ffc99160</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-hu-1.2.91.tar.bz2">
koffice-i18n-hu-1.2.91.tar.bz2</a></td>
<td><tt>0b6936b29f52ae09c8757e26fd8eb896</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-it-1.2.91.tar.bz2">
koffice-i18n-it-1.2.91.tar.bz2</a></td>
<td><tt>e0f262e0706e035dde1c896e02f4fc81</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-ja-1.2.91.tar.bz2">
koffice-i18n-ja-1.2.91.tar.bz2</a></td>
<td><tt>6ee719f2880273684fed19cd24955759</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-lo-1.2.91.tar.bz2">
koffice-i18n-lo-1.2.91.tar.bz2</a></td>
<td><tt>b1297f47b234354d588f020b22c88b6e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-nb-1.2.91.tar.bz2">
koffice-i18n-nb-1.2.91.tar.bz2</a></td>
<td><tt>1ff327b1e870368f0bb242ea307fc237</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-pt-1.2.91.tar.bz2">
koffice-i18n-pt-1.2.91.tar.bz2</a></td>
<td><tt>96ae5e8b7ede66c1d9e479b4dbdd8643</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-pt_BR-1.2.91.tar.bz2">
koffice-i18n-pt_BR-1.2.91.tar.bz2</a></td>
<td><tt>6aacf2fb03acc30283404ef3bc95a7ef</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-ru-1.2.91.tar.bz2">
koffice-i18n-ru-1.2.91.tar.bz2</a></td>
<td><tt>843ca1b44c1c025f17b5a6b3188571c1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-sk-1.2.91.tar.bz2">
koffice-i18n-sk-1.2.91.tar.bz2</a></td>
<td><tt>c8a4e632a6b6a2cdd8fcf0640aaa637e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-sv-1.2.91.tar.bz2">
koffice-i18n-sv-1.2.91.tar.bz2</a></td>
<td><tt>0aca338d11aa5cc30b4d0843f218a866</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-zh_CN-1.2.91.tar.bz2">
koffice-i18n-zh_CN-1.2.91.tar.bz2</a></td>
<td><tt>1f129870df4174d555017dadd6d2d151</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.91/src/koffice-i18n-zh_TW-1.2.91.tar.bz2">
koffice-i18n-zh_TW-1.2.91.tar.bz2</a></td>
<td><tt>b79e9688be98f493c38588c6efd902e9</tt></td></tr>
</table>
