<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General *</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-1.3.3-1.3.4.tar.xdelta">
koffice-1.3.3-1.3.4.tar.xdelta</a></td>
<td><tt>c3ce9c390350a7e1392e8a49090d87c9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-1.3.4.tar.bz2">
koffice-1.3.4.tar.bz2</a></td>
<td><tt>79896426542b0cf07e2e15f84946905a</tt></td></tr>
<tr><td>All languages *</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-1.3.3-1.3.4.tar.xdelta">
koffice-i18n-1.3.3-1.3.4.tar.xdelta</a></td>
<td><tt>f49adf4234115fc14cf203019402623b</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-1.3.4.tar.bz2">
koffice-i18n-1.3.4.tar.bz2</a></td>
<td><tt>6455f496f6031e810398ad6b065eb929</tt></td></tr>
<tr><td>Afrikaans</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-af-1.3.4.tar.bz2">
koffice-i18n-af-1.3.4.tar.bz2</a></td>
<td><tt>e1a518fe565c146abe0fc745dc2881a3</tt></td></tr>
<tr><td>Bulgarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-bg-1.3.4.tar.bz2">
koffice-i18n-bg-1.3.4.tar.bz2</a></td>
<td><tt>61987311c452f419e1c0bd952381154a</tt></td></tr>
<tr><td>Catalan</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ca-1.3.4.tar.bz2">
koffice-i18n-ca-1.3.4.tar.bz2</a></td>
<td><tt>92f3c35950e45d3ba415e37d83d6b75f</tt></td></tr>
<tr><td>Czech</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-cs-1.3.4.tar.bz2">
koffice-i18n-cs-1.3.4.tar.bz2</a></td>
<td><tt>3dcba3c06d3c5a9708065f6083921670</tt></td></tr>
<tr><td>Welsh</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-cy-1.3.4.tar.bz2">
koffice-i18n-cy-1.3.4.tar.bz2</a></td>
<td><tt>4a58affd253ff26688c1e9a0dce75054</tt></td></tr>
<tr><td>Danish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-da-1.3.4.tar.bz2">
koffice-i18n-da-1.3.4.tar.bz2</a></td>
<td><tt>380f08397afe19a9958539bb692ecb12</tt></td></tr>
<tr><td>German</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-de-1.3.4.tar.bz2">
koffice-i18n-de-1.3.4.tar.bz2</a></td>
<td><tt>0890907543fb8a6a08b841ef88deaf50</tt></td></tr>
<tr><td>Greek</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-el-1.3.4.tar.bz2">
koffice-i18n-el-1.3.4.tar.bz2</a></td>
<td><tt>2553159c99293c505422db1b8543381a</tt></td></tr>
<tr><td>British English</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-en_GB-1.3.4.tar.bz2">
koffice-i18n-en_GB-1.3.4.tar.bz2</a></td>
<td><tt>b570ad31d8f714b94051594b6524809e</tt></td></tr>
<tr><td>Esperanto</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-eo-1.3.4.tar.bz2">
koffice-i18n-eo-1.3.4.tar.bz2</a></td>
<td><tt>f19eef3ff421ebc14fe241e3a0fde047</tt></td></tr>
<tr><td>Spanish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-es-1.3.4.tar.bz2">
koffice-i18n-es-1.3.4.tar.bz2</a></td>
<td><tt>1ea77f3630e893cb5a90e62ef1f46d3c</tt></td></tr>
<tr><td>Estonian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-et-1.3.4.tar.bz2">
koffice-i18n-et-1.3.4.tar.bz2</a></td>
<td><tt>bd92ef9522f9bdf7a3009a4c6cf4ddb2</tt></td></tr>
<tr><td>Farsi</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-fa-1.3.4.tar.bz2">
koffice-i18n-fa-1.3.4.tar.bz2</a></td>
<td><tt>fbabcdde8220e4e63b05284a5d302b71</tt></td></tr>
<tr><td>Finnish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-fi-1.3.4.tar.bz2">
koffice-i18n-fi-1.3.4.tar.bz2</a></td>
<td><tt>be4a80ce938b0c791b9bb91d74bbd7ac</tt></td></tr>
<tr><td>French</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-fr-1.3.4.tar.bz2">
koffice-i18n-fr-1.3.4.tar.bz2</a></td>
<td><tt>499641bb9130458872481fde66711799</tt></td></tr>
<tr><td>Hebrew</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-he-1.3.4.tar.bz2">
koffice-i18n-he-1.3.4.tar.bz2</a></td>
<td><tt>578f8d7dd3893870931db8d2c45d1457</tt></td></tr>
<tr><td>Upper Sorbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-hsb-1.3.4.tar.bz2">
koffice-i18n-hsb-1.3.4.tar.bz2</a></td>
<td><tt>acb5166029429b01d3692d0d1fef0d81</tt></td></tr>
<tr><td>Hungarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-hu-1.3.4.tar.bz2">
koffice-i18n-hu-1.3.4.tar.bz2</a></td>
<td><tt>088995c20287688524c0b7e526cda96a</tt></td></tr>
<tr><td>Italian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-it-1.3.4.tar.bz2">
koffice-i18n-it-1.3.4.tar.bz2</a></td>
<td><tt>87a62e8215f5d28964fa65b0d8ae3cec</tt></td></tr>
<tr><td>Japanese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ja-1.3.4.tar.bz2">
koffice-i18n-ja-1.3.4.tar.bz2</a></td>
<td><tt>2cc18986be537c9ea218c46780c82c20</tt></td></tr>
<tr><td>Lao</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-lo-1.3.4.tar.bz2">
koffice-i18n-lo-1.3.4.tar.bz2</a></td>
<td><tt>18e716c2efd3f9b63b74150a11262ea2</tt></td></tr>
<tr><td>Maltese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-mt-1.3.4.tar.bz2">
koffice-i18n-mt-1.3.4.tar.bz2</a></td>
<td><tt>1b484cae3fc2c0fafe9ab7d24f31dd87</tt></td></tr>
<tr><td>Norwegian Bokm&aring;l</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-nb-1.3.4.tar.bz2">
koffice-i18n-nb-1.3.4.tar.bz2</a></td>
<td><tt>e62a2c0ee5fbce326dce566b37c03380</tt></td></tr>
<tr><td>Dutch</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-nl-1.3.4.tar.bz2">
koffice-i18n-nl-1.3.4.tar.bz2</a></td>
<td><tt>783fd4e43104aac9244befc6aebe9712</tt></td></tr>
<tr><td>Norwegian Nynorsk</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-nn-1.3.4.tar.bz2">
koffice-i18n-nn-1.3.4.tar.bz2</a></td>
<td><tt>c37e618786f5a0132566f6c9d3021b74</tt></td></tr>
<tr><td>Polish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-pl-1.3.4.tar.bz2">
koffice-i18n-pl-1.3.4.tar.bz2</a></td>
<td><tt>cb6b521cd8f144c7a7d78bd6eab85076</tt></td></tr>
<tr><td>Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-pt-1.3.4.tar.bz2">
koffice-i18n-pt-1.3.4.tar.bz2</a></td>
<td><tt>b6de43a4ef23552406313f7a20113c26</tt></td></tr>
<tr><td>Brazilian Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-pt_BR-1.3.4.tar.bz2">
koffice-i18n-pt_BR-1.3.4.tar.bz2</a></td>
<td><tt>5c594e12ce1809ac4cd556dc7e953f78</tt></td></tr>
<tr><td>Russian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ru-1.3.4.tar.bz2">
koffice-i18n-ru-1.3.4.tar.bz2</a></td>
<td><tt>ee559623b65809b71ebc36a1c9f6efa8</tt></td></tr>
<tr><td>Northern Sami</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-se-1.3.4.tar.bz2">
koffice-i18n-se-1.3.4.tar.bz2</a></td>
<td><tt>279bd7df48d4f3ef07eaca20031ab37f</tt></td></tr>
<tr><td>Slovak</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sk-1.3.4.tar.bz2">
koffice-i18n-sk-1.3.4.tar.bz2</a></td>
<td><tt>8232f07452ac048f7ad8464f3c4cead5</tt></td></tr>
<tr><td>Slovenian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sl-1.3.4.tar.bz2">
koffice-i18n-sl-1.3.4.tar.bz2</a></td>
<td><tt>54f87c7f2c9b6735d7ae590f7a07f17d</tt></td></tr>
<tr><td>Serbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sr-1.3.4.tar.bz2">
koffice-i18n-sr-1.3.4.tar.bz2</a></td>
<td><tt>873d280b5da5814273521cb57fec06d8</tt></td></tr>
<tr><td>Swedish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sv-1.3.4.tar.bz2">
koffice-i18n-sv-1.3.4.tar.bz2</a></td>
<td><tt>759a81ab33b5bc99c8816446df8720c7</tt></td></tr>
<tr><td>Tajik</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-tg-1.3.4.tar.bz2">
koffice-i18n-tg-1.3.4.tar.bz2</a></td>
<td><tt>6cc89e3f85b21c965b06734e429f0268</tt></td></tr>
<tr><td>Thai</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-th-1.3.4.tar.bz2">
koffice-i18n-th-1.3.4.tar.bz2</a></td>
<td><tt>d79550250d01646770dfddf1b434abf2</tt></td></tr>
<tr><td>Turkish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-tr-1.3.4.tar.bz2">
koffice-i18n-tr-1.3.4.tar.bz2</a></td>
<td><tt>7fe59f9e9c8ce968231f891bd8aadd25</tt></td></tr>
<tr><td>Venda</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ven-1.3.4.tar.bz2">
koffice-i18n-ven-1.3.4.tar.bz2</a></td>
<td><tt>507a2917fd219cafd4a5c954b7bb7c41</tt></td></tr>
<tr><td>Xhosa</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-xh-1.3.4.tar.bz2">
koffice-i18n-xh-1.3.4.tar.bz2</a></td>
<td><tt>1fe2f07ef22069d3435a478b5b26602e</tt></td></tr>
<tr><td>Chinese Simplified</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-zh_CN-1.3.4.tar.bz2">
koffice-i18n-zh_CN-1.3.4.tar.bz2</a></td>
<td><tt>7bde884bc10758ad5d6ae95bd495b9c2</tt></td></tr>
<tr><td>Chinese Traditional</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-zh_TW-1.3.4.tar.bz2">
koffice-i18n-zh_TW-1.3.4.tar.bz2</a></td>
<td><tt>2b5e8abc051be19ec0ffad8807dcb570</tt></td></tr>
<tr><td>Zulu</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-zu-1.3.4.tar.bz2">
koffice-i18n-zu-1.3.4.tar.bz2</a></td>
<td><tt>29a28b859e3ed6f14d3961dc24c442a3</tt></td></tr>
</table>
<p>*: XDelta patches</p>
