<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-1.3.1-1.3.2.tar.xdelta">
koffice-1.3.1-1.3.2.tar.xdelta</a></td>
<td><tt>3fd3504c53acdd9794f80a76d82e3ba9</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-1.3.2.tar.bz2">
koffice-1.3.2.tar.bz2</a></td>
<td><tt>078a371f6768bea53b84ea342ac0b34b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-1.3.1-1.3.2.tar.xdelta">
koffice-i18n-1.3.1-1.3.2.tar.xdelta</a></td>
<td><tt>3c77f956b7d857ddeed9626319f3c3e8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-1.3.2.tar.bz2">
koffice-i18n-1.3.2.tar.bz2</a></td>
<td><tt>228d933c13da33f3d66c5d0f3f4b5ef1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-af-1.3.2.tar.bz2">
koffice-i18n-af-1.3.2.tar.bz2</a></td>
<td><tt>1c6c45574d4967f61622eee62c670505</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-bg-1.3.2.tar.bz2">
koffice-i18n-bg-1.3.2.tar.bz2</a></td>
<td><tt>274f1bad8e264499395ba1e141b7d08e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-ca-1.3.2.tar.bz2">
koffice-i18n-ca-1.3.2.tar.bz2</a></td>
<td><tt>64b81f2e77cecb2d1351a4b020bac9d9</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-cs-1.3.2.tar.bz2">
koffice-i18n-cs-1.3.2.tar.bz2</a></td>
<td><tt>f4757ee4fc27284de38df5fddc1955d5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-da-1.3.2.tar.bz2">
koffice-i18n-da-1.3.2.tar.bz2</a></td>
<td><tt>dec78da3da7685d5d2ffea73c68323ae</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-de-1.3.2.tar.bz2">
koffice-i18n-de-1.3.2.tar.bz2</a></td>
<td><tt>a72c3b0560f09236c6592cd9f9e3183a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-el-1.3.2.tar.bz2">
koffice-i18n-el-1.3.2.tar.bz2</a></td>
<td><tt>35d810ee4b2a432fee24c19c9e9fa997</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-en_GB-1.3.2.tar.bz2">
koffice-i18n-en_GB-1.3.2.tar.bz2</a></td>
<td><tt>d482c100ebe5ff4fdd666d8968b36e54</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-eo-1.3.2.tar.bz2">
koffice-i18n-eo-1.3.2.tar.bz2</a></td>
<td><tt>2a20daab35034fddcb7643a8aad41dca</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-es-1.3.2.tar.bz2">
koffice-i18n-es-1.3.2.tar.bz2</a></td>
<td><tt>a3b1067594093968644ddd22c9501120</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-et-1.3.2.tar.bz2">
koffice-i18n-et-1.3.2.tar.bz2</a></td>
<td><tt>fefea899f957e8cfe2e9b2a46a7c8895</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-fa-1.3.2.tar.bz2">
koffice-i18n-fa-1.3.2.tar.bz2</a></td>
<td><tt>405977750c2e48dc5413d40b52484f2d</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-fi-1.3.2.tar.bz2">
koffice-i18n-fi-1.3.2.tar.bz2</a></td>
<td><tt>33239d6de9e82b5591891f6be94929a1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-fr-1.3.2.tar.bz2">
koffice-i18n-fr-1.3.2.tar.bz2</a></td>
<td><tt>55a7f6d8f69212000d921ede183f3d87</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-he-1.3.2.tar.bz2">
koffice-i18n-he-1.3.2.tar.bz2</a></td>
<td><tt>8d4fdd46c3d543871e70c4f6a2db23b0</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-hsb-1.3.2.tar.bz2">
koffice-i18n-hsb-1.3.2.tar.bz2</a></td>
<td><tt>678b911c397e87446cb5665fc24d6bfe</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-hu-1.3.2.tar.bz2">
koffice-i18n-hu-1.3.2.tar.bz2</a></td>
<td><tt>ec6bc2c518ddb1cb12da672df0e2beea</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-it-1.3.2.tar.bz2">
koffice-i18n-it-1.3.2.tar.bz2</a></td>
<td><tt>76b0983454ff1af4f116f25e1fdb26c1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-ja-1.3.2.tar.bz2">
koffice-i18n-ja-1.3.2.tar.bz2</a></td>
<td><tt>5c54a627e80d2b5e005872e5d1ceecb1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-lo-1.3.2.tar.bz2">
koffice-i18n-lo-1.3.2.tar.bz2</a></td>
<td><tt>3272c4d54c32af0b7c24cb146d3918de</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-mt-1.3.2.tar.bz2">
koffice-i18n-mt-1.3.2.tar.bz2</a></td>
<td><tt>05632fdda445dd376fe312c0dbcaf519</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-nb-1.3.2.tar.bz2">
koffice-i18n-nb-1.3.2.tar.bz2</a></td>
<td><tt>152cd5f93bfbc48fa1a5ba773e6b346a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-nl-1.3.2.tar.bz2">
koffice-i18n-nl-1.3.2.tar.bz2</a></td>
<td><tt>d40a5d78ddead57fe8a5806499db83eb</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-nn-1.3.2.tar.bz2">
koffice-i18n-nn-1.3.2.tar.bz2</a></td>
<td><tt>6366cc39f1ccd6e3a9e3520940adc43d</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-pl-1.3.2.tar.bz2">
koffice-i18n-pl-1.3.2.tar.bz2</a></td>
<td><tt>f186986ae7bc54a7e94764005e11858e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-pt-1.3.2.tar.bz2">
koffice-i18n-pt-1.3.2.tar.bz2</a></td>
<td><tt>24c498db0818cbb875821b6b52c9d7de</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-pt_BR-1.3.2.tar.bz2">
koffice-i18n-pt_BR-1.3.2.tar.bz2</a></td>
<td><tt>cfc572fe9b786539f11fbdb81c0920bf</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-ru-1.3.2.tar.bz2">
koffice-i18n-ru-1.3.2.tar.bz2</a></td>
<td><tt>4c95ffa437b05adbd51cc1e98eb46694</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-se-1.3.2.tar.bz2">
koffice-i18n-se-1.3.2.tar.bz2</a></td>
<td><tt>59b96c0cf07ce480ac3b0c7158374ea4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-sk-1.3.2.tar.bz2">
koffice-i18n-sk-1.3.2.tar.bz2</a></td>
<td><tt>0932c38864fea2a5bde5b979231cd59e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-sl-1.3.2.tar.bz2">
koffice-i18n-sl-1.3.2.tar.bz2</a></td>
<td><tt>71719ccc7de04323f20defe02dc4577c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-sr-1.3.2.tar.bz2">
koffice-i18n-sr-1.3.2.tar.bz2</a></td>
<td><tt>73c0dbc96161499a43ae48a4e335d242</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-sv-1.3.2.tar.bz2">
koffice-i18n-sv-1.3.2.tar.bz2</a></td>
<td><tt>f5431d336eca9b5baff397eb18736a22</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-tg-1.3.2.tar.bz2">
koffice-i18n-tg-1.3.2.tar.bz2</a></td>
<td><tt>13989d70392f561ee5336c4dc88426de</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-th-1.3.2.tar.bz2">
koffice-i18n-th-1.3.2.tar.bz2</a></td>
<td><tt>0eb58c7ff314d87f555cd4309b498bfe</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-tr-1.3.2.tar.bz2">
koffice-i18n-tr-1.3.2.tar.bz2</a></td>
<td><tt>46b6958734ece8ffa3ecec6a1230a958</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-ven-1.3.2.tar.bz2">
koffice-i18n-ven-1.3.2.tar.bz2</a></td>
<td><tt>30b2967313efab532c93d2c340d9779f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-xh-1.3.2.tar.bz2">
koffice-i18n-xh-1.3.2.tar.bz2</a></td>
<td><tt>aa05a8d90700bd5da18de815b0253cbc</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-zh_CN-1.3.2.tar.bz2">
koffice-i18n-zh_CN-1.3.2.tar.bz2</a></td>
<td><tt>389e69fa0bd37272816bd6805605c7bd</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-zh_TW-1.3.2.tar.bz2">
koffice-i18n-zh_TW-1.3.2.tar.bz2</a></td>
<td><tt>c14c620526da6c1c5dae35c275bc19e1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.2/src/koffice-i18n-zu-1.3.2.tar.bz2">
koffice-i18n-zu-1.3.2.tar.bz2</a></td>
<td><tt>8085b4f502539d037f5c5dc8dcd2ed86</tt></td></tr>
</table>
