<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-1.3.98.tar.bz2">
koffice-1.3.98.tar.bz2</a></td>
<td><tt>754e565383783f5e22f7b7483123868e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-bg-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-bg-1.3.98.tar.bz2</a></td>
<td><tt>217de9f296e58d555cc3000aa53ec48f</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-ca-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.3.98.tar.bz2</a></td>
<td><tt>9d024ad4abcc31257baf0aa88455aba4</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-cs-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.3.98.tar.bz2</a></td>
<td><tt>acca6dacf01981b5b2c43bd7efdd25f6</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-cy-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.3.98.tar.bz2</a></td>
<td><tt>3cbd4cf2ab3cbbba58c70b2d60c68cc3</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-da-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-da-1.3.98.tar.bz2</a></td>
<td><tt>b278a5ba4cbc4bbcc3389e4297c00900</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-de-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-de-1.3.98.tar.bz2</a></td>
<td><tt>16c1fce15802dae3eeaf70e671a89fad</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-el-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-el-1.3.98.tar.bz2</a></td>
<td><tt>3f2097d293325713736eb7f9275668ed</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-en_GB-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.3.98.tar.bz2</a></td>
<td><tt>319f6dc14fd87ba0d8b1137564ef32c8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-es-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-es-1.3.98.tar.bz2</a></td>
<td><tt>d415ea461e451fca0f9af683c6278d15</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-et-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-et-1.3.98.tar.bz2</a></td>
<td><tt>fd663a45f05d38ddac6212eb0f9528c9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-fr-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.3.98.tar.bz2</a></td>
<td><tt>ebf7e75455c9aa9b7539d81f7b9b8adc</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-hu-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.3.98.tar.bz2</a></td>
<td><tt>a1ab23a08414c93642dc7ba512f9552b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-it-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-it-1.3.98.tar.bz2</a></td>
<td><tt>6577a439a88acc1780fc918009340b80</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-nb-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.3.98.tar.bz2</a></td>
<td><tt>91ec70b9cf08164af4616b6f6fc9dccb</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-nl-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.3.98.tar.bz2</a></td>
<td><tt>02d98b459afa73eb726b46ca08b3224e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-nn-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-nn-1.3.98.tar.bz2</a></td>
<td><tt>7297a5d4e19b14de4efe507d7130ed0d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-pt-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.3.98.tar.bz2</a></td>
<td><tt>c17264c4462a09cebbb4bc3d30dcc3ce</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-pt_BR-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.3.98.tar.bz2</a></td>
<td><tt>fcd1555f1c41b656a662dac498d614e4</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-ru-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.3.98.tar.bz2</a></td>
<td><tt>7dc876321dd47f2e067612df7c8d4982</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-sl-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.3.98.tar.bz2</a></td>
<td><tt>ebecb7df80f1740cf9021ceb2c1ee40d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-sr-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.3.98.tar.bz2</a></td>
<td><tt>b0cc6d611be93b3588b63d7c830d977c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-sr@Latn-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.3.98.tar.bz2</a></td>
<td><tt>2fd843e5002d77b023f61eefb0ccc2f8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-sv-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.3.98.tar.bz2</a></td>
<td><tt>3876a1488f95e124c4ee004fde3ed45b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-ta-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-ta-1.3.98.tar.bz2</a></td>
<td><tt>ef9052a4c81ff0987aff9f49925304fe</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-tg-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-tg-1.3.98.tar.bz2</a></td>
<td><tt>1c8cbe2fc2215feb5826f5ac7e0e7061</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-rc1/src/koffice-l10n/koffice-l10n-zh_CN-1.3.98.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.3.98.tar.bz2</a></td>
<td><tt>ec292a0c8578cacf58560b4f14cc818d</tt></td></tr>
</table>
<p>*: XDelta patches</p>
