<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-1.3.tar.bz2">
koffice-1.3.tar.bz2</a></td>
<td><tt>8e4c9db57f701d42f21d61651f0b03bd</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-1.3.tar.bz2">
koffice-i18n-1.3.tar.bz2</a></td>
<td><tt>ca89c9c944508de11ca2908eb0a851e4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-af-1.3.tar.bz2">
koffice-i18n-af-1.3.tar.bz2</a></td>
<td><tt>36afe0209288c827285a65c73ac52303</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-bg-1.3.tar.bz2">
koffice-i18n-bg-1.3.tar.bz2</a></td>
<td><tt>37ddacc121c50d7eb597da800478a99d</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-ca-1.3.tar.bz2">
koffice-i18n-ca-1.3.tar.bz2</a></td>
<td><tt>6b9fc98cd1ff64d31adee67c9dc7c176</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-cs-1.3.tar.bz2">
koffice-i18n-cs-1.3.tar.bz2</a></td>
<td><tt>a6c5aecc656d98ec6cf7e2b157d79761</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-da-1.3.tar.bz2">
koffice-i18n-da-1.3.tar.bz2</a></td>
<td><tt>cd40cc7c4d8803fa80a39380af163bcd</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-de-1.3.tar.bz2">
koffice-i18n-de-1.3.tar.bz2</a></td>
<td><tt>4d90b5cd3920e3f2e5d2f7ed03fb9cba</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-el-1.3.tar.bz2">
koffice-i18n-el-1.3.tar.bz2</a></td>
<td><tt>48e15a1e3210134e1426be61673e135b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-en_GB-1.3.tar.bz2">
koffice-i18n-en_GB-1.3.tar.bz2</a></td>
<td><tt>b15124b835f771efe80620496a5ad281</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-eo-1.3.tar.bz2">
koffice-i18n-eo-1.3.tar.bz2</a></td>
<td><tt>d5ab142b00c37831e607decf6373049b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-es-1.3.tar.bz2">
koffice-i18n-es-1.3.tar.bz2</a></td>
<td><tt>236cb0474c0a0812fff0bd282560e3b9</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-et-1.3.tar.bz2">
koffice-i18n-et-1.3.tar.bz2</a></td>
<td><tt>8ab3fc6ae0344f721d73d45e9d0b86e8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-fa-1.3.tar.bz2">
koffice-i18n-fa-1.3.tar.bz2</a></td>
<td><tt>983de2dc9791a5364d35e85a21e41f10</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-fi-1.3.tar.bz2">
koffice-i18n-fi-1.3.tar.bz2</a></td>
<td><tt>152028c099959d1c383a54cef488660f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-fr-1.3.tar.bz2">
koffice-i18n-fr-1.3.tar.bz2</a></td>
<td><tt>851708c580e92865e9102a24d822f8e5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-he-1.3.tar.bz2">
koffice-i18n-he-1.3.tar.bz2</a></td>
<td><tt>30072797fde370a2ebbbfc4cac37486e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-hu-1.3.tar.bz2">
koffice-i18n-hu-1.3.tar.bz2</a></td>
<td><tt>5fead9ce6913b88d38887131c516dca5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-it-1.3.tar.bz2">
koffice-i18n-it-1.3.tar.bz2</a></td>
<td><tt>b636ede70ce159695439fa37ddf00606</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-ja-1.3.tar.bz2">
koffice-i18n-ja-1.3.tar.bz2</a></td>
<td><tt>ef6d36fb4201d0bfa632ccf36af5b640</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-lo-1.3.tar.bz2">
koffice-i18n-lo-1.3.tar.bz2</a></td>
<td><tt>7e0cecb44263b5c0fd81cbb26c98529b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-mt-1.3.tar.bz2">
koffice-i18n-mt-1.3.tar.bz2</a></td>
<td><tt>29513820ecf2f2c621bafe554a3c48df</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-nb-1.3.tar.bz2">
koffice-i18n-nb-1.3.tar.bz2</a></td>
<td><tt>3ccae87fefcfb7867eb4be0eacef9d62</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-nl-1.3.tar.bz2">
koffice-i18n-nl-1.3.tar.bz2</a></td>
<td><tt>7847f7ef84b9a1a31b7257405a4851e2</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-nn-1.3.tar.bz2">
koffice-i18n-nn-1.3.tar.bz2</a></td>
<td><tt>2f982858e44cd5f5191b1bef5a57b4e1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-pl-1.3.tar.bz2">
koffice-i18n-pl-1.3.tar.bz2</a></td>
<td><tt>c8e5503168699944784d3a61e0dfe1e0</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-pt-1.3.tar.bz2">
koffice-i18n-pt-1.3.tar.bz2</a></td>
<td><tt>c7385013bef2453404d6ea6ecf07d654</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-pt_BR-1.3.tar.bz2">
koffice-i18n-pt_BR-1.3.tar.bz2</a></td>
<td><tt>e9e7e4b054d5d1f2f6cd450a632c1dc9</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-ru-1.3.tar.bz2">
koffice-i18n-ru-1.3.tar.bz2</a></td>
<td><tt>e4876dabcfc7cab4de98cc26583e71b7</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-se-1.3.tar.bz2">
koffice-i18n-se-1.3.tar.bz2</a></td>
<td><tt>23f9b561675619babf3f46b80c7ee603</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-sk-1.3.tar.bz2">
koffice-i18n-sk-1.3.tar.bz2</a></td>
<td><tt>19d3c081e923ec9df6eb8dd59b643901</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-sl-1.3.tar.bz2">
koffice-i18n-sl-1.3.tar.bz2</a></td>
<td><tt>f6523bac1730255407e73ef7a2b6a1e1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-sr-1.3.tar.bz2">
koffice-i18n-sr-1.3.tar.bz2</a></td>
<td><tt>ce5303b8c7ef65474e83f79d25477eb7</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-sv-1.3.tar.bz2">
koffice-i18n-sv-1.3.tar.bz2</a></td>
<td><tt>bac2fb1ac55d0fe676faf936ec712bcc</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-th-1.3.tar.bz2">
koffice-i18n-th-1.3.tar.bz2</a></td>
<td><tt>98e53f0a2cfde85e859192398606d6de</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-tr-1.3.tar.bz2">
koffice-i18n-tr-1.3.tar.bz2</a></td>
<td><tt>aefac0daf595e5357ba22d57753bb3c1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-ven-1.3.tar.bz2">
koffice-i18n-ven-1.3.tar.bz2</a></td>
<td><tt>aef8d0bb5e6878c80c969462b2e24c5f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-xh-1.3.tar.bz2">
koffice-i18n-xh-1.3.tar.bz2</a></td>
<td><tt>7b8de6dbf6b0e76d1735c8358e2a31cb</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-zh_CN-1.3.tar.bz2">
koffice-i18n-zh_CN-1.3.tar.bz2</a></td>
<td><tt>350238f5c52f1a040df561261aa8ce10</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-zh_TW-1.3.tar.bz2">
koffice-i18n-zh_TW-1.3.tar.bz2</a></td>
<td><tt>ed757efe0e1bed3d371b740a6c68801d</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3/src/koffice-i18n-zu-1.3.tar.bz2">
koffice-i18n-zu-1.3.tar.bz2</a></td>
<td><tt>51cfaf7f79366b408c4b0b242bf42e38</tt></td></tr>
</table>
