<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-1.5.2.tar.bz2">
koffice-1.5.2.tar.bz2</a></td>
<td><tt>cbe9deeb7c811a6bb5a954989b25c1f2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/keximdb-1.0.2.tar.gz">
keximdb-1.0.2.tar.gz</a></td>
<td><tt>5d63539e8ee69b9f4bb27932d809fde4</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-af-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-af-1.5.2.tar.bz2</a></td>
<td><tt>c7a48bb275230d1152e29c67a869daee</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ar-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ar-1.5.2.tar.bz2</a></td>
<td><tt>a35e9b3f75265488ca400469f23a5a91</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-bg-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-bg-1.5.2.tar.bz2</a></td>
<td><tt>b8be1348ffab32d826c358d44de68c5e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-br-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-br-1.5.2.tar.bz2</a></td>
<td><tt>fd0738d2c9538994de3573ec00964cf1</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-bs-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-bs-1.5.2.tar.bz2</a></td>
<td><tt>b7de9b93298aba597d9d8f8da038fc37</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ca-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.5.2.tar.bz2</a></td>
<td><tt>8e3ff02096b6574cf337430924d5af98</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-cs-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.5.2.tar.bz2</a></td>
<td><tt>b8f83541b98ff0cb8361f797f665971c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-cy-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.5.2.tar.bz2</a></td>
<td><tt>64782ef55dbdfbbc3672b613dc7f5faf</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-da-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-da-1.5.2.tar.bz2</a></td>
<td><tt>58c13527c47dee445572d26141fd3269</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-de-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-de-1.5.2.tar.bz2</a></td>
<td><tt>ef007ab98ffe65ce072a9245f51b01e1</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-el-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-el-1.5.2.tar.bz2</a></td>
<td><tt>4392e652560adb8c83fe2aac9479fcb8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-en_GB-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.5.2.tar.bz2</a></td>
<td><tt>11b499953ae1616c589e793abc4e474b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-eo-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-eo-1.5.2.tar.bz2</a></td>
<td><tt>c7025f7d946342267943fd146a5cc19c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-es-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-es-1.5.2.tar.bz2</a></td>
<td><tt>fb0ddfb9d7e6bbcb8fe9ebfc8d04b2cc</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-et-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-et-1.5.2.tar.bz2</a></td>
<td><tt>fed89528182c0dc7baa2c50fee165270</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-eu-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-eu-1.5.2.tar.bz2</a></td>
<td><tt>3e15c7433f91486d8b76eefb19990a74</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-fi-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.5.2.tar.bz2</a></td>
<td><tt>de6a7a2b2b2edc1a4eaad7523b1bab39</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-fr-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.5.2.tar.bz2</a></td>
<td><tt>8f868a919c6ccb66b719196d3e842910</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ga-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ga-1.5.2.tar.bz2</a></td>
<td><tt>b8b4d4cbb0ff29bc0da4954eb9ba4e13</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-he-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-he-1.5.2.tar.bz2</a></td>
<td><tt>a0368a287bf2a3566b802ffe6de8b472</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-hi-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-hi-1.5.2.tar.bz2</a></td>
<td><tt>95a4edd9df2b1c4744ae0b590d68822a</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-hu-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.5.2.tar.bz2</a></td>
<td><tt>cd57e11f100ffabf6a3c72faa6433569</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-is-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-is-1.5.2.tar.bz2</a></td>
<td><tt>e3b5ec6948dea217e79d3c692d3e3bd3</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-it-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-it-1.5.2.tar.bz2</a></td>
<td><tt>9658442039b455e52cf68599e3250f54</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ja-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ja-1.5.2.tar.bz2</a></td>
<td><tt>7eb7880c8e03a8c905a7bba06423fdde</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-lt-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-lt-1.5.2.tar.bz2</a></td>
<td><tt>bf8fb56e3b2ab401d4b3ac9e19ad30f4</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-mk-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-mk-1.5.2.tar.bz2</a></td>
<td><tt>8f9a9ccea194653be186517c0879fe8c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ms-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ms-1.5.2.tar.bz2</a></td>
<td><tt>617ab3344f714fa9109875bc50b79502</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-nb-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.5.2.tar.bz2</a></td>
<td><tt>02adef48c63e4a9f87fed63cefb19d1d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-nl-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.5.2.tar.bz2</a></td>
<td><tt>9847ff8d7dbddf4c2f1ae4a6cb0694d1</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-nn-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-nn-1.5.2.tar.bz2</a></td>
<td><tt>9926f8aa4449e839d40f97e7c621de96</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-pl-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.5.2.tar.bz2</a></td>
<td><tt>193d09145eea9136067676b6d74ab5f9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-pt-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.5.2.tar.bz2</a></td>
<td><tt>f8d4e8990e1f24ef6076de1c9698458f</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-pt_BR-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.5.2.tar.bz2</a></td>
<td><tt>bba591e0460c4a0169c07c3d5ae5b118</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ro-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ro-1.5.2.tar.bz2</a></td>
<td><tt>22d91909560288e7dd79a3db6e2aab42</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ru-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.5.2.tar.bz2</a></td>
<td><tt>e0a809bf7c9202cf5eebaaa93999f4f3</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-se-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-se-1.5.2.tar.bz2</a></td>
<td><tt>8fa484cd096f3f8461c054bad31c3601</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-sk-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-sk-1.5.2.tar.bz2</a></td>
<td><tt>a7dbf6b5fa42d0cdee1f0928cbaadfd0</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-sl-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.5.2.tar.bz2</a></td>
<td><tt>e5fe2c8a350ba2636f4bd8dd2168b017</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-sr-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.5.2.tar.bz2</a></td>
<td><tt>2717a1e1e1ff92d1e962e3b69625e906</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-sr@Latn-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.5.2.tar.bz2</a></td>
<td><tt>f7774ad33c0efb072653495894865e0e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-sv-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.5.2.tar.bz2</a></td>
<td><tt>83f73110f60ef4b5f633e3cca0dd4e12</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-ta-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-ta-1.5.2.tar.bz2</a></td>
<td><tt>3f0ce9e790415b90daf43c35736a62e7</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-tg-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-tg-1.5.2.tar.bz2</a></td>
<td><tt>add764f98fd61d74bf0886f4bfe7808f</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-tr-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-tr-1.5.2.tar.bz2</a></td>
<td><tt>6b7df893cae7725ca94979a4dcd73edf</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-uk-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-uk-1.5.2.tar.bz2</a></td>
<td><tt>a31dc3319a452ae7d2d689ac50a73bb0</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-uz-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-uz-1.5.2.tar.bz2</a></td>
<td><tt>259739c2bde6d4fb890915cf7f3358c9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-zh_CN-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.5.2.tar.bz2</a></td>
<td><tt>e2de60faab2bc7049e2b4af6827cbe8e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-zh_TW-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-zh_TW-1.5.2.tar.bz2</a></td>
<td><tt>a39dcaf36d9361d2915399ee0dce0cc0</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.2/src/koffice-l10n/koffice-l10n-zh_TW-1.5.2.tar.bz2">
koffice-l10n/koffice-l10n-zh_TW-1.5.2.tar.bz2</a></td>
<td><tt>a39dcaf36d9361d2915399ee0dce0cc0</tt></td></tr>
</table>
<p>*: XDelta patches</p>
