<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-1.4.1.tar.bz2">
koffice-1.4.1.tar.bz2</a></td>
<td><tt>91a7b68757addc5934c5a8209a4926d5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-bg-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-bg-1.4.1.tar.bz2</a></td>
<td><tt>445f35bf43b60c7799df116bd90957ad</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-ca-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.4.1.tar.bz2</a></td>
<td><tt>f011aa527e4b476f18f1fda9a043f81b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-cs-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.4.1.tar.bz2</a></td>
<td><tt>8b56e381765bece8a32fec3b67e881c2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-cy-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.4.1.tar.bz2</a></td>
<td><tt>e15377d70faef67a91a361b421b8be84</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-da-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-da-1.4.1.tar.bz2</a></td>
<td><tt>3bcda6ccf32a2b0916f5de47981be655</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-de-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-de-1.4.1.tar.bz2</a></td>
<td><tt>b54a04db280a5b00f0105407c24ce49c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-el-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-el-1.4.1.tar.bz2</a></td>
<td><tt>a744de5d6e97a25257a809f7a0f79a11</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-en_GB-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.4.1.tar.bz2</a></td>
<td><tt>deaaf836cce7efcd9c83d800a6b4e51b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-es-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-es-1.4.1.tar.bz2</a></td>
<td><tt>3872dfdfb6b12532218daf8f61f94282</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-et-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-et-1.4.1.tar.bz2</a></td>
<td><tt>0ecd275357b76d245b2367a1925bda59</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-fi-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.4.1.tar.bz2</a></td>
<td><tt>a2e26094907dc77365266c215183c587</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-fr-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.4.1.tar.bz2</a></td>
<td><tt>37a18640975a8a1ba38044a6ea7dbd37</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-hu-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.4.1.tar.bz2</a></td>
<td><tt>95e046ab8097fda8b4f146b4a625b7a3</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-it-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-it-1.4.1.tar.bz2</a></td>
<td><tt>cac43b60ea3d01cfa0ac337bc0a296be</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-nb-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.4.1.tar.bz2</a></td>
<td><tt>0d9c12a3881861377130801a3a431dd2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-nl-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.4.1.tar.bz2</a></td>
<td><tt>a960e30b5bd883ed71ada339f238bb38</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-nn-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-nn-1.4.1.tar.bz2</a></td>
<td><tt>7e55ada0f26bc0125ae26ab7c7b1eae2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-pl-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.4.1.tar.bz2</a></td>
<td><tt>c6c38ec4a42d2c2abd289b83e2398c21</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-pt-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.4.1.tar.bz2</a></td>
<td><tt>af2c79e0694d913a749a9591598641c5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-pt_BR-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.4.1.tar.bz2</a></td>
<td><tt>96f2a0ba7a249078e64ea319b8f27dc9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-ru-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.4.1.tar.bz2</a></td>
<td><tt>d198b6cc3574ea9305701a48324085bb</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-sl-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.4.1.tar.bz2</a></td>
<td><tt>3c27784f5630ca6f3b0cfbae89271176</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-sr-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.4.1.tar.bz2</a></td>
<td><tt>f49d2141aa8bd2c68f0ab892cdc4e1a8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-sr@Latn-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.4.1.tar.bz2</a></td>
<td><tt>41fecc81a0bfbce8eaf5f40e978be3fe</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-sv-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.4.1.tar.bz2</a></td>
<td><tt>58ffb4991e48caa73f434f30ca2b4761</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-ta-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-ta-1.4.1.tar.bz2</a></td>
<td><tt>43e954db7f2af6f4c4f34a85a31e33d2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-tg-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-tg-1.4.1.tar.bz2</a></td>
<td><tt>2e35a578c8afb853ef5c23e71c2d575e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-l10n/koffice-l10n-zh_CN-1.4.1.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.4.1.tar.bz2</a></td>
<td><tt>02491c50d888600dccd1685a9ef7ed6c</tt></td></tr>
<tr><td>General *</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.1/src/koffice-1.4.0a-1.4.1.tar.xdelta">
koffice-1.4.0a-1.4.1.tar.xdelta</a></td>
<td><tt>6f7fb7626bbd6cf2c7bcd5246a937319</tt></td></tr>
</table>
<p>*: XDelta patches</p>
