<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-1.6.0.tar.bz2">
koffice-1.6.0.tar.bz2</a></td>
<td><tt>e669cf19b2e1c7db7029c0772c527c0d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/keximdb-1.1.0.tar.gz">
keximdb-1.1.0.tar.gz</a></td>
<td><tt>0e960fe9344d5be1232c12fb984e60a9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-ca-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.6.0.tar.bz2</a></td>
<td><tt>b90e14bd3508bcc030096496ea87683a</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-cs-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.6.0.tar.bz2</a></td>
<td><tt>21f9a7c3daf57aabf70111dded8a26a6</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-cy-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.6.0.tar.bz2</a></td>
<td><tt>b1d03624474b91becd3ff64647f45087</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-da-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-da-1.6.0.tar.bz2</a></td>
<td><tt>d1532dc1107f01752a9eeeb362666289</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-de-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-de-1.6.0.tar.bz2</a></td>
<td><tt>21344257dcd9b418898fb5e348918171</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-el-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-el-1.6.0.tar.bz2</a></td>
<td><tt>c00bbbf55de2d5d8aa68916ef6618ee3</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-en_GB-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.6.0.tar.bz2</a></td>
<td><tt>eb4582f359eaada24a1dd96443636219</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-es-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-es-1.6.0.tar.bz2</a></td>
<td><tt>81db059841e59cfee6371d10b12e82d7</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-et-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-et-1.6.0.tar.bz2</a></td>
<td><tt>64b4dd81d61362599af0882d695dd175</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-eu-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-eu-1.6.0.tar.bz2</a></td>
<td><tt>c3c5dbfe0135896c41f749ff79c6744e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-fi-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.6.0.tar.bz2</a></td>
<td><tt>738bf409e16c08018b75f672abcb94a4</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-fr-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.6.0.tar.bz2</a></td>
<td><tt>96a5871374f69c694be87e621f04f39e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-hu-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.6.0.tar.bz2</a></td>
<td><tt>01ea831cfbd136fecb1c7de8826e97b9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-it-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-it-1.6.0.tar.bz2</a></td>
<td><tt>73f17287697e54e61237a8cf7f6fc75f</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-ja-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-ja-1.6.0.tar.bz2</a></td>
<td><tt>dd3f979c03f9bc4ae6393a54766b4a84</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-lv-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-lv-1.6.0.tar.bz2</a></td>
<td><tt>af51669631e18feef464e8d6778a41ad</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-ms-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-ms-1.6.0.tar.bz2</a></td>
<td><tt>259be59d9bfe0e7fba7d96c1b5740614</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-nb-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.6.0.tar.bz2</a></td>
<td><tt>ef631712fe58e8129823b0f53253e153</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-nl-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.6.0.tar.bz2</a></td>
<td><tt>b9c572b04701226fdce5e9ae5817177c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-pl-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.6.0.tar.bz2</a></td>
<td><tt>aaa167a7881f383b88696d34fd1903a5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-pt-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.6.0.tar.bz2</a></td>
<td><tt>c907923d13d2e2d15e09ac5be9259c96</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-pt_BR-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.6.0.tar.bz2</a></td>
<td><tt>8d1be2180acdba3287c2936cc379b4c6</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-ru-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.6.0.tar.bz2</a></td>
<td><tt>0b895c8a86f0b3c6f31903c906e0dd08</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-sk-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-sk-1.6.0.tar.bz2</a></td>
<td><tt>3bdbfb8532c3a3422345ff8693544b29</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-sl-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.6.0.tar.bz2</a></td>
<td><tt>6dfa4b30a8d246a46dddef1e3933cf36</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-sr-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.6.0.tar.bz2</a></td>
<td><tt>69681fe0a95a61b88aa5b9ee226fc320</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-sr@Latn-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.6.0.tar.bz2</a></td>
<td><tt>8ce2f6edd23a43b079fbec9c20cfe516</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-sv-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.6.0.tar.bz2</a></td>
<td><tt>774efb0a9c02776c58ca6cfe1930d327</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-tr-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-tr-1.6.0.tar.bz2</a></td>
<td><tt>d941eddab83cc8991d4f218854d25f64</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-uk-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-uk-1.6.0.tar.bz2</a></td>
<td><tt>b29bea37e37917edb45cfde8c48b50f7</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-zh_CN-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.6.0.tar.bz2</a></td>
<td><tt>a3fda356e170368d7fd88d0ce892307b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.0/src/koffice-l10n/koffice-l10n-zh_TW-1.6.0.tar.bz2">
koffice-l10n/koffice-l10n-zh_TW-1.6.0.tar.bz2</a></td>
<td><tt>17ec8363abee3dd45c1a4c103b023ff3</tt></td></tr>
</table>
<p>*: XDelta patches</p>
