<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General *</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-1.3.2-1.3.3.tar.xdelta">
koffice-1.3.2-1.3.3.tar.xdelta</a></td>
<td><tt>42e99220e9443c52395341038e27f60d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-1.3.3.tar.bz2">
koffice-1.3.3.tar.bz2</a></td>
<td><tt>2c3b745c6218a9dc9b3f60edea2dca2b</tt></td></tr>
<tr><td>All languages *</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-1.3.2-1.3.3.tar.xdelta">
koffice-i18n-1.3.2-1.3.3.tar.xdelta</a></td>
<td><tt>ea9117a6879ac3582c4125bbc76973c5</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-1.3.3.tar.bz2">
koffice-i18n-1.3.3.tar.bz2</a></td>
<td><tt>d1d99fbdd9ceb527a40f235fe6f0255a</tt></td></tr>
<tr><td>Afrikaans</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-af-1.3.3.tar.bz2">
koffice-i18n-af-1.3.3.tar.bz2</a></td>
<td><tt>1a24edec9f43a17d67229057a9c838b5</tt></td></tr>
<tr><td>Bulgarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-bg-1.3.3.tar.bz2">
koffice-i18n-bg-1.3.3.tar.bz2</a></td>
<td><tt>881e0bdc90e9ceb0ec389b62ecdc628a</tt></td></tr>
<tr><td>Catalan</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ca-1.3.3.tar.bz2">
koffice-i18n-ca-1.3.3.tar.bz2</a></td>
<td><tt>40b03d50d630279c08f55ae89b81522f</tt></td></tr>
<tr><td>Czech</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-cs-1.3.3.tar.bz2">
koffice-i18n-cs-1.3.3.tar.bz2</a></td>
<td><tt>01f3fddd88a367f2b552131848a79cfc</tt></td></tr>
<tr><td>Welsh</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-cy-1.3.3.tar.bz2">
koffice-i18n-cy-1.3.3.tar.bz2</a></td>
<td><tt>bd180d1e4f8d20476de5c81c2e1dd51b</tt></td></tr>
<tr><td>Danish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-da-1.3.3.tar.bz2">
koffice-i18n-da-1.3.3.tar.bz2</a></td>
<td><tt>fe2afbbde06672e2ac48e1e2e7dc46a5</tt></td></tr>
<tr><td>German</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-de-1.3.3.tar.bz2">
koffice-i18n-de-1.3.3.tar.bz2</a></td>
<td><tt>c7171fbc73f445c3807ecb31adf8eb58</tt></td></tr>
<tr><td>Greek</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-el-1.3.3.tar.bz2">
koffice-i18n-el-1.3.3.tar.bz2</a></td>
<td><tt>237df918d9c4a18185cd5f5289fcd353</tt></td></tr>
<tr><td>British English</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-en_GB-1.3.3.tar.bz2">
koffice-i18n-en_GB-1.3.3.tar.bz2</a></td>
<td><tt>d281ecc02a0d92cbd5dd01e940f7afcd</tt></td></tr>
<tr><td>Esperanto</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-eo-1.3.3.tar.bz2">
koffice-i18n-eo-1.3.3.tar.bz2</a></td>
<td><tt>084f8da03ed008de03d79e09ac8f93b9</tt></td></tr>
<tr><td>Spanish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-es-1.3.3.tar.bz2">
koffice-i18n-es-1.3.3.tar.bz2</a></td>
<td><tt>dbbb10da7360f109ac2199f00442d9c1</tt></td></tr>
<tr><td>Estonian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-et-1.3.3.tar.bz2">
koffice-i18n-et-1.3.3.tar.bz2</a></td>
<td><tt>670c1e5b41ea0f359b83f7aa8a186f88</tt></td></tr>
<tr><td>Farsi</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-fa-1.3.3.tar.bz2">
koffice-i18n-fa-1.3.3.tar.bz2</a></td>
<td><tt>89db2e736e56aadef1b1072872d9f668</tt></td></tr>
<tr><td>Finnish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-fi-1.3.3.tar.bz2">
koffice-i18n-fi-1.3.3.tar.bz2</a></td>
<td><tt>487b1567174d24cc36d1f6ceb5862b18</tt></td></tr>
<tr><td>French</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-fr-1.3.3.tar.bz2">
koffice-i18n-fr-1.3.3.tar.bz2</a></td>
<td><tt>dcd487ec0943cc0757d5a2ec3ffe0e41</tt></td></tr>
<tr><td>Hebrew</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-he-1.3.3.tar.bz2">
koffice-i18n-he-1.3.3.tar.bz2</a></td>
<td><tt>fc52b4d1a9a11fd2d6a4b34c0c3accc2</tt></td></tr>
<tr><td>Upper Sorbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-hsb-1.3.3.tar.bz2">
koffice-i18n-hsb-1.3.3.tar.bz2</a></td>
<td><tt>e1f19311f4e22856564148b85bc5d20f</tt></td></tr>
<tr><td>Hungarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-hu-1.3.3.tar.bz2">
koffice-i18n-hu-1.3.3.tar.bz2</a></td>
<td><tt>433056e4e15d61704d25a0c0fd4ee454</tt></td></tr>
<tr><td>Italian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-it-1.3.3.tar.bz2">
koffice-i18n-it-1.3.3.tar.bz2</a></td>
<td><tt>6d3a1c49c7ca0c46e5cb3e6383ee4947</tt></td></tr>
<tr><td>Japanese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ja-1.3.3.tar.bz2">
koffice-i18n-ja-1.3.3.tar.bz2</a></td>
<td><tt>d85746cfdfc919eebcf3ef012baad2b6</tt></td></tr>
<tr><td>Lao</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-lo-1.3.3.tar.bz2">
koffice-i18n-lo-1.3.3.tar.bz2</a></td>
<td><tt>e1fe2adef429c91627e6b2083038eb99</tt></td></tr>
<tr><td>Maltese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-mt-1.3.3.tar.bz2">
koffice-i18n-mt-1.3.3.tar.bz2</a></td>
<td><tt>a29504c9fb21a03e1b84b7750ee2112a</tt></td></tr>
<tr><td>Norwegian Bokm&aring;l</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-nb-1.3.3.tar.bz2">
koffice-i18n-nb-1.3.3.tar.bz2</a></td>
<td><tt>f94f8ce543258aa5882c92ad165e75a1</tt></td></tr>
<tr><td>Dutch</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-nl-1.3.3.tar.bz2">
koffice-i18n-nl-1.3.3.tar.bz2</a></td>
<td><tt>d5964fb163f4006ca4a6cadc6bd03a1d</tt></td></tr>
<tr><td>Norwegian Nynorsk</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-nn-1.3.3.tar.bz2">
koffice-i18n-nn-1.3.3.tar.bz2</a></td>
<td><tt>d7f0c8e80461597bc2e193fca5a182c1</tt></td></tr>
<tr><td>Polish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-pl-1.3.3.tar.bz2">
koffice-i18n-pl-1.3.3.tar.bz2</a></td>
<td><tt>5e49311a806307c4148c5fe22be4ef1b</tt></td></tr>
<tr><td>Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-pt-1.3.3.tar.bz2">
koffice-i18n-pt-1.3.3.tar.bz2</a></td>
<td><tt>548731d49402079ffde38837deebd9c3</tt></td></tr>
<tr><td>Brazilian Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-pt_BR-1.3.3.tar.bz2">
koffice-i18n-pt_BR-1.3.3.tar.bz2</a></td>
<td><tt>576112a88c7d82574a41114c201a07f0</tt></td></tr>
<tr><td>Russian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ru-1.3.3.tar.bz2">
koffice-i18n-ru-1.3.3.tar.bz2</a></td>
<td><tt>b9f5db0dd5ca679a8de43c9b98374801</tt></td></tr>
<tr><td>Northern Sami</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-se-1.3.3.tar.bz2">
koffice-i18n-se-1.3.3.tar.bz2</a></td>
<td><tt>aedf4d28a88dfea47765614cd75afac2</tt></td></tr>
<tr><td>Slovak</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sk-1.3.3.tar.bz2">
koffice-i18n-sk-1.3.3.tar.bz2</a></td>
<td><tt>6ae257bbcfbaef0b39df82e3916452b0</tt></td></tr>
<tr><td>Slovenian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sl-1.3.3.tar.bz2">
koffice-i18n-sl-1.3.3.tar.bz2</a></td>
<td><tt>c21c80d641affb37fa86e5979ce93729</tt></td></tr>
<tr><td>Serbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sr-1.3.3.tar.bz2">
koffice-i18n-sr-1.3.3.tar.bz2</a></td>
<td><tt>fb79ec44c7aa7b6166ad292869ba436b</tt></td></tr>
<tr><td>Swedish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-sv-1.3.3.tar.bz2">
koffice-i18n-sv-1.3.3.tar.bz2</a></td>
<td><tt>1f778fff63e61569dfa7f336b9058c98</tt></td></tr>
<tr><td>Tajik</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-tg-1.3.3.tar.bz2">
koffice-i18n-tg-1.3.3.tar.bz2</a></td>
<td><tt>6a8b4248bc50cf2937e7f5af7e43ca5f</tt></td></tr>
<tr><td>Thai</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-th-1.3.3.tar.bz2">
koffice-i18n-th-1.3.3.tar.bz2</a></td>
<td><tt>41195264d9e06b1ffd62061cf5e0eba0</tt></td></tr>
<tr><td>Turkish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-tr-1.3.3.tar.bz2">
koffice-i18n-tr-1.3.3.tar.bz2</a></td>
<td><tt>5efd98451bf756c132b7cd09a11a3221</tt></td></tr>
<tr><td>Venda</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-ven-1.3.3.tar.bz2">
koffice-i18n-ven-1.3.3.tar.bz2</a></td>
<td><tt>177748cf03c961307c9c734177e327fd</tt></td></tr>
<tr><td>Xhosa</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-xh-1.3.3.tar.bz2">
koffice-i18n-xh-1.3.3.tar.bz2</a></td>
<td><tt>60b64400bf0a6435da17983727bf4164</tt></td></tr>
<tr><td>Chinese Simplified</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-zh_CN-1.3.3.tar.bz2">
koffice-i18n-zh_CN-1.3.3.tar.bz2</a></td>
<td><tt>41523d6458fa1c1671ec97f8dfb95fbb</tt></td></tr>
<tr><td>Chinese Traditional</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-zh_TW-1.3.3.tar.bz2">
koffice-i18n-zh_TW-1.3.3.tar.bz2</a></td>
<td><tt>58d218d4d00716bc67c4be7c576214b6</tt></td></tr>
<tr><td>Zulu</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.3/src/koffice-i18n-zu-1.3.3.tar.bz2">
koffice-i18n-zu-1.3.3.tar.bz2</a></td>
<td><tt>c67d5a2379d612660deeb4eef29b2a92</tt></td></tr>
</table>
<p>*: XDelta patches</p>
