<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-1.3.1.tar.bz2">
koffice-1.3.1.tar.bz2</a></td>
<td><tt>ad68bab5753cf8d2e32a1d9e0c19495a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-1.3.1.tar.bz2">
koffice-i18n-1.3.1.tar.bz2</a></td>
<td><tt>2eaa60eecb8a50c37f1af64d82378050</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-af-1.3.1.tar.bz2">
koffice-i18n-af-1.3.1.tar.bz2</a></td>
<td><tt>8d196e6f28848056b841034abf2279e6</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-bg-1.3.1.tar.bz2">
koffice-i18n-bg-1.3.1.tar.bz2</a></td>
<td><tt>2992a66afb37de410a3c93fbaa0bca29</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-ca-1.3.1.tar.bz2">
koffice-i18n-ca-1.3.1.tar.bz2</a></td>
<td><tt>5dc8a8cdd652329d163a70d74966160b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-cs-1.3.1.tar.bz2">
koffice-i18n-cs-1.3.1.tar.bz2</a></td>
<td><tt>fe024c600abae8f9ae48e259308b6540</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-da-1.3.1.tar.bz2">
koffice-i18n-da-1.3.1.tar.bz2</a></td>
<td><tt>3e359910a220951856898b601e257bb9</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-de-1.3.1.tar.bz2">
koffice-i18n-de-1.3.1.tar.bz2</a></td>
<td><tt>0be0fbdd4e7cee5072bb17d274e0f458</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-el-1.3.1.tar.bz2">
koffice-i18n-el-1.3.1.tar.bz2</a></td>
<td><tt>d711ece1a2054953df5b7e3801417164</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-en_GB-1.3.1.tar.bz2">
koffice-i18n-en_GB-1.3.1.tar.bz2</a></td>
<td><tt>44664577d5aafcbf5de1269e8dbbd1c1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-eo-1.3.1.tar.bz2">
koffice-i18n-eo-1.3.1.tar.bz2</a></td>
<td><tt>b8698b36a14c2590fcd6df0e40953afd</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-es-1.3.1.tar.bz2">
koffice-i18n-es-1.3.1.tar.bz2</a></td>
<td><tt>72e11f45bd6ca89f95bd0cbb1d318439</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-et-1.3.1.tar.bz2">
koffice-i18n-et-1.3.1.tar.bz2</a></td>
<td><tt>20e5a6469ace6c1c23c47348eb2e2b66</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-fa-1.3.1.tar.bz2">
koffice-i18n-fa-1.3.1.tar.bz2</a></td>
<td><tt>80abe4e46d99328347c4cd233602687b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-fi-1.3.1.tar.bz2">
koffice-i18n-fi-1.3.1.tar.bz2</a></td>
<td><tt>cb671ffc0674dc1479ac3b25e88bd8a8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-fr-1.3.1.tar.bz2">
koffice-i18n-fr-1.3.1.tar.bz2</a></td>
<td><tt>9ff4722b8afc7f0134c236981e764b0e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-he-1.3.1.tar.bz2">
koffice-i18n-he-1.3.1.tar.bz2</a></td>
<td><tt>76d63c32e718f7f350e0c5c6b012b959</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-hu-1.3.1.tar.bz2">
koffice-i18n-hu-1.3.1.tar.bz2</a></td>
<td><tt>3c3d4b06ba4d4571136520351325b13e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-it-1.3.1.tar.bz2">
koffice-i18n-it-1.3.1.tar.bz2</a></td>
<td><tt>3514c1d59e270c9dddd9c704f1445232</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-ja-1.3.1.tar.bz2">
koffice-i18n-ja-1.3.1.tar.bz2</a></td>
<td><tt>2a2a6ee77dc5627eb0e1678d83236ead</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-lo-1.3.1.tar.bz2">
koffice-i18n-lo-1.3.1.tar.bz2</a></td>
<td><tt>09f880989792d1cb1860082681c451dd</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-mt-1.3.1.tar.bz2">
koffice-i18n-mt-1.3.1.tar.bz2</a></td>
<td><tt>64c6905b0ad55b9e10f5466904c06d7f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-nb-1.3.1.tar.bz2">
koffice-i18n-nb-1.3.1.tar.bz2</a></td>
<td><tt>c1b79c32aca4cfa1ac9c85132857d765</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-nl-1.3.1.tar.bz2">
koffice-i18n-nl-1.3.1.tar.bz2</a></td>
<td><tt>a839d0ee9525ce73cf4b5c40a3837e83</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-nn-1.3.1.tar.bz2">
koffice-i18n-nn-1.3.1.tar.bz2</a></td>
<td><tt>ff689745fc36da3c938ca5b16a0bce2e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-pl-1.3.1.tar.bz2">
koffice-i18n-pl-1.3.1.tar.bz2</a></td>
<td><tt>a6e5621097a2a4c6f70ad7cb8b084fe6</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-pt-1.3.1.tar.bz2">
koffice-i18n-pt-1.3.1.tar.bz2</a></td>
<td><tt>962710bce673bd0ca4cfd62698a7a4b5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-pt_BR-1.3.1.tar.bz2">
koffice-i18n-pt_BR-1.3.1.tar.bz2</a></td>
<td><tt>46d558f3e0aa98cafbf67e0d953369eb</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-ru-1.3.1.tar.bz2">
koffice-i18n-ru-1.3.1.tar.bz2</a></td>
<td><tt>59c65893dbbcd5ee84f157ed611e3660</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-se-1.3.1.tar.bz2">
koffice-i18n-se-1.3.1.tar.bz2</a></td>
<td><tt>1c16b403348ed6f3103b75b7ff233d1a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-sk-1.3.1.tar.bz2">
koffice-i18n-sk-1.3.1.tar.bz2</a></td>
<td><tt>42a4088a49de57cfb0fe89add2a9e258</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-sl-1.3.1.tar.bz2">
koffice-i18n-sl-1.3.1.tar.bz2</a></td>
<td><tt>aafbe07c4875138d4cac8bdcac6dee7e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-sr-1.3.1.tar.bz2">
koffice-i18n-sr-1.3.1.tar.bz2</a></td>
<td><tt>b6825d1a16fed905c6cc673afe4b1344</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-sv-1.3.1.tar.bz2">
koffice-i18n-sv-1.3.1.tar.bz2</a></td>
<td><tt>b7c37a9bb03433b7f4e6a08d1e14a223</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-tg-1.3.1.tar.bz2">
koffice-i18n-tg-1.3.1.tar.bz2</a></td>
<td><tt>fcd7c642f2f85eeeafb4410114dbffbe</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-th-1.3.1.tar.bz2">
koffice-i18n-th-1.3.1.tar.bz2</a></td>
<td><tt>5eedaa567ce94d4ba27bc5c474d32aa4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-tr-1.3.1.tar.bz2">
koffice-i18n-tr-1.3.1.tar.bz2</a></td>
<td><tt>5e7f1ca88ec66b326d99c6e8a2744a4b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-ven-1.3.1.tar.bz2">
koffice-i18n-ven-1.3.1.tar.bz2</a></td>
<td><tt>2f8817326641fcef048e534c7ab3d1d8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-xh-1.3.1.tar.bz2">
koffice-i18n-xh-1.3.1.tar.bz2</a></td>
<td><tt>0339a791dc4270a0633a643b9c934638</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-zh_CN-1.3.1.tar.bz2">
koffice-i18n-zh_CN-1.3.1.tar.bz2</a></td>
<td><tt>cb769e23187ef1426727043fb3e487d7</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-zh_TW-1.3.1.tar.bz2">
koffice-i18n-zh_TW-1.3.1.tar.bz2</a></td>
<td><tt>ac6483e95d99085900902cb5d2fbc360</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/stable/koffice-1.3.1/src/koffice-i18n-zu-1.3.1.tar.bz2">
koffice-i18n-zu-1.3.1.tar.bz2</a></td>
<td><tt>20537d86ea5c8580aaa763a94d2970c2</tt></td></tr>
</table>
