<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General *</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-1.3.4-1.3.5.tar.xdelta">
koffice-1.3.4-1.3.5.tar.xdelta</a></td>
<td><tt>18f35fd33b62d4d0549130eceb6fca38</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-1.3.5.tar.bz2">
koffice-1.3.5.tar.bz2</a></td>
<td><tt>dbc7e76c86647709a3e74f57c0fcf7f5</tt></td></tr>
<tr><td>All languages *</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-1.3.4-1.3.5.tar.xdelta">
koffice-i18n-1.3.4-1.3.5.tar.xdelta</a></td>
<td><tt>b5cd083dee6bddf5953b48c949b5ed25</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-1.3.5.tar.bz2">
koffice-i18n-1.3.5.tar.bz2</a></td>
<td><tt>7a4af78be2a9e09a148717079f44a7a7</tt></td></tr>
<tr><td>Afrikaans</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-af-1.3.5.tar.bz2">
koffice-i18n-af-1.3.5.tar.bz2</a></td>
<td><tt>8386eab59a080e0f8ea1c2a6b30f5d1e</tt></td></tr>
<tr><td>Bulgarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-bg-1.3.5.tar.bz2">
koffice-i18n-bg-1.3.5.tar.bz2</a></td>
<td><tt>f339b53c687f33424e6eb08912b28a19</tt></td></tr>
<tr><td>Breton</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-br-1.3.5.tar.bz2">
koffice-i18n-br-1.3.5.tar.bz2</a></td>
<td><tt>8b1763f2baeec706c6532fc3dc17bdb7</tt></td></tr>
<tr><td>Catalan</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-ca-1.3.5.tar.bz2">
koffice-i18n-ca-1.3.5.tar.bz2</a></td>
<td><tt>e12fcb017726162d68d759492a464230</tt></td></tr>
<tr><td>Czech</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-cs-1.3.5.tar.bz2">
koffice-i18n-cs-1.3.5.tar.bz2</a></td>
<td><tt>817d6d138b0eb706b56983789ff903d9</tt></td></tr>
<tr><td>Welsh</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-cy-1.3.5.tar.bz2">
koffice-i18n-cy-1.3.5.tar.bz2</a></td>
<td><tt>19ee15a9e6f6a444e9c3bf50413697de</tt></td></tr>
<tr><td>Danish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-da-1.3.5.tar.bz2">
koffice-i18n-da-1.3.5.tar.bz2</a></td>
<td><tt>b713265b9e975de3e1c0f3f23624c37d</tt></td></tr>
<tr><td>German</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-de-1.3.5.tar.bz2">
koffice-i18n-de-1.3.5.tar.bz2</a></td>
<td><tt>7ff3c969a75a577f5d1d10f14f5486b4</tt></td></tr>
<tr><td>Greek</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-el-1.3.5.tar.bz2">
koffice-i18n-el-1.3.5.tar.bz2</a></td>
<td><tt>ea98b433c9f1260f252b7907213dfff7</tt></td></tr>
<tr><td>British English</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-en_GB-1.3.5.tar.bz2">
koffice-i18n-en_GB-1.3.5.tar.bz2</a></td>
<td><tt>c085044e6af71010b41e1db9acd3c97b</tt></td></tr>
<tr><td>Esperanto</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-eo-1.3.5.tar.bz2">
koffice-i18n-eo-1.3.5.tar.bz2</a></td>
<td><tt>7b6ec614d75532a2801f0135c91dda1c</tt></td></tr>
<tr><td>Spanish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-es-1.3.5.tar.bz2">
koffice-i18n-es-1.3.5.tar.bz2</a></td>
<td><tt>5eb96a2a4bfeb760ae9053bcbd4e1895</tt></td></tr>
<tr><td>Estonian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-et-1.3.5.tar.bz2">
koffice-i18n-et-1.3.5.tar.bz2</a></td>
<td><tt>f56878931e6630d9c9f3444fe5d7f92f</tt></td></tr>
<tr><td>Farsi</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-fa-1.3.5.tar.bz2">
koffice-i18n-fa-1.3.5.tar.bz2</a></td>
<td><tt>385bfe77bee40f92e963d1dc6b687d6c</tt></td></tr>
<tr><td>Finnish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-fi-1.3.5.tar.bz2">
koffice-i18n-fi-1.3.5.tar.bz2</a></td>
<td><tt>7be66b046c38d08f694ef57335428ef6</tt></td></tr>
<tr><td>French</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-fr-1.3.5.tar.bz2">
koffice-i18n-fr-1.3.5.tar.bz2</a></td>
<td><tt>b675b5f47aca0913076d5586d79f98a3</tt></td></tr>
<tr><td>Hebrew</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-he-1.3.5.tar.bz2">
koffice-i18n-he-1.3.5.tar.bz2</a></td>
<td><tt>40b78f7d40dead7dda9a05a48ca8f3c6</tt></td></tr>
<tr><td>Upper Sorbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-hsb-1.3.5.tar.bz2">
koffice-i18n-hsb-1.3.5.tar.bz2</a></td>
<td><tt>93f48f01d07dfa31119012885ae982a0</tt></td></tr>
<tr><td>Hungarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-hu-1.3.5.tar.bz2">
koffice-i18n-hu-1.3.5.tar.bz2</a></td>
<td><tt>5b8b8a4c32655f78f3e27be02e050c61</tt></td></tr>
<tr><td>Italian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-it-1.3.5.tar.bz2">
koffice-i18n-it-1.3.5.tar.bz2</a></td>
<td><tt>3a631c690abe074ca061bafa5a9cf154</tt></td></tr>
<tr><td>Japanese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-ja-1.3.5.tar.bz2">
koffice-i18n-ja-1.3.5.tar.bz2</a></td>
<td><tt>b1ca4ff0bc1e72ac8da97d7ea37ad401</tt></td></tr>
<tr><td>Lao</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-lo-1.3.5.tar.bz2">
koffice-i18n-lo-1.3.5.tar.bz2</a></td>
<td><tt>5a99d5b9fd7e9d67113e02549bd780fc</tt></td></tr>
<tr><td>Maltese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-mt-1.3.5.tar.bz2">
koffice-i18n-mt-1.3.5.tar.bz2</a></td>
<td><tt>d46319bc4e42902e318169c8e57def23</tt></td></tr>
<tr><td>Norwegian Bokm&aring;l</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-nb-1.3.5.tar.bz2">
koffice-i18n-nb-1.3.5.tar.bz2</a></td>
<td><tt>88bd3f8cd16267fb5bca4211afe8236e</tt></td></tr>
<tr><td>Dutch</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-nl-1.3.5.tar.bz2">
koffice-i18n-nl-1.3.5.tar.bz2</a></td>
<td><tt>c99b8c678766d342d97a58d147f4452a</tt></td></tr>
<tr><td>Norwegian Nynorsk</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-nn-1.3.5.tar.bz2">
koffice-i18n-nn-1.3.5.tar.bz2</a></td>
<td><tt>9a00f0d52f5d05a5d336751fbaa1438f</tt></td></tr>
<tr><td>Polish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-pl-1.3.5.tar.bz2">
koffice-i18n-pl-1.3.5.tar.bz2</a></td>
<td><tt>ff23b6cb20f842515a42e373b8ea3c51</tt></td></tr>
<tr><td>Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-pt-1.3.5.tar.bz2">
koffice-i18n-pt-1.3.5.tar.bz2</a></td>
<td><tt>3f80a26e4b9e0c399b70aaec2cff2d88</tt></td></tr>
<tr><td>Brazilian Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-pt_BR-1.3.5.tar.bz2">
koffice-i18n-pt_BR-1.3.5.tar.bz2</a></td>
<td><tt>6e119e87b78319dc144992572c937367</tt></td></tr>
<tr><td>Russian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-ru-1.3.5.tar.bz2">
koffice-i18n-ru-1.3.5.tar.bz2</a></td>
<td><tt>3e6af2701cf72348681f4149bf0525af</tt></td></tr>
<tr><td>Northern Sami</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-se-1.3.5.tar.bz2">
koffice-i18n-se-1.3.5.tar.bz2</a></td>
<td><tt>391ec8bba693fe35f2a40250fdc892d7</tt></td></tr>
<tr><td>Slovak</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-sk-1.3.5.tar.bz2">
koffice-i18n-sk-1.3.5.tar.bz2</a></td>
<td><tt>596ea89996e082d87e881ef54e736f57</tt></td></tr>
<tr><td>Slovenian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-sl-1.3.5.tar.bz2">
koffice-i18n-sl-1.3.5.tar.bz2</a></td>
<td><tt>a2a9c30b4fa822b86d3729463a300baa</tt></td></tr>
<tr><td>Serbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-sr-1.3.5.tar.bz2">
koffice-i18n-sr-1.3.5.tar.bz2</a></td>
<td><tt>001b7d906a5a4b21c34315bfa589ff16</tt></td></tr>
<tr><td>Swedish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-sv-1.3.5.tar.bz2">
koffice-i18n-sv-1.3.5.tar.bz2</a></td>
<td><tt>37cd83f1933ee497b782aa6d9ab56c1e</tt></td></tr>
<tr><td>Tajik</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-tg-1.3.5.tar.bz2">
koffice-i18n-tg-1.3.5.tar.bz2</a></td>
<td><tt>39e56d0189de20c87ac18f1c8ad925e0</tt></td></tr>
<tr><td>Thai</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-th-1.3.5.tar.bz2">
koffice-i18n-th-1.3.5.tar.bz2</a></td>
<td><tt>b9099dceed971ebafaa540f0a6e8f302</tt></td></tr>
<tr><td>Turkish</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-tr-1.3.5.tar.bz2">
koffice-i18n-tr-1.3.5.tar.bz2</a></td>
<td><tt>164ff3fbe1b6e1c0d81d1a24215320bf</tt></td></tr>
<tr><td>Venda</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-ven-1.3.5.tar.bz2">
koffice-i18n-ven-1.3.5.tar.bz2</a></td>
<td><tt>079df2be6221b0184a03dc8552d254b8</tt></td></tr>
<tr><td>Xhosa</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-xh-1.3.5.tar.bz2">
koffice-i18n-xh-1.3.5.tar.bz2</a></td>
<td><tt>4e2ab740a1e0ae2ce2ea5df7dc8858fa</tt></td></tr>
<tr><td>Chinese Simplified</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-zh_CN-1.3.5.tar.bz2">
koffice-i18n-zh_CN-1.3.5.tar.bz2</a></td>
<td><tt>9094bade95397b4c5768b347d2fff137</tt></td></tr>
<tr><td>Chinese Traditional</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-zh_TW-1.3.5.tar.bz2">
koffice-i18n-zh_TW-1.3.5.tar.bz2</a></td>
<td><tt>5bb197f88cefdbf59d3ec5ab0e8604bd</tt></td></tr>
<tr><td>Zulu</td>
<td><a href="http://download.kde.org/stable/koffice-1.3.5/src/koffice-i18n-zu-1.3.5.tar.bz2">
koffice-i18n-zu-1.3.5.tar.bz2</a></td>
<td><tt>a44be69800b770df11f2fe515a9418cb</tt></td></tr>
</table>
<p>*: XDelta patches</p>
