<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-1.5.0-rc1.tar.bz2">
koffice-1.5.0-rc1.tar.bz2</a></td>
<td><tt>e9346977d18c67185d5b50f49ee8225b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-af-1.5-rc1.tar.bz2">
koffice-l10n-af-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-ar-1.5-rc1.tar.bz2">
koffice-l10n-ar-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-bg-1.5-rc1.tar.bz2">
koffice-l10n-bg-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-bn-1.5-rc1.tar.bz2">
koffice-l10n-bn-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-br-1.5-rc1.tar.bz2">
koffice-l10n-br-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-bs-1.5-rc1.tar.bz2">
koffice-l10n-bs-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-ca-1.5-rc1.tar.bz2">
koffice-l10n-ca-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-cs-1.5-rc1.tar.bz2">
koffice-l10n-cs-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-cy-1.5-rc1.tar.bz2">
koffice-l10n-cy-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-da-1.5-rc1.tar.bz2">
koffice-l10n-da-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-de-1.5-rc1.tar.bz2">
koffice-l10n-de-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-el-1.5-rc1.tar.bz2">
koffice-l10n-el-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-en_GB-1.5-rc1.tar.bz2">
koffice-l10n-en_GB-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-eo-1.5-rc1.tar.bz2">
koffice-l10n-eo-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-es-1.5-rc1.tar.bz2">
koffice-l10n-es-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-et-1.5-rc1.tar.bz2">
koffice-l10n-et-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-eu-1.5-rc1.tar.bz2">
koffice-l10n-eu-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-fi-1.5-rc1.tar.bz2">
koffice-l10n-fi-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-fr-1.5-rc1.tar.bz2">
koffice-l10n-fr-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-fy-1.5-rc1.tar.bz2">
koffice-l10n-fy-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-ga-1.5-rc1.tar.bz2">
koffice-l10n-ga-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-he-1.5-rc1.tar.bz2">
koffice-l10n-he-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-hi-1.5-rc1.tar.bz2">
koffice-l10n-hi-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-hsb-1.5-rc1.tar.bz2">
koffice-l10n-hsb-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-hu-1.5-rc1.tar.bz2">
koffice-l10n-hu-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-is-1.5-rc1.tar.bz2">
koffice-l10n-is-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-it-1.5-rc1.tar.bz2">
koffice-l10n-it-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-ja-1.5-rc1.tar.bz2">
koffice-l10n-ja-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-lt-1.5-rc1.tar.bz2">
koffice-l10n-lt-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-mk-1.5-rc1.tar.bz2">
koffice-l10n-mk-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-nb-1.5-rc1.tar.bz2">
koffice-l10n-nb-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-nds-1.5-rc1.tar.bz2">
koffice-l10n-nds-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-nl-1.5-rc1.tar.bz2">
koffice-l10n-nl-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-nn-1.5-rc1.tar.bz2">
koffice-l10n-nn-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-pa-1.5-rc1.tar.bz2">
koffice-l10n-pa-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-pl-1.5-rc1.tar.bz2">
koffice-l10n-pl-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-pt-1.5-rc1.tar.bz2">
koffice-l10n-pt-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-pt_BR-1.5-rc1.tar.bz2">
koffice-l10n-pt_BR-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-ro-1.5-rc1.tar.bz2">
koffice-l10n-ro-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-ru-1.5-rc1.tar.bz2">
koffice-l10n-ru-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-se-1.5-rc1.tar.bz2">
koffice-l10n-se-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-sk-1.5-rc1.tar.bz2">
koffice-l10n-sk-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-sl-1.5-rc1.tar.bz2">
koffice-l10n-sl-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-sr-1.5-rc1.tar.bz2">
koffice-l10n-sr-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-sr@Latn-1.5-rc1.tar.bz2">
koffice-l10n-sr@Latn-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-sv-1.5-rc1.tar.bz2">
koffice-l10n-sv-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-ta-1.5-rc1.tar.bz2">
koffice-l10n-ta-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-tg-1.5-rc1.tar.bz2">
koffice-l10n-tg-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-tr-1.5-rc1.tar.bz2">
koffice-l10n-tr-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-uk-1.5-rc1.tar.bz2">
koffice-l10n-uk-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n-zh_CN-1.5-rc1.tar.bz2">
koffice-l10n-zh_CN-1.5-rc1.tar.bz2</a></td>
<td><tt>xx</tt></td></tr>
</table>
<p>*: XDelta patches</p>
