<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-1.4.2.tar.bz2">
koffice-1.4.2.tar.bz2</a></td>
<td><tt>6b456fb7d54c84b11396b27a96ae0cf8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-bg-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-bg-1.4.2.tar.bz2</a></td>
<td><tt>ad980947860046ca4d5e0c8b23b7d3ab</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-ca-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.4.2.tar.bz2</a></td>
<td><tt>8a546eec2897af073bb564edf7150b6d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-cs-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.4.2.tar.bz2</a></td>
<td><tt>58e6c355e478ab459e6f0a5c86662f36</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-cy-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.4.2.tar.bz2</a></td>
<td><tt>ed0c069797a89680d49bd396f80e94e1</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-da-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-da-1.4.2.tar.bz2</a></td>
<td><tt>f6c3b0afcb299519f0663aa5a3ff3362</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-de-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-de-1.4.2.tar.bz2</a></td>
<td><tt>2659e56e079bfdd133833a39497f80e6</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-el-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-el-1.4.2.tar.bz2</a></td>
<td><tt>1aa341393b7ade4037ddeed77c73cacf</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-en_GB-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.4.2.tar.bz2</a></td>
<td><tt>caf59bd82ac94ccbeaa4b907c218defa</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-es-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-es-1.4.2.tar.bz2</a></td>
<td><tt>0f429120c8b27d1208f020a353aeb88d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-et-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-et-1.4.2.tar.bz2</a></td>
<td><tt>1ac8201573602a69e7d00b3332cb3bec</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-eu-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-eu-1.4.2.tar.bz2</a></td>
<td><tt>f8417721a49dd23f20115e102b0a8204</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-fi-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.4.2.tar.bz2</a></td>
<td><tt>b4925a3bd6db8b6b787b0313e3695371</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-fr-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.4.2.tar.bz2</a></td>
<td><tt>5f4e1d1f360a14e4ca2d24d2d85bf061</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-hu-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.4.2.tar.bz2</a></td>
<td><tt>ba83bf5a84f1ae5e7b22c1611c89e8bd</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-it-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-it-1.4.2.tar.bz2</a></td>
<td><tt>62609f289dc1ed216c7d075045159a04</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-nb-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.4.2.tar.bz2</a></td>
<td><tt>9d8c327b3e6567d90258cec8b0694a2c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-nl-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.4.2.tar.bz2</a></td>
<td><tt>6328a285565add97cd55413e52541050</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-nn-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-nn-1.4.2.tar.bz2</a></td>
<td><tt>2e52095b2c9c879e101d274888d49fcc</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-pl-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.4.2.tar.bz2</a></td>
<td><tt>78337154a7183cda46d34f80c6bf23e5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-pt-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.4.2.tar.bz2</a></td>
<td><tt>61e11d48f788275389f0b75e75b8de2b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-pt_BR-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.4.2.tar.bz2</a></td>
<td><tt>a559487f91f9bdf7eaf608f5d88c67c1</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-ru-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.4.2.tar.bz2</a></td>
<td><tt>a1527f53ed16ceed8c295614eedf7deb</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-sl-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.4.2.tar.bz2</a></td>
<td><tt>6d85c8b3f84b892471fd3cadd00aba37</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-sr-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.4.2.tar.bz2</a></td>
<td><tt>97d0fa5fdb458bbe5c8ef5317e15ed5c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-sr@Latn-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.4.2.tar.bz2</a></td>
<td><tt>65e7e7939b3d538913ddcec261741f75</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-sv-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.4.2.tar.bz2</a></td>
<td><tt>897218187ef83afcd99406b62e352e69</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-ta-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-ta-1.4.2.tar.bz2</a></td>
<td><tt>2c55f413ec8e02a667e37d967186dc86</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-tg-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-tg-1.4.2.tar.bz2</a></td>
<td><tt>c10cd70d7f1a9a397f768002625ad6f9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4.2/src/koffice-l10n/koffice-l10n-zh_CN-1.4.2.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.4.2.tar.bz2</a></td>
<td><tt>5733aa59661f8828c66ef0d2335d4242</tt></td></tr>
</table>
<p>*: XDelta patches</p>
