<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-1.2.95.tar.bz2">
koffice-1.2.95.tar.bz2</a></td>
<td><tt>a738120fed3f68316700f5f05317ac7a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-1.2.95.tar.bz2">
koffice-i18n-1.2.95.tar.bz2</a></td>
<td><tt>174d90ece76bacef1843a90ac8487e81</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-af-1.2.95.tar.bz2">
koffice-i18n-af-1.2.95.tar.bz2</a></td>
<td><tt>411603787d58b2df9de587c8db0c76a5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-bg-1.2.95.tar.bz2">
koffice-i18n-bg-1.2.95.tar.bz2</a></td>
<td><tt>0028e79be557e64b738e5a180e88e57f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-ca-1.2.95.tar.bz2">
koffice-i18n-ca-1.2.95.tar.bz2</a></td>
<td><tt>fa85202f114871ed9b4a297d2aa29f13</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-cs-1.2.95.tar.bz2">
koffice-i18n-cs-1.2.95.tar.bz2</a></td>
<td><tt>01ac8e3795ca0304d0f0b4777ab95213</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-da-1.2.95.tar.bz2">
koffice-i18n-da-1.2.95.tar.bz2</a></td>
<td><tt>6f64f0bbacab6fe1069df2c000f66699</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-de-1.2.95.tar.bz2">
koffice-i18n-de-1.2.95.tar.bz2</a></td>
<td><tt>08b736d1a284c9532f789df58ab3fd4a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-el-1.2.95.tar.bz2">
koffice-i18n-el-1.2.95.tar.bz2</a></td>
<td><tt>136106f38c5b038f43c312cd0d2bdb45</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-en_GB-1.2.95.tar.bz2">
koffice-i18n-en_GB-1.2.95.tar.bz2</a></td>
<td><tt>bc850a982b48ee3aa9f57610a7c4efd3</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-eo-1.2.95.tar.bz2">
koffice-i18n-eo-1.2.95.tar.bz2</a></td>
<td><tt>65b545dcf388e8d7dab06fc934f513c5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-es-1.2.95.tar.bz2">
koffice-i18n-es-1.2.95.tar.bz2</a></td>
<td><tt>5db47237e12766a199878c3d4ab22e3f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-et-1.2.95.tar.bz2">
koffice-i18n-et-1.2.95.tar.bz2</a></td>
<td><tt>532256724dac6ed01b10b957f59fa547</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-fa-1.2.95.tar.bz2">
koffice-i18n-fa-1.2.95.tar.bz2</a></td>
<td><tt>e18cc4100de4e6a2c0507a13a6c675a6</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-fi-1.2.95.tar.bz2">
koffice-i18n-fi-1.2.95.tar.bz2</a></td>
<td><tt>8ffb92171741f0734a890fbc86562944</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-fr-1.2.95.tar.bz2">
koffice-i18n-fr-1.2.95.tar.bz2</a></td>
<td><tt>3a578c329f555b0a48d8f97bf951110f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-he-1.2.95.tar.bz2">
koffice-i18n-he-1.2.95.tar.bz2</a></td>
<td><tt>1bd76e18bd06a76f03b03a5e92f7a00f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-hu-1.2.95.tar.bz2">
koffice-i18n-hu-1.2.95.tar.bz2</a></td>
<td><tt>c1ce7ce1179348e8d2a3111b6ad6dc8f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-it-1.2.95.tar.bz2">
koffice-i18n-it-1.2.95.tar.bz2</a></td>
<td><tt>90af360e8596569b87b5802d72082d1f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-ja-1.2.95.tar.bz2">
koffice-i18n-ja-1.2.95.tar.bz2</a></td>
<td><tt>09d9291fdf3b4c75080458e243897be2</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-lo-1.2.95.tar.bz2">
koffice-i18n-lo-1.2.95.tar.bz2</a></td>
<td><tt>50a487ed001b20d46857fa9e588583ca</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-mt-1.2.95.tar.bz2">
koffice-i18n-mt-1.2.95.tar.bz2</a></td>
<td><tt>b0306649e5151a11c63b3baa443f06cd</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-nb-1.2.95.tar.bz2">
koffice-i18n-nb-1.2.95.tar.bz2</a></td>
<td><tt>351b0db55213328585bb66fcf5a1ef10</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-nl-1.2.95.tar.bz2">
koffice-i18n-nl-1.2.95.tar.bz2</a></td>
<td><tt>77eb129cf1a64d4fd8bef9aead1bcbc1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-nn-1.2.95.tar.bz2">
koffice-i18n-nn-1.2.95.tar.bz2</a></td>
<td><tt>2b643cfc601419bb793257b2bb1d7f9b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-pl-1.2.95.tar.bz2">
koffice-i18n-pl-1.2.95.tar.bz2</a></td>
<td><tt>780ce7ec74472a671e8f86ace7f45035</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-pt-1.2.95.tar.bz2">
koffice-i18n-pt-1.2.95.tar.bz2</a></td>
<td><tt>d4cfa2f39916a321fb98e96526eb0478</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-pt_BR-1.2.95.tar.bz2">
koffice-i18n-pt_BR-1.2.95.tar.bz2</a></td>
<td><tt>61c5ff56d145fbbf4fc7ede783db8186</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-ru-1.2.95.tar.bz2">
koffice-i18n-ru-1.2.95.tar.bz2</a></td>
<td><tt>afc2b487ae84f6c8f19aa99b10f8c38c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-se-1.2.95.tar.bz2">
koffice-i18n-se-1.2.95.tar.bz2</a></td>
<td><tt>1a61ac336a7d94948957682b43b95955</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-sk-1.2.95.tar.bz2">
koffice-i18n-sk-1.2.95.tar.bz2</a></td>
<td><tt>6a1a1dac9b9e08d4a7b13d4ed2b7f879</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-sl-1.2.95.tar.bz2">
koffice-i18n-sl-1.2.95.tar.bz2</a></td>
<td><tt>0fbe52c5931ad1b348fbd2b0fcbd34a5</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-sr-1.2.95.tar.bz2">
koffice-i18n-sr-1.2.95.tar.bz2</a></td>
<td><tt>a878711318b888b98eb45cfdf11cd7e8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-sv-1.2.95.tar.bz2">
koffice-i18n-sv-1.2.95.tar.bz2</a></td>
<td><tt>46d0d6132775358a50d880acf3095bc2</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-th-1.2.95.tar.bz2">
koffice-i18n-th-1.2.95.tar.bz2</a></td>
<td><tt>552dde468999a20869e1581519a6fcf8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-tr-1.2.95.tar.bz2">
koffice-i18n-tr-1.2.95.tar.bz2</a></td>
<td><tt>8d8b959ac0dd8f014927ddb10271b6b2</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-ven-1.2.95.tar.bz2">
koffice-i18n-ven-1.2.95.tar.bz2</a></td>
<td><tt>4e702185314f10613fc33e9f88c5dff8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-xh-1.2.95.tar.bz2">
koffice-i18n-xh-1.2.95.tar.bz2</a></td>
<td><tt>fa9e1dd8556920c6b8cb75d614020d5e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-zh_CN-1.2.95.tar.bz2">
koffice-i18n-zh_CN-1.2.95.tar.bz2</a></td>
<td><tt>94131433f77710356c89eea3d542b362</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-zh_TW-1.2.95.tar.bz2">
koffice-i18n-zh_TW-1.2.95.tar.bz2</a></td>
<td><tt>e990ae9addb329a8b28cafa4e9ac7e07</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.95/src/koffice-i18n-zu-1.2.95.tar.bz2">
koffice-i18n-zu-1.2.95.tar.bz2</a></td>
<td><tt>a6dbc67a553a8522a5d4a48e9259d15f</tt></td></tr>
</table>
