<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-1.3.91.tar.bz2">
koffice-1.3.91.tar.bz2</a></td>
<td><tt>0fab58e267f8e261e86e1a52c58c2fb5</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n-1.3.91.tar.bz2">
koffice-i18n-1.3.91.tar.bz2</a></td>
<td><tt>c8926c234dcf8daeca43cb6e5e30ef1a</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-af-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-af-1.3.91.tar.bz2</a></td>
<td><tt>90e1b5e3804e84520f8fdf68a4189fad</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-bg-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-bg-1.3.91.tar.bz2</a></td>
<td><tt>494d8c8181356c94943ac0b1784a6c48</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-br-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-br-1.3.91.tar.bz2</a></td>
<td><tt>6ade492b82f6afba180124c3c7c55c11</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-ca-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-ca-1.3.91.tar.bz2</a></td>
<td><tt>7440e37a5be3e3c37a34e7fd08f6712d</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-cs-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-cs-1.3.91.tar.bz2</a></td>
<td><tt>55103e5f0ea023284c487bd55a964556</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-cy-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-cy-1.3.91.tar.bz2</a></td>
<td><tt>35bfd10cd4f1331b654e63205ac617bc</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-da-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-da-1.3.91.tar.bz2</a></td>
<td><tt>50cc255c59b811d6bcca56fc440cc309</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-de-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-de-1.3.91.tar.bz2</a></td>
<td><tt>c224e5125f5d86b9dbe4ef432ffcddb5</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-el-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-el-1.3.91.tar.bz2</a></td>
<td><tt>7caf7c32f257954e1213b4b241479e46</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-en_GB-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-en_GB-1.3.91.tar.bz2</a></td>
<td><tt>848bd5bb709e117df8849c2f768ce1ca</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-eo-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-eo-1.3.91.tar.bz2</a></td>
<td><tt>ff5e9b2045ba7a2361a1b8f4f8105e19</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-es-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-es-1.3.91.tar.bz2</a></td>
<td><tt>183dc31d666cf7245812279e70beaef8</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-et-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-et-1.3.91.tar.bz2</a></td>
<td><tt>3645f51958409340395dc3129151957f</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-fa-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-fa-1.3.91.tar.bz2</a></td>
<td><tt>be8b3b59ee6105252e528ddee51ab199</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-fi-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-fi-1.3.91.tar.bz2</a></td>
<td><tt>62fd5cbf5a54147ce9c185643503049c</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-fr-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-fr-1.3.91.tar.bz2</a></td>
<td><tt>4e4c7cd820d6b7ed22a3ced7ff80152c</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-ga-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-ga-1.3.91.tar.bz2</a></td>
<td><tt>6fa91a937799b65fec2b9a12919c488f</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-he-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-he-1.3.91.tar.bz2</a></td>
<td><tt>3834dfadf03310238331b970ef27cc3d</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-hu-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-hu-1.3.91.tar.bz2</a></td>
<td><tt>5707499a7713666ca5ce8563a2400051</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-it-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-it-1.3.91.tar.bz2</a></td>
<td><tt>6c7b6b187c5d22a485a7582111d61d45</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-ja-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-ja-1.3.91.tar.bz2</a></td>
<td><tt>e49d58b140a2bb9f8d82478f48973e29</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-lo-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-lo-1.3.91.tar.bz2</a></td>
<td><tt>4cbc45107b59f92a83b2cb0acdd3a31b</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-lv-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-lv-1.3.91.tar.bz2</a></td>
<td><tt>107a0554d7245bef316634e8eb97d5d1</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-mt-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-mt-1.3.91.tar.bz2</a></td>
<td><tt>dba81c750387a164416cb7910a5ee3b8</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-nb-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-nb-1.3.91.tar.bz2</a></td>
<td><tt>5693b0525649b70c39fafc741539f73e</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-nl-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-nl-1.3.91.tar.bz2</a></td>
<td><tt>98b92069d482c88fffd75e3445d31ac5</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-nn-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-nn-1.3.91.tar.bz2</a></td>
<td><tt>5b17c4758804e5a9a0052017cf4e8cd1</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-pl-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-pl-1.3.91.tar.bz2</a></td>
<td><tt>7ca5f17022744aaf1391f69433f04181</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-pt-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-pt-1.3.91.tar.bz2</a></td>
<td><tt>5c0787ee3fedc048c3e7041e15d9a0f9</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-pt_BR-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-pt_BR-1.3.91.tar.bz2</a></td>
<td><tt>de6860d773aa240cac114f3533dc5baf</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-ru-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-ru-1.3.91.tar.bz2</a></td>
<td><tt>cc4dc5f1a140ae0436ef4efcc843df4f</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-se-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-se-1.3.91.tar.bz2</a></td>
<td><tt>6e8c2ef73818dea40576bc27a76522e4</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-sk-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-sk-1.3.91.tar.bz2</a></td>
<td><tt>69823a2eac539b0b0adf5af3a8fd58a2</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-sl-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-sl-1.3.91.tar.bz2</a></td>
<td><tt>5d5a8a2a8e19a16ffd01b7b296b045c3</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-sr-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-sr-1.3.91.tar.bz2</a></td>
<td><tt>07f4600fa5cdf4953e6e3a6a85f8d049</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-sv-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-sv-1.3.91.tar.bz2</a></td>
<td><tt>f8abf496abe272f8d15cc39526e338a7</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-ta-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-ta-1.3.91.tar.bz2</a></td>
<td><tt>f804003ae3386ac4c0882dba7a473470</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-tg-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-tg-1.3.91.tar.bz2</a></td>
<td><tt>2fbed3c70d51b23b5748344d88cab221</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-th-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-th-1.3.91.tar.bz2</a></td>
<td><tt>5f23483b0fbd1923689e73007a1161a1</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-tr-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-tr-1.3.91.tar.bz2</a></td>
<td><tt>9a5f4614acf22aa7ebf22e61221a1c15</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-uk-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-uk-1.3.91.tar.bz2</a></td>
<td><tt>8f8607b16dc3269d8e4e3ddaa6dace88</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-ven-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-ven-1.3.91.tar.bz2</a></td>
<td><tt>746dd7e4d886847e874dee76b281ab42</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-xh-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-xh-1.3.91.tar.bz2</a></td>
<td><tt>f6dda2494daffc1ac65548fb7ff5ea91</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-zh_CN-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-zh_CN-1.3.91.tar.bz2</a></td>
<td><tt>50d1553b8f7d261c2d7f96fa9b846ca9</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-zh_TW-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-zh_TW-1.3.91.tar.bz2</a></td>
<td><tt>8944cdec557d8f0441062bd1d3a2416d</tt></td></tr>
<tr><td>All languages</td>
<td><a href="http://download.kde.org/unstable/koffice-1.4-beta1/src/koffice-i18n/koffice-i18n-zu-1.3.91.tar.bz2">
koffice-i18n/koffice-i18n-zu-1.3.91.tar.bz2</a></td>
<td><tt>f23c088a0ffa8460174448c38435ff2f</tt></td></tr>
</table>
<p>*: XDelta patches</p>
