<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-1.2.92.tar.bz2">
koffice-1.2.92.tar.bz2</a></td>
<td><tt>ec1c9297c877ab3adec76d492ee2621c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-1.2.92.tar.bz2">
koffice-i18n-1.2.92.tar.bz2</a></td>
<td><tt>87d73a50a3a4267590442c9348b4321f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-bg-1.2.92.tar.bz2">
koffice-i18n-bg-1.2.92.tar.bz2</a></td>
<td><tt>d814e33c7dcc655f6eeffcecb8ed04d6</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-ca-1.2.92.tar.bz2">
koffice-i18n-ca-1.2.92.tar.bz2</a></td>
<td><tt>f60ab63883d9c8a813fd8671f0bd78bc</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-cs-1.2.92.tar.bz2">
koffice-i18n-cs-1.2.92.tar.bz2</a></td>
<td><tt>27e285a3495ac90553dc321f8c376713</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-da-1.2.92.tar.bz2">
koffice-i18n-da-1.2.92.tar.bz2</a></td>
<td><tt>0055852214b42866c3d9fa025cd87be4</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-de-1.2.92.tar.bz2">
koffice-i18n-de-1.2.92.tar.bz2</a></td>
<td><tt>55a4880863158c4a6c2abce5f8cb4ed1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-el-1.2.92.tar.bz2">
koffice-i18n-el-1.2.92.tar.bz2</a></td>
<td><tt>12b31d06aa46693a8e6bcf5363a163fb</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-en_GB-1.2.92.tar.bz2">
koffice-i18n-en_GB-1.2.92.tar.bz2</a></td>
<td><tt>4d65fefb7afa73e52976d27b9546b5b1</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-eo-1.2.92.tar.bz2">
koffice-i18n-eo-1.2.92.tar.bz2</a></td>
<td><tt>16fb3cecf7f37c1ccbd221964b6d6f63</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-es-1.2.92.tar.bz2">
koffice-i18n-es-1.2.92.tar.bz2</a></td>
<td><tt>30889420b9a8a8b7cbeca98bf3372a88</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-et-1.2.92.tar.bz2">
koffice-i18n-et-1.2.92.tar.bz2</a></td>
<td><tt>ab9a960169efae13c395836db76f7b5e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-fa-1.2.92.tar.bz2">
koffice-i18n-fa-1.2.92.tar.bz2</a></td>
<td><tt>2bd19edece5653344d2341a528c1f518</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-fr-1.2.92.tar.bz2">
koffice-i18n-fr-1.2.92.tar.bz2</a></td>
<td><tt>74d5b06aae6b0cabaaf5f2aced190b64</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-he-1.2.92.tar.bz2">
koffice-i18n-he-1.2.92.tar.bz2</a></td>
<td><tt>a5550dd931b7250cbc6d7f113705c41a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-hu-1.2.92.tar.bz2">
koffice-i18n-hu-1.2.92.tar.bz2</a></td>
<td><tt>05b4acbbd55d4dfc3bb5e90f1a7de91a</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-it-1.2.92.tar.bz2">
koffice-i18n-it-1.2.92.tar.bz2</a></td>
<td><tt>6fc8120d09f80b48f094204a9a9aa7fe</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-ja-1.2.92.tar.bz2">
koffice-i18n-ja-1.2.92.tar.bz2</a></td>
<td><tt>e2afa9a452f1be653c0490be0592c1ed</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-lo-1.2.92.tar.bz2">
koffice-i18n-lo-1.2.92.tar.bz2</a></td>
<td><tt>d5d7fcd2a8932ba63d0b5e5541de1925</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-nl-1.2.92.tar.bz2">
koffice-i18n-nl-1.2.92.tar.bz2</a></td>
<td><tt>0e66e471f3beade936a627b8341a41ed</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-nn-1.2.92.tar.bz2">
koffice-i18n-nn-1.2.92.tar.bz2</a></td>
<td><tt>25fcdf9bdd6f0b5ece07732c2321e69e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-pl-1.2.92.tar.bz2">
koffice-i18n-pl-1.2.92.tar.bz2</a></td>
<td><tt>df32ef3cbffb1890434e3caa54d86b50</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-pt-1.2.92.tar.bz2">
koffice-i18n-pt-1.2.92.tar.bz2</a></td>
<td><tt>32adb2a0942b710a4cc5abf5c3d4b534</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-pt_BR-1.2.92.tar.bz2">
koffice-i18n-pt_BR-1.2.92.tar.bz2</a></td>
<td><tt>889b0bc526af3648be8440293b6e4ff0</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-ru-1.2.92.tar.bz2">
koffice-i18n-ru-1.2.92.tar.bz2</a></td>
<td><tt>748ba3311b881bf9fe89340faccbc1b8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-se-1.2.92.tar.bz2">
koffice-i18n-se-1.2.92.tar.bz2</a></td>
<td><tt>7828e07aa2695dc4a3c27d403e7b180b</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-sk-1.2.92.tar.bz2">
koffice-i18n-sk-1.2.92.tar.bz2</a></td>
<td><tt>ade8a771354d1d1f8f57da145ad142e0</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-sl-1.2.92.tar.bz2">
koffice-i18n-sl-1.2.92.tar.bz2</a></td>
<td><tt>7f3c843c80ffa2aea2c0a3fa80eab902</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-sv-1.2.92.tar.bz2">
koffice-i18n-sv-1.2.92.tar.bz2</a></td>
<td><tt>af8e8b9df6f5b7717a6282d03897e522</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-tr-1.2.92.tar.bz2">
koffice-i18n-tr-1.2.92.tar.bz2</a></td>
<td><tt>5dac9d1dd1436c8acd5d0cb3a0fe68b7</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-zh_CN-1.2.92.tar.bz2">
koffice-i18n-zh_CN-1.2.92.tar.bz2</a></td>
<td><tt>37fe978e21e12a0b6685158972a08e67</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/koffice-1.2.92/src/koffice-i18n-zh_TW-1.2.92.tar.bz2">
koffice-i18n-zh_TW-1.2.92.tar.bz2</a></td>
<td><tt>c9e7f5894003eed1d34bec584f911f06</tt></td></tr>
</table>
