<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-1.5.0-rc1.tar.bz2">
koffice-1.5.0-rc1.tar.bz2</a></td>
<td><tt>e9346977d18c67185d5b50f49ee8225b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-af-1.5-rc1.tar.bz2">
koffice-l10n-af-1.5-rc1.tar.bz2</a></td>
<td><tt>750fb30aee3591fd1112ba5956a5af77</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-ar-1.5-rc1.tar.bz2">
koffice-l10n-ar-1.5-rc1.tar.bz2</a></td>
<td><tt>86286f6a4ed00c1ddd96c91a9de72502</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-bg-1.5-rc1.tar.bz2">
koffice-l10n-bg-1.5-rc1.tar.bz2</a></td>
<td><tt>1788e6b2e4b99532aaabdb998058829b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-bn-1.5-rc1.tar.bz2">
koffice-l10n-bn-1.5-rc1.tar.bz2</a></td>
<td><tt>5db749a0c1f9299f2ddb9bce6ec03ceb</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-br-1.5-rc1.tar.bz2">
koffice-l10n-br-1.5-rc1.tar.bz2</a></td>
<td><tt>e56ef4fbdef1ffec0dbdb38607d10f6c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-bs-1.5-rc1.tar.bz2">
koffice-l10n-bs-1.5-rc1.tar.bz2</a></td>
<td><tt>4163e34a011e87b385946d112340f658</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-ca-1.5-rc1.tar.bz2">
koffice-l10n-ca-1.5-rc1.tar.bz2</a></td>
<td><tt>0b3d5a08585c2e88b3cc2dac1a64bd18</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-cs-1.5-rc1.tar.bz2">
koffice-l10n-cs-1.5-rc1.tar.bz2</a></td>
<td><tt>e6987c3647956caa4e4842edb7bdc864</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-cy-1.5-rc1.tar.bz2">
koffice-l10n-cy-1.5-rc1.tar.bz2</a></td>
<td><tt>b34b49e0836143caaac7620f84c615fc</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-da-1.5-rc1.tar.bz2">
koffice-l10n-da-1.5-rc1.tar.bz2</a></td>
<td><tt>9883ab8e7195846b7e00212a669033d8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-de-1.5-rc1.tar.bz2">
koffice-l10n-de-1.5-rc1.tar.bz2</a></td>
<td><tt>d4224fadd0f86f566ffa88f6ede5137a</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-el-1.5-rc1.tar.bz2">
koffice-l10n-el-1.5-rc1.tar.bz2</a></td>
<td><tt>757277cbcd8fe5f7d03713bea5c7ca9e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-en_GB-1.5-rc1.tar.bz2">
koffice-l10n-en_GB-1.5-rc1.tar.bz2</a></td>
<td><tt>4c465f228b21be8075e964ed8bfc2f55</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-eo-1.5-rc1.tar.bz2">
koffice-l10n-eo-1.5-rc1.tar.bz2</a></td>
<td><tt>98a5a394f76ad2b1324fbbfc9191aecf</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-es-1.5-rc1.tar.bz2">
koffice-l10n-es-1.5-rc1.tar.bz2</a></td>
<td><tt>6bfa4ee3ff6418c5441478a7b4a77659</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-et-1.5-rc1.tar.bz2">
koffice-l10n-et-1.5-rc1.tar.bz2</a></td>
<td><tt>fa1c263396f497b25a0e337b61d33bf8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-eu-1.5-rc1.tar.bz2">
koffice-l10n-eu-1.5-rc1.tar.bz2</a></td>
<td><tt>288c822579edf6d574e2eb8372076351</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-fi-1.5-rc1.tar.bz2">
koffice-l10n-fi-1.5-rc1.tar.bz2</a></td>
<td><tt>15d128b804acaf2ad73113c20b539b10</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-fr-1.5-rc1.tar.bz2">
koffice-l10n-fr-1.5-rc1.tar.bz2</a></td>
<td><tt>35bdbcb648bf58fc28fce5333c090ada</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-fy-1.5-rc1.tar.bz2">
koffice-l10n-fy-1.5-rc1.tar.bz2</a></td>
<td><tt>dccd154c21e8cd7d95373a7580d42483</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-ga-1.5-rc1.tar.bz2">
koffice-l10n-ga-1.5-rc1.tar.bz2</a></td>
<td><tt>28a1fc149a31a1550358f233eeab23a9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-he-1.5-rc1.tar.bz2">
koffice-l10n-he-1.5-rc1.tar.bz2</a></td>
<td><tt>6bd95311ecd6f0dc5a76dc9a1caa5a0b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-hi-1.5-rc1.tar.bz2">
koffice-l10n-hi-1.5-rc1.tar.bz2</a></td>
<td><tt>a74fd45a7696e51a03558dcd2b4f9670</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-hsb-1.5-rc1.tar.bz2">
koffice-l10n-hsb-1.5-rc1.tar.bz2</a></td>
<td><tt>3d2da5fcf09f95f77f3087162e94770f</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-hu-1.5-rc1.tar.bz2">
koffice-l10n-hu-1.5-rc1.tar.bz2</a></td>
<td><tt>28ec8a5d4c2542ff96acb7d40305762a</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-is-1.5-rc1.tar.bz2">
koffice-l10n-is-1.5-rc1.tar.bz2</a></td>
<td><tt>8c3f11afa1922e6d7fd6dab0f8d24ace</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-it-1.5-rc1.tar.bz2">
koffice-l10n-it-1.5-rc1.tar.bz2</a></td>
<td><tt>04b3c0b9e8f16218968264685407e6ab</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-ja-1.5-rc1.tar.bz2">
koffice-l10n-ja-1.5-rc1.tar.bz2</a></td>
<td><tt>1f810920ec2aec85ea0856b37ebe6f33</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-lt-1.5-rc1.tar.bz2">
koffice-l10n-lt-1.5-rc1.tar.bz2</a></td>
<td><tt>34cce34e772fa87bdfd698a7195c5634</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-mk-1.5-rc1.tar.bz2">
koffice-l10n-mk-1.5-rc1.tar.bz2</a></td>
<td><tt>9f79f0f14d5539c9c0facbe7df5248b2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-nb-1.5-rc1.tar.bz2">
koffice-l10n-nb-1.5-rc1.tar.bz2</a></td>
<td><tt>547697a869c1973f68d53d6ebc7bcba1</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-nds-1.5-rc1.tar.bz2">
koffice-l10n-nds-1.5-rc1.tar.bz2</a></td>
<td><tt>215860f25b37a5cabe43e4f7eebbbf13</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-nl-1.5-rc1.tar.bz2">
koffice-l10n-nl-1.5-rc1.tar.bz2</a></td>
<td><tt>2ed016b0e6fa4f47d4755c4dd160816d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-nn-1.5-rc1.tar.bz2">
koffice-l10n-nn-1.5-rc1.tar.bz2</a></td>
<td><tt>fc3b88a9d8912fd1d84c6486ede5ccc8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-pa-1.5-rc1.tar.bz2">
koffice-l10n-pa-1.5-rc1.tar.bz2</a></td>
<td><tt>115bb8c75ca36c5b174a81493d8b6718</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-pl-1.5-rc1.tar.bz2">
koffice-l10n-pl-1.5-rc1.tar.bz2</a></td>
<td><tt>859790e80df1d88dba631d33b15dc375</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-pt-1.5-rc1.tar.bz2">
koffice-l10n-pt-1.5-rc1.tar.bz2</a></td>
<td><tt>07e612c2180d157b68356d7fcb025297</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-pt_BR-1.5-rc1.tar.bz2">
koffice-l10n-pt_BR-1.5-rc1.tar.bz2</a></td>
<td><tt>78d6ae1c9e8ffc3017fa3b2ccc98c02c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-ro-1.5-rc1.tar.bz2">
koffice-l10n-ro-1.5-rc1.tar.bz2</a></td>
<td><tt>2eca9c2b4a7b1ab12f998a6588cafc19</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-ru-1.5-rc1.tar.bz2">
koffice-l10n-ru-1.5-rc1.tar.bz2</a></td>
<td><tt>7afe8824a2f1d85141cd06e578fd479d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-se-1.5-rc1.tar.bz2">
koffice-l10n-se-1.5-rc1.tar.bz2</a></td>
<td><tt>85dfa5c2d18a0e3005690f1763c73bfa</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-sk-1.5-rc1.tar.bz2">
koffice-l10n-sk-1.5-rc1.tar.bz2</a></td>
<td><tt>5e7c2d53f04ffde0bc0484d1611b7939</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-sl-1.5-rc1.tar.bz2">
koffice-l10n-sl-1.5-rc1.tar.bz2</a></td>
<td><tt>9371fbdaa1dd2c6ec6a0b6f66a49d402</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-sr-1.5-rc1.tar.bz2">
koffice-l10n-sr-1.5-rc1.tar.bz2</a></td>
<td><tt>e55eb189e89ac0b0d7a6fd4ad66019e9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-sr@Latn-1.5-rc1.tar.bz2">
koffice-l10n-sr@Latn-1.5-rc1.tar.bz2</a></td>
<td><tt>4a73f740ce5e54643328659fe08face9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-sv-1.5-rc1.tar.bz2">
koffice-l10n-sv-1.5-rc1.tar.bz2</a></td>
<td><tt>915a9b84d8530c9ef910c650ffc8e142</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-ta-1.5-rc1.tar.bz2">
koffice-l10n-ta-1.5-rc1.tar.bz2</a></td>
<td><tt>605133320da5bd9c6317427f895a36e2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-tg-1.5-rc1.tar.bz2">
koffice-l10n-tg-1.5-rc1.tar.bz2</a></td>
<td><tt>27e30323712effc88b4c448c041dc821</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-tr-1.5-rc1.tar.bz2">
koffice-l10n-tr-1.5-rc1.tar.bz2</a></td>
<td><tt>be9ea57c487a91f358e06befd6d32dc7</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-uk-1.5-rc1.tar.bz2">
koffice-l10n-uk-1.5-rc1.tar.bz2</a></td>
<td><tt>50d3fb8e74698196d847ce2773ca51e0</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/unstable/koffice-1.5.0-rc1/src/koffice-l10n/koffice-l10n-zh_CN-1.5-rc1.tar.bz2">
koffice-l10n-zh_CN-1.5-rc1.tar.bz2</a></td>
<td><tt>c88d026faf7486841e3fd98eef829865</tt></td></tr>
</table>
<p>*: XDelta patches</p>
