<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-1.4.0a.tar.bz2">
koffice-1.4.0a.tar.bz2</a></td>
<td><tt>9a8494144962ea5434397289ed326385</tt></td></tr>
<tr><td>General *</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-1.3.5-1.4.0a.tar.xdelta">
koffice-1.3.5-1.4.0a.tar.xdelta</a></td>
<td><tt>5c6829f73848ecd52818b8dcdb38a900</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-bg-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-bg-1.4.0.tar.bz2</a></td>
<td><tt>652633b53f58e856650efccd2374fac7</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-ca-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.4.0.tar.bz2</a></td>
<td><tt>3a4aa4fd99e184a2a0eb762e0f081cb5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-cs-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.4.0.tar.bz2</a></td>
<td><tt>2018d10c04fb3f621ac6545f30724769</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-cy-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.4.0.tar.bz2</a></td>
<td><tt>dfea4ce2c5f5bc53e63545ef7436844e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-da-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-da-1.4.0.tar.bz2</a></td>
<td><tt>43d717e080a7f8dabe091e3385049586</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-de-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-de-1.4.0.tar.bz2</a></td>
<td><tt>01dc7d3203c04810ab101ea066ba5011</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-el-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-el-1.4.0.tar.bz2</a></td>
<td><tt>36e093ee1e38ffa2e3bd499944fe8bed</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-en_GB-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.4.0.tar.bz2</a></td>
<td><tt>e3440256589346604c25379e3eaee173</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-es-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-es-1.4.0.tar.bz2</a></td>
<td><tt>be2751769dc0cbf0c5bdea7000aaddd2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-et-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-et-1.4.0.tar.bz2</a></td>
<td><tt>acb1de7b44ac00fd980f45dab072ec27</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-fr-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.4.0.tar.bz2</a></td>
<td><tt>dca0b734646ef2c80f5aeb5174e6abb8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-hu-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.4.0.tar.bz2</a></td>
<td><tt>8120fbdf7dc04a459e3f6fb3e2057d0b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-it-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-it-1.4.0.tar.bz2</a></td>
<td><tt>a75556e17c8b56c29da8f08f8341af03</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-nb-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.4.0.tar.bz2</a></td>
<td><tt>21756b745a5fe76a14a191a0cc18db1f</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-nl-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.4.0.tar.bz2</a></td>
<td><tt>a33730c00e94427d74013668e5721c47</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-nn-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-nn-1.4.0.tar.bz2</a></td>
<td><tt>cad72eca45efa7d0d466050ca1c63cb5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-pl-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.4.0.tar.bz2</a></td>
<td><tt>67a12f1f43161ee5c379a472963f778c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-pt-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.4.0.tar.bz2</a></td>
<td><tt>e1b1ff4ee0b411bb5272108361072ac3</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-pt_BR-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.4.0.tar.bz2</a></td>
<td><tt>ba8baffd29f90decd1810bbecc150624</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-ru-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.4.0.tar.bz2</a></td>
<td><tt>b86614ed09f9f9294ea5979365d8b2fb</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-sl-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.4.0.tar.bz2</a></td>
<td><tt>a755bebf90d91da25a46f1aad97aa399</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-sr-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.4.0.tar.bz2</a></td>
<td><tt>a59aca9f90878019cb3a04fa4e242b20</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-sr@Latn-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.4.0.tar.bz2</a></td>
<td><tt>426638826d599bd6d01735a52b8ecd65</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-sv-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.4.0.tar.bz2</a></td>
<td><tt>438ec2910393c425a1d5964dd8b7da45</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-ta-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-ta-1.4.0.tar.bz2</a></td>
<td><tt>ee0ccda7e73b03ad5ef46d209cc5df7c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-tg-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-tg-1.4.0.tar.bz2</a></td>
<td><tt>23083ab3f97d9ebdd8e8c8733f3fe06c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.4/src/koffice-l10n/koffice-l10n-zh_CN-1.4.0.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.4.0.tar.bz2</a></td>
<td><tt>e98a9df0ee26a10267355b612dd0a019</tt></td></tr>
</table>
<p>*: XDelta patches</p>
