<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>KOffice 1.6 RC1 (source)</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-1.5.92.tar.bz2">
koffice-1.5.92.tar.bz2</a></td>
<td><tt>2134a0d09a3f98b91a062c7bafb57622</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-ca-1.5.92.tar.bz2">
koffice-l10n-ca-1.5.92.tar.bz2</a></td>
<td><tt>400cc7b0f970625baf8252e8a6fde104</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-cs-1.5.92.tar.bz2">
koffice-l10n-af-1.5.92.tar.bz2</a></td>
<td><tt>dff7df595a9a5f842b456e2cb551f668</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-cy-1.5.92.tar.bz2">
koffice-l10n-cy-1.5.92.tar.bz2</a></td>
<td><tt>35a6ab2616a730e8986bb296d935b663</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-da-1.5.92.tar.bz2">
koffice-l10n-da-1.5.92.tar.bz2</a></td>
<td><tt>5829cfc7b004ec62be70734ba3414db0</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-de-1.5.92.tar.bz2">
koffice-l10n-de-1.5.92.tar.bz2</a></td>
<td><tt>d28b1c200459a3cb4a0dfc92919bbbe1</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-el-1.5.92.tar.bz2">
koffice-l10n-el-1.5.92.tar.bz2</a></td>
<td><tt>e7a541b46e21c66a775b472a97a919dc</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-en_GB-1.5.92.tar.bz2">
koffice-l10n-en_GB-1.5.92.tar.bz2</a></td>
<td><tt>032476060fda929f73e7db686f22d1d9</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-es-1.5.92.tar.bz2">
koffice-l10n-es-1.5.92.tar.bz2</a></td>
<td><tt>1dab28f64686e853ce470b37f54e2716</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-et-1.5.92.tar.bz2">
koffice-l10n-et-1.5.92.tar.bz2</a></td>
<td><tt>e9d7685ca45bc4a046991fb1fe081775</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-eu-1.5.92.tar.bz2">
koffice-l10n-eu-1.5.92.tar.bz2</a></td>
<td><tt>55e93523d3c060493b8a28d4346c398b</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-fi-1.5.92.tar.bz2">
koffice-l10n-fi-1.5.92.tar.bz2</a></td>
<td><tt>010740a059a4e043e965fdd2e6eacc32</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-fr-1.5.92.tar.bz2">
koffice-l10n-fr-1.5.92.tar.bz2</a></td>
<td><tt>ade116e23961822c74adad44658c8fdf</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-hu-1.5.92.tar.bz2">
koffice-l10n-hu-1.5.92.tar.bz2</a></td>
<td><tt>a596241290031373b95c7d3277888a0d</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-it-1.5.92.tar.bz2">
koffice-l10n-it-1.5.92.tar.bz2</a></td>
<td><tt>0302da961200626efbb59d0fed85888e</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-ja-1.5.92.tar.bz2">
koffice-l10n-ja-1.5.92.tar.bz2</a></td>
<td><tt>e8202fff8db3356702fd766c5c29018b</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-ms-1.5.92.tar.bz2">
koffice-l10n-ms-1.5.92.tar.bz2</a></td>
<td><tt>5ed1e21e6804ceb3528ea1d9410d4af0</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-nb-1.5.92.tar.bz2">
koffice-l10n-nb-1.5.92.tar.bz2</a></td>
<td><tt>16aae845e06c5b152fbf142c8706ee39</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-nl-1.5.92.tar.bz2">
koffice-l10n-nl-1.5.92.tar.bz2</a></td>
<td><tt>699dd8ddfd249c3d0f0f7c085d5a249e</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-pl-1.5.92.tar.bz2">
koffice-l10n-pl-1.5.92.tar.bz2</a></td>
<td><tt>9326084eacc927cdcb9c832f6a24bf01</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-pt-1.5.92.tar.bz2">
koffice-l10n-pt-1.5.92.tar.bz2</a></td>
<td><tt>f79d7749f6ef07c3d3c59e54091a77b4</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-pt_BR-1.5.92.tar.bz2">
koffice-l10n-pt_BR-1.5.92.tar.bz2</a></td>
<td><tt>37b90a09dc0e1250c6682fe28d811a2e</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-ru-1.5.92.tar.bz2">
koffice-l10n-ru-1.5.92.tar.bz2</a></td>
<td><tt>903a090960865515c8fa25ac158c67a5</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-sk-1.5.92.tar.bz2">
koffice-l10n-sk-1.5.92.tar.bz2</a></td>
<td><tt>948b78fcc83203be0105859cc69369d5</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-sl-1.5.92.tar.bz2">
koffice-l10n-sl-1.5.92.tar.bz2</a></td>
<td><tt>7d24d234bfbf75d17b33db0363c98bb2</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-sr-1.5.92.tar.bz2">
koffice-l10n-sr-1.5.92.tar.bz2</a></td>
<td><tt>27692c643a122b218812d1c687ec553d</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-sr@Latn-1.5.92.tar.bz2">
koffice-l10n-sr@Latn-1.5.92.tar.bz2</a></td>
<td><tt>492599a1761bf057b37383fdd3501a94</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-sv-1.5.92.tar.bz2">
koffice-l10n-sv-1.5.92.tar.bz2</a></td>
<td><tt>fa64133190a15cf791287a257562b273</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n/koffice-l10n-uk-1.5.92.tar.bz2">
koffice-l10n/koffice-l10n-uk-1.5.92.tar.bz2</a></td>
<td><tt>293943cbd34cde4e598c6e4b950b7561</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-zh_CN-1.5.92.tar.bz2">
koffice-l10n-zh_CN-1.5.92.tar.bz2</a></td>
<td><tt>30375256cb733c76921b04360d10e575</tt></td></tr>
<tr><td>Translation</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-rc1/src/koffice-l10n/koffice-l10n-zh_TW-1.5.92.tar.bz2">
koffice-l10n-zh_TW-1.5.92.tar.bz2</a></td>
<td><tt>36d62a01fd568cc8b6a0512dcc828301</tt></td></tr>
</table>
