<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top"><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-1.2.90.tar.bz2">
koffice-1.2.90.tar.bz2</a></td>
<td><tt>5f08ec8a42aacd7dcaf7899d486c9885</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-1.2.90.tar.bz2">
koffice-i18n-1.2.90.tar.bz2</a></td>
<td><tt>bf68b267ba17c95464ddbfb297648674</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-af-1.2.90.tar.bz2">
koffice-i18n-af-1.2.90.tar.bz2</a></td>
<td><tt>96cbf10f66cee8111031899a4cf2d6ef</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-bg-1.2.90.tar.bz2">
koffice-i18n-bg-1.2.90.tar.bz2</a></td>
<td><tt>9246452f853159ddb60499b24a6c387f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-ca-1.2.90.tar.bz2">
koffice-i18n-ca-1.2.90.tar.bz2</a></td>
<td><tt>7031d2f771702dd6ed2e79a014570d81</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-cs-1.2.90.tar.bz2">
koffice-i18n-cs-1.2.90.tar.bz2</a></td>
<td><tt>20eb444dca23ff2ec9ffee3c492c9c0d</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-da-1.2.90.tar.bz2">
koffice-i18n-da-1.2.90.tar.bz2</a></td>
<td><tt>996bc200bae712a536acdd522f0a4e8e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-de-1.2.90.tar.bz2">
koffice-i18n-de-1.2.90.tar.bz2</a></td>
<td><tt>73880a67a00db76a40fd5bff02e85735</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-el-1.2.90.tar.bz2">
koffice-i18n-el-1.2.90.tar.bz2</a></td>
<td><tt>ca4c0d45c371ee294ef456f840c571f7</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-en_GB-1.2.90.tar.bz2">
koffice-i18n-en_GB-1.2.90.tar.bz2</a></td>
<td><tt>5e00d1ec16c0e33586b4b89758a1f699</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-eo-1.2.90.tar.bz2">
koffice-i18n-eo-1.2.90.tar.bz2</a></td>
<td><tt>069e517964e6aa18f5312d0cdb1a4bbc</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-es-1.2.90.tar.bz2">
koffice-i18n-es-1.2.90.tar.bz2</a></td>
<td><tt>9dd11233ce5208ee1f45d64aa448be6e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-et-1.2.90.tar.bz2">
koffice-i18n-et-1.2.90.tar.bz2</a></td>
<td><tt>ced7d0253cf3f2f54117ae0766918465</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-fr-1.2.90.tar.bz2">
koffice-i18n-fr-1.2.90.tar.bz2</a></td>
<td><tt>a823beeeac4945ccd207bfd40dc9e498</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-he-1.2.90.tar.bz2">
koffice-i18n-he-1.2.90.tar.bz2</a></td>
<td><tt>d7863eaf721474020250c707aee1d2ce</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-hu-1.2.90.tar.bz2">
koffice-i18n-hu-1.2.90.tar.bz2</a></td>
<td><tt>2e7baae647d8387473f57463dda432d2</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-it-1.2.90.tar.bz2">
koffice-i18n-it-1.2.90.tar.bz2</a></td>
<td><tt>87f557a8eadef43aaa80c4a0dd55d6d7</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-ja-1.2.90.tar.bz2">
koffice-i18n-ja-1.2.90.tar.bz2</a></td>
<td><tt>575e921e97558f9f78314347db746a68</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-lo-1.2.90.tar.bz2">
koffice-i18n-lo-1.2.90.tar.bz2</a></td>
<td><tt>bb5077ebfd47b0c2002f215658a16784</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-lv-1.2.90.tar.bz2">
koffice-i18n-lv-1.2.90.tar.bz2</a></td>
<td><tt>4edbf42a10da6185c21d836e61004979</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-mt-1.2.90.tar.bz2">
koffice-i18n-mt-1.2.90.tar.bz2</a></td>
<td><tt>b23e352bc85b1e1e2c9cfc1b4751c537</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-nb-1.2.90.tar.bz2">
koffice-i18n-nb-1.2.90.tar.bz2</a></td>
<td><tt>e9260bd190de1427dc165437c314f0ea</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-nl-1.2.90.tar.bz2">
koffice-i18n-nl-1.2.90.tar.bz2</a></td>
<td><tt>e3eccbb9fbfba89fc4d05bbc95814fec</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-nn-1.2.90.tar.bz2">
koffice-i18n-nn-1.2.90.tar.bz2</a></td>
<td><tt>d0d1904e69ef0f77a5a06f081535707e</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-pl-1.2.90.tar.bz2">
koffice-i18n-pl-1.2.90.tar.bz2</a></td>
<td><tt>412de0a10e6c19ae3d430cbe9fd7e661</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-pt-1.2.90.tar.bz2">
koffice-i18n-pt-1.2.90.tar.bz2</a></td>
<td><tt>236cc8da1423274616f5102a0accf94f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-pt_BR-1.2.90.tar.bz2">
koffice-i18n-pt_BR-1.2.90.tar.bz2</a></td>
<td><tt>1c4d1f85d9ec312e273debe191d9326f</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-ru-1.2.90.tar.bz2">
koffice-i18n-ru-1.2.90.tar.bz2</a></td>
<td><tt>5d07e41b16d575ffa8ad61dd87f8050c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-sk-1.2.90.tar.bz2">
koffice-i18n-sk-1.2.90.tar.bz2</a></td>
<td><tt>196ef7fdd443b6d3234cc2596c6b3d43</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-sl-1.2.90.tar.bz2">
koffice-i18n-sl-1.2.90.tar.bz2</a></td>
<td><tt>17fef952be89d3afcd86b5f88f8a8a2c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-sr-1.2.90.tar.bz2">
koffice-i18n-sr-1.2.90.tar.bz2</a></td>
<td><tt>fa2db5f66eaf9371bc97523206a4a006</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-sv-1.2.90.tar.bz2">
koffice-i18n-sv-1.2.90.tar.bz2</a></td>
<td><tt>955c5e7edc5c31dbccb9aac4dbfba191</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-tr-1.2.90.tar.bz2">
koffice-i18n-tr-1.2.90.tar.bz2</a></td>
<td><tt>e1ffb873728516b54794d8eae6613670</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-uk-1.2.90.tar.bz2">
koffice-i18n-uk-1.2.90.tar.bz2</a></td>
<td><tt>b6de99aecf0e7fbb2004633f96273fad</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-ven-1.2.90.tar.bz2">
koffice-i18n-ven-1.2.90.tar.bz2</a></td>
<td><tt>27541d8040b74c1104c9fbcad093438c</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-xh-1.2.90.tar.bz2">
koffice-i18n-xh-1.2.90.tar.bz2</a></td>
<td><tt>755f8483076f0de70517575ad42df0b8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-zh_CN-1.2.90.tar.bz2">
koffice-i18n-zh_CN-1.2.90.tar.bz2</a></td>
<td><tt>036fa2333ed268641e7d9cb6af842ba8</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-zh_TW-1.2.90.tar.bz2">
koffice-i18n-zh_TW-1.2.90.tar.bz2</a></td>
<td><tt>1337350f29a7ce8a00395db06e1bdf96</tt></td></tr>
<tr valign="top"><td><a href="http://download.kde.org/unstable/1.2.90/src/koffice-i18n-zu-1.2.90.tar.bz2">
koffice-i18n-zu-1.2.90.tar.bz2</a></td>
<td><tt>4f409e3c912287238226af78a99c0d14</tt></td></tr>
</table>
