<table border="0" cellpadding="4" cellspacing="0">
<tr valign="top">
  <th align="left">Location</th>
  <th align="left">Size</th>
  <th align="left">MD5&nbsp;Sum</th>
</tr>
<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-1.5.0.tar.bz2">koffice-1.5.0</a></td>
   <td align="right">34MB</td>
   <td><tt>220b6bde28b5ebd5c6621bc87ca2c05f</tt></td>
</tr>
<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-af-1.5.0.tar.bz2">koffice-l10n-af-1.5.0</a></td>
   <td align="right">296kB</td>
   <td><tt>03217f2f39b1a21cc685a5aa85200247</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-ar-1.5.0.tar.bz2">koffice-l10n-ar-1.5.0</a></td>
   <td align="right">313kB</td>
   <td><tt>922cdc3f2de8d350deaf54c32feab117</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-bg-1.5.0.tar.bz2">koffice-l10n-bg-1.5.0</a></td>
   <td align="right">348kB</td>
   <td><tt>5e24b5028de337c2cbda323fa69d56f2</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-br-1.5.0.tar.bz2">koffice-l10n-br-1.5.0</a></td>
   <td align="right">338kB</td>
   <td><tt>4c5c9d834f14defd87c5580092002e51</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-bs-1.5.0.tar.bz2">koffice-l10n-bs-1.5.0</a></td>
   <td align="right">311kB</td>
   <td><tt>6086121e25b243d7b5543dc15ebaf3ee</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-ca-1.5.0.tar.bz2">koffice-l10n-ca-1.5.0</a></td>
   <td align="right">412kB</td>
   <td><tt>cc24df3b6d3899b89776e2d2cabb3eb5</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-cs-1.5.0.tar.bz2">koffice-l10n-cs-1.5.0</a></td>
   <td align="right">343kB</td>
   <td><tt>193f7d66d9b5c945932ee9868721f9f1</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-cy-1.5.0.tar.bz2">koffice-l10n-cy-1.5.0</a></td>
   <td align="right">365kB</td>
   <td><tt>14c6069119fb491e6b430d6663e3a60f</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-da-1.5.0.tar.bz2">koffice-l10n-da-1.5.0</a></td>
   <td align="right">991kB</td>
   <td><tt>fedd3f7c0c39a40940576fb86d7262f0</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-de-1.5.0.tar.bz2">koffice-l10n-de-1.5.0</a></td>
   <td align="right">2.6MB</td>
   <td><tt>fe3334c31472b006907f59f47db6cb75</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-el-1.5.0.tar.bz2">koffice-l10n-el-1.5.0</a></td>
   <td align="right">362kB</td>
   <td><tt>d7384ecf60617aa054ec3ded25cff1ea</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-en_GB-1.5.0.tar.bz2">koffice-l10n-en_GB-1.5.0</a></td>
   <td align="right">335kB</td>
   <td><tt>5f00c66613f2250babd4cb02590952df</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-eo-1.5.0.tar.bz2">koffice-l10n-eo-1.5.0</a></td>
   <td align="right">355kB</td>
   <td><tt>79d73a7d8e5a284e1c997cbec6bc804c</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-es-1.5.0.tar.bz2">koffice-l10n-es-1.5.0</a></td>
   <td align="right">8.2MB</td>
   <td><tt>0abef42c4ea3a0992b69933ad1e94287</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-et-1.5.0.tar.bz2">koffice-l10n-et-1.5.0</a></td>
   <td align="right">1.0MB</td>
   <td><tt>149ba841f9dc322336b9c153b598dea5</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-eu-1.5.0.tar.bz2">koffice-l10n-eu-1.5.0</a></td>
   <td align="right">350kB</td>
   <td><tt>af2a4e93887cd55ba0cda123362650d7</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-fi-1.5.0.tar.bz2">koffice-l10n-fi-1.5.0</a></td>
   <td align="right">341kB</td>
   <td><tt>e87c44fc8c7b10c4c44c76d90cb1ca7c</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-fr-1.5.0.tar.bz2">koffice-l10n-fr-1.5.0</a></td>
   <td align="right">6.2MB</td>
   <td><tt>65b9b6fd7903050c4c170af11aa94fb2</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-ga-1.5.0.tar.bz2">koffice-l10n-ga-1.5.0</a></td>
   <td align="right">305kB</td>
   <td><tt>47b453c7444e404c19cc8dc85cf56d37</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-he-1.5.0.tar.bz2">koffice-l10n-he-1.5.0</a></td>
   <td align="right">334kB</td>
   <td><tt>1d0810b08947f072631615ffa3260bec</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-hi-1.5.0.tar.bz2">koffice-l10n-hi-1.5.0</a></td>
   <td align="right">321kB</td>
   <td><tt>82231d5c7e273d0384d04e80be228167</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-hu-1.5.0.tar.bz2">koffice-l10n-hu-1.5.0</a></td>
   <td align="right">359kB</td>
   <td><tt>9c1d2441a49eaf06a6adac3f61590076</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-is-1.5.0.tar.bz2">koffice-l10n-is-1.5.0</a></td>
   <td align="right">348kB</td>
   <td><tt>3fc01e0a34d0ce9a2988ef30df638f62</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-it-1.5.0.tar.bz2">koffice-l10n-it-1.5.0</a></td>
   <td align="right">1.2MB</td>
   <td><tt>db8b9a1bb5114e69c3768508c09bde8d</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-ja-1.5.0.tar.bz2">koffice-l10n-ja-1.5.0</a></td>
   <td align="right">342kB</td>
   <td><tt>16435cf9fd545529bea61010fb35ad03</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-lt-1.5.0.tar.bz2">koffice-l10n-lt-1.5.0</a></td>
   <td align="right">263kB</td>
   <td><tt>c306e0bfdccd60fd9f11e93828475fac</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-mk-1.5.0.tar.bz2">koffice-l10n-mk-1.5.0</a></td>
   <td align="right">234kB</td>
   <td><tt>b0469b72436e35a1101ee9ea4e981ae3</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-nb-1.5.0.tar.bz2">koffice-l10n-nb-1.5.0</a></td>
   <td align="right">353kB</td>
   <td><tt>8cffcf181366737bea12a1ae9a14c294</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-nl-1.5.0.tar.bz2">koffice-l10n-nl-1.5.0</a></td>
   <td align="right">3.1MB</td>
   <td><tt>f4bfc5952a2612c72443d266df034e7d</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-nn-1.5.0.tar.bz2">koffice-l10n-nn-1.5.0</a></td>
   <td align="right">354kB</td>
   <td><tt>bb3444c52bcbc33aaaad542454048c69</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-pl-1.5.0.tar.bz2">koffice-l10n-pl-1.5.0</a></td>
   <td align="right">370kB</td>
   <td><tt>442946625f984e8eb9f977c39a57749d</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-pt-1.5.0.tar.bz2">koffice-l10n-pt-1.5.0</a></td>
   <td align="right">816kB</td>
   <td><tt>285b5766d9955de0fd7c2599b25115ab</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-pt_BR-1.5.0.tar.bz2">koffice-l10n-pt_BR-1.5.0</a></td>
   <td align="right">1.9MB</td>
   <td><tt>41373317668d2d7cbc20e4a5a188daf6</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-ro-1.5.0.tar.bz2">koffice-l10n-ro-1.5.0</a></td>
   <td align="right">294kB</td>
   <td><tt>35fb855cb7c18b95a11602a7c8483d2d</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-ru-1.5.0.tar.bz2">koffice-l10n-ru-1.5.0</a></td>
   <td align="right">812kB</td>
   <td><tt>f5842b78af8ba903129942dfa7f6d7d4</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-se-1.5.0.tar.bz2">koffice-l10n-se-1.5.0</a></td>
   <td align="right">273kB</td>
   <td><tt>d153416b1403f7e4cf8a03b5739ab6a9</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-sk-1.5.0.tar.bz2">koffice-l10n-sk-1.5.0</a></td>
   <td align="right">920kB</td>
   <td><tt>400b547e0520fe769594d4f39c3ec769</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-sl-1.5.0.tar.bz2">koffice-l10n-sl-1.5.0</a></td>
   <td align="right">351kB</td>
   <td><tt>7e73b04ed5952631efa8ef9ed216ce3d</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-sr-1.5.0.tar.bz2">koffice-l10n-sr-1.5.0</a></td>
   <td align="right">360kB</td>
   <td><tt>5b7f01f22ae97c8983411b043c41a689</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-sr@Latn-1.5.0.tar.bz2">koffice-l10n-sr@Latn-1.5.0</a></td>
   <td align="right">370kB</td>
   <td><tt>5bafc53a3c3b4f863fd28fc9f0a090f9</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-sv-1.5.0.tar.bz2">koffice-l10n-sv-1.5.0</a></td>
   <td align="right">5.6MB</td>
   <td><tt>810dd9311472f1e60f90c9fdfcc6c84c</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-ta-1.5.0.tar.bz2">koffice-l10n-ta-1.5.0</a></td>
   <td align="right">340kB</td>
   <td><tt>2991caa710ad20da8925331a51026498</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-tg-1.5.0.tar.bz2">koffice-l10n-tg-1.5.0</a></td>
   <td align="right">341kB</td>
   <td><tt>3c9f50e64cc892cfcb840c424b2940e4</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-tr-1.5.0.tar.bz2">koffice-l10n-tr-1.5.0</a></td>
   <td align="right">345kB</td>
   <td><tt>411466bf3f0f7340431f2f6448332a89</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-uk-1.5.0.tar.bz2">koffice-l10n-uk-1.5.0</a></td>
   <td align="right">344kB</td>
   <td><tt>8e3294a78b9beab5122703d61d2e9a2c</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-uz-1.5.0.tar.bz2">koffice-l10n-uz-1.5.0</a></td>
   <td align="right">266kB</td>
   <td><tt>ace68fe74216fb0a57024fb3b750fdaf</tt></td>
</tr>

<tr valign="top">
   <td><a href="http://download.kde.org/stable/koffice-1.5.0/src/koffice-l10n/koffice-l10n-zh_CN-1.5.0.tar.bz2">koffice-l10n-zh_CN-1.5.0</a></td>
   <td align="right">340kB</td>
   <td><tt>3b15bc617451461f9911ad316a264005</tt></td>
</tr>

</table>
