<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-1.6.2.tar.bz2">
koffice-1.6.2.tar.bz2</a></td>
<td><tt>74ef62a5f8f766fe8192d5b7d65a3928</tt></td></tr>
<tr><td>Catalan</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-ca-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.6.2.tar.bz2</a></td>
<td><tt>8809746f5856aa7c2b37583425501ea7</tt></td></tr>
<tr><td>Czech</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-cs-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.6.2.tar.bz2</a></td>
<td><tt>2b7eb0aa4a3e21048d073b414cbca26e</tt></td></tr>
<tr><td>Welsh</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-cy-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.6.2.tar.bz2</a></td>
<td><tt>8d731dd80ebeb2d89263a3884c0fef44</tt></td></tr>
<tr><td>Danish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-da-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-da-1.6.2.tar.bz2</a></td>
<td><tt>ed57736b883215dce9d8cf6985d70fe2</tt></td></tr>
<tr><td>German</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-de-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-de-1.6.2.tar.bz2</a></td>
<td><tt>3cf83fceb1caff5ba1c5bcad31a7df81</tt></td></tr>
<tr><td>Greek</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-el-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-el-1.6.2.tar.bz2</a></td>
<td><tt>239ea87f98dc701cc8b4b6b1ef1372b9</tt></td></tr>
<tr><td>British English</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-en_GB-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.6.2.tar.bz2</a></td>
<td><tt>445f7990c5ecb9118cbe3c7d68c74654</tt></td></tr>
<tr><td>Spanish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-es-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-es-1.6.2.tar.bz2</a></td>
<td><tt>d10222e3c617f73327db7eee522ce753</tt></td></tr>
<tr><td>Estonian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-et-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-et-1.6.2.tar.bz2</a></td>
<td><tt>e7a4017b8db71204650c44bc72cd9500</tt></td></tr>
<tr><td>Basque</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-eu-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-eu-1.6.2.tar.bz2</a></td>
<td><tt>78244fb0777c69433dbc406bd2d5d0cc</tt></td></tr>
<tr><td>Farsi</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-fa-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-fa-1.6.2.tar.bz2</a></td>
<td><tt>c210ae6ee1dac06f0858a73183db22b6</tt></td></tr>
<tr><td>Finnish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-fi-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.6.2.tar.bz2</a></td>
<td><tt>1d3904967d3a8be1616dc0c215f4e196</tt></td></tr>
<tr><td>French</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-fr-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.6.2.tar.bz2</a></td>
<td><tt>d6ba1878f85ad21d678019098124094b</tt></td></tr>
<tr><td>Irish Gaelic</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-ga-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-ga-1.6.2.tar.bz2</a></td>
<td><tt>721f0ae5b438ffba3e2b48b442bb4329</tt></td></tr>
<tr><td>Galician</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-gl-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-gl-1.6.2.tar.bz2</a></td>
<td><tt>ab7b69562abe5d66618aa1d03296ebaa</tt></td></tr>
<tr><td>Hungarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-hu-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.6.2.tar.bz2</a></td>
<td><tt>6e5789a140283e98e3240cc1ca516ce8</tt></td></tr>
<tr><td>Italian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-it-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-it-1.6.2.tar.bz2</a></td>
<td><tt>91b2df95b845fa9aabbe33a9af8e37f9</tt></td></tr>
<tr><td>Japanese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-ja-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-ja-1.6.2.tar.bz2</a></td>
<td><tt>d77a310c8563318dc4ced31c9fe2f2ce</tt></td></tr>
<tr><td>Khmer</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-km-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-km-1.6.2.tar.bz2</a></td>
<td><tt>a199933f40e29a3fe05c4cfd52525479</tt></td></tr>
<tr><td>Latvian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-lv-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-lv-1.6.2.tar.bz2</a></td>
<td><tt>7e1938aa7dfef401759122bdbd54c98d</tt></td></tr>
<tr><td>Malay</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-ms-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-ms-1.6.2.tar.bz2</a></td>
<td><tt>dbe0339a7d7bf8626e4ea7ccc8ef5c1b</tt></td></tr>
<tr><td>Norwegian Bokm&aring;l</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-nb-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.6.2.tar.bz2</a></td>
<td><tt>72578347facd96247c52d48ccbbf1f0b</tt></td></tr>
<tr><td>Dutch</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-nl-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.6.2.tar.bz2</a></td>
<td><tt>201de20b5285ac1ffccb16e75f1472e7</tt></td></tr>
<tr><td>Polish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-pl-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.6.2.tar.bz2</a></td>
<td><tt>ce121b8c225a6ffd4530b095f1b590e9</tt></td></tr>
<tr><td>Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-pt-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.6.2.tar.bz2</a></td>
<td><tt>f8f90316c3aacc6a6c9150d1241a808d</tt></td></tr>
<tr><td>Brazilian Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-pt_BR-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.6.2.tar.bz2</a></td>
<td><tt>2502c7ad3f66da2d51b643531acde224</tt></td></tr>
<tr><td>Russian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-ru-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.6.2.tar.bz2</a></td>
<td><tt>0fc0f3c8942acc6c4f87ee37e76f48f8</tt></td></tr>
<tr><td>Slovak</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-sk-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-sk-1.6.2.tar.bz2</a></td>
<td><tt>8f151c52c09db40849cd67bcc11cb447</tt></td></tr>
<tr><td>Slovenian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-sl-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.6.2.tar.bz2</a></td>
<td><tt>0e12b6670b31a089c054b9b7370ba4d3</tt></td></tr>
<tr><td>Serbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-sr-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.6.2.tar.bz2</a></td>
<td><tt>94fb0ca00bd2f089db2854413316fe87</tt></td></tr>
<tr><td>Serbian Latin</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-sr@Latn-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.6.2.tar.bz2</a></td>
<td><tt>93f0ba1b6b54d677a354806f0e204fe5</tt></td></tr>
<tr><td>Swedish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-sv-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.6.2.tar.bz2</a></td>
<td><tt>f63e6deda90f6bc1f10985c5e7971add</tt></td></tr>
<tr><td>Turkish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-tr-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-tr-1.6.2.tar.bz2</a></td>
<td><tt>a17e9f38819b242b9019b92412b2d22f</tt></td></tr>
<tr><td>Ukrainian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-uk-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-uk-1.6.2.tar.bz2</a></td>
<td><tt>983b0509583a7aa08684310f6d4133a4</tt></td></tr>
<tr><td>Chinese Simplified</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-zh_CN-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.6.2.tar.bz2</a></td>
<td><tt>64e8c0cac900d22d4a1cc04c9be160af</tt></td></tr>
<tr><td>Chinese Traditional</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.2/src/koffice-l10n/koffice-l10n-zh_TW-1.6.2.tar.bz2">
koffice-l10n/koffice-l10n-zh_TW-1.6.2.tar.bz2</a></td>
<td><tt>bc25552d0a21146b542bc764c1fed5a1</tt></td></tr>
</table>
<p>*: XDelta patches</p>
