<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-1.6.3.tar.bz2">
koffice-1.6.3.tar.bz2</a></td>
<td><tt>386d388094734f9759977c3267098e30</tt></td></tr>
<tr><td>Bulgarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-bg-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-bg-1.6.3.tar.bz2</a></td>
<td><tt>da3167fc536f51d8e32998ae203cd4b9</tt></td></tr>
<tr><td>Catalan</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ca-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.6.3.tar.bz2</a></td>
<td><tt>5ec6aa3c1c613466a545e26bdb9dfd72</tt></td></tr>
<tr><td>Czech</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-cs-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.6.3.tar.bz2</a></td>
<td><tt>d893774830fa05b2450018ae70fcd267</tt></td></tr>
<tr><td>Welsh</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-cy-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.6.3.tar.bz2</a></td>
<td><tt>6a100e050c3e6ae95733b24ce4d4f4cf</tt></td></tr>
<tr><td>Danish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-da-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-da-1.6.3.tar.bz2</a></td>
<td><tt>fa9c878f7672d1b9881722f93a1dc1ce</tt></td></tr>
<tr><td>German</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-de-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-de-1.6.3.tar.bz2</a></td>
<td><tt>9153728550bc6101094bac42aefb7663</tt></td></tr>
<tr><td>Greek</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-el-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-el-1.6.3.tar.bz2</a></td>
<td><tt>be97b80ccaa0da028d8d04f263be5fed</tt></td></tr>
<tr><td>British English</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-en_GB-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.6.3.tar.bz2</a></td>
<td><tt>468c3ac77b57de10e1cb7c99d184a443</tt></td></tr>
<tr><td>Spanish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-es-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-es-1.6.3.tar.bz2</a></td>
<td><tt>23f246f5bc86f8831e595f98c24c154e</tt></td></tr>
<tr><td>Estonian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-et-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-et-1.6.3.tar.bz2</a></td>
<td><tt>fdc1c81ae65bec5f7e56d76bcdbaa1af</tt></td></tr>
<tr><td>Basque</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-eu-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-eu-1.6.3.tar.bz2</a></td>
<td><tt>3ca81163f7242bcad450342e1105ad89</tt></td></tr>
<tr><td>Farsi</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-fa-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-fa-1.6.3.tar.bz2</a></td>
<td><tt>63f5d0570660e47455e8ccd1a8c4bf02</tt></td></tr>
<tr><td>Finnish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-fi-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.6.3.tar.bz2</a></td>
<td><tt>98b3b306061c127b92d9e73d3641f687</tt></td></tr>
<tr><td>French</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-fr-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.6.3.tar.bz2</a></td>
<td><tt>01219310196ac9c8325c3d8c7456bcb3</tt></td></tr>
<tr><td>Irish Gaelic</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ga-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-ga-1.6.3.tar.bz2</a></td>
<td><tt>80f28f345dbae9b108b97701ab2a3b7b</tt></td></tr>
<tr><td>Galician</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-gl-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-gl-1.6.3.tar.bz2</a></td>
<td><tt>84b9c65886a99599d99c7ea077875a88</tt></td></tr>
<tr><td>Hungarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-hu-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.6.3.tar.bz2</a></td>
<td><tt>088e5c503a9dedfa8d23a3fa11f596ca</tt></td></tr>
<tr><td>Italian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-it-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-it-1.6.3.tar.bz2</a></td>
<td><tt>1aa3d67279e63f7c7919908c686f2281</tt></td></tr>
<tr><td>Japanese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ja-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-ja-1.6.3.tar.bz2</a></td>
<td><tt>b0d886c7504a8b0bafb5095835e78c8a</tt></td></tr>
<tr><td>Khmer</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-km-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-km-1.6.3.tar.bz2</a></td>
<td><tt>527e698b2907f90712239681f0ae0a9e</tt></td></tr>
<tr><td>Latvian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-lv-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-lv-1.6.3.tar.bz2</a></td>
<td><tt>62386e1713216bd2709e1ce3fd150c8e</tt></td></tr>
<tr><td>Malay</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ms-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-ms-1.6.3.tar.bz2</a></td>
<td><tt>1bf2fcf2c82464e038eed026eaa13fca</tt></td></tr>
<tr><td>Norwegian Bokm&aring;l</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-nb-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.6.3.tar.bz2</a></td>
<td><tt>462ecb27a008482801ca3bd9e803b2d1</tt></td></tr>
<tr><td>Low Saxon</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-nds-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-nds-1.6.3.tar.bz2</a></td>
<td><tt>50702ef6c8d586e89280a2b42d2c5225</tt></td></tr>
<tr><td>Nepali</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ne-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-ne-1.6.3.tar.bz2</a></td>
<td><tt>bd95494b15f647dfcbe39d514811504a</tt></td></tr>
<tr><td>Dutch</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-nl-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.6.3.tar.bz2</a></td>
<td><tt>a63c40510c0bb322dc1f6bb057759772</tt></td></tr>
<tr><td>Polish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-pl-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.6.3.tar.bz2</a></td>
<td><tt>a174b73f3e2c0e579bf3775e481958dd</tt></td></tr>
<tr><td>Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-pt-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.6.3.tar.bz2</a></td>
<td><tt>e74540534eae3d0b1cb4bbabf3da0ed0</tt></td></tr>
<tr><td>Brazilian Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-pt_BR-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.6.3.tar.bz2</a></td>
<td><tt>fe49fa2405b44044b69b5d1e2bcb15cf</tt></td></tr>
<tr><td>Russian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ru-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.6.3.tar.bz2</a></td>
<td><tt>e6be9bcea5e2b6e6aa4662f1530841ef</tt></td></tr>
<tr><td>Slovak</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sk-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-sk-1.6.3.tar.bz2</a></td>
<td><tt>aa49a6c5497dc201359c577ab77c8361</tt></td></tr>
<tr><td>Slovenian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sl-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.6.3.tar.bz2</a></td>
<td><tt>18e3f2e81be91170fe551e4b47c2f907</tt></td></tr>
<tr><td>Serbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sr-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.6.3.tar.bz2</a></td>
<td><tt>3eb97f2ef5f65b3637af397dca0d8fcb</tt></td></tr>
<tr><td>Serbian Latin</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sr@Latn-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.6.3.tar.bz2</a></td>
<td><tt>217064c12d6efe969a1bbdac2ef8aef0</tt></td></tr>
<tr><td>Swedish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sv-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.6.3.tar.bz2</a></td>
<td><tt>c6c530010a64fb9e2880a3f33bb9276e</tt></td></tr>
<tr><td>Turkish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-tr-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-tr-1.6.3.tar.bz2</a></td>
<td><tt>301f3a665f12d1b7f56fe9be93403812</tt></td></tr>
<tr><td>Ukrainian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-uk-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-uk-1.6.3.tar.bz2</a></td>
<td><tt>f8a50375d4f280131a27e0bdfb0deb83</tt></td></tr>
<tr><td>Chinese Simplified</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-zh_CN-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.6.3.tar.bz2</a></td>
<td><tt>a21490ebc1d0beedc565c070d4bdad25</tt></td></tr>
<tr><td>Chinese Traditional</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-zh_TW-1.6.3.tar.bz2">
koffice-l10n/koffice-l10n-zh_TW-1.6.3.tar.bz2</a></td>
<td><tt>7c7c3787a45743ae9d06938829381d2e</tt></td></tr>
</table>
<p>*: XDelta patches</p>
