<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-1.5.1.tar.bz2">
koffice-1.5.1.tar.bz2</a></td>
<td><tt>50897bd5dfd4eba8a0d78a02003a6ec9</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/keximdb-1.0.1.tar.gz">
keximdb-1.0.1.tar.gz</a></td>
<td><tt>45cc0659b02dda9799edbb4d31dd11d5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-af-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-af-1.5.1.tar.bz2</a></td>
<td><tt>99f5fae8b0d15bcdec7daa3dfadfc20d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ar-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ar-1.5.1.tar.bz2</a></td>
<td><tt>3ace1a68c04d3cb3d0e2b45ab9a059d0</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-bg-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-bg-1.5.1.tar.bz2</a></td>
<td><tt>8daaeb614b3439490c2dd64a5ca6a90d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-br-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-br-1.5.1.tar.bz2</a></td>
<td><tt>bed06b1e8dc15ab3f0360d66ecb5eca8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-bs-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-bs-1.5.1.tar.bz2</a></td>
<td><tt>f5e83bf3d981a433fe8470947ed22c0a</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ca-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.5.1.tar.bz2</a></td>
<td><tt>a9386b6c6049814d6f4a3f67a4cb51d8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-cs-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.5.1.tar.bz2</a></td>
<td><tt>6f68790c56564626e42949979a4e1dba</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-cy-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.5.1.tar.bz2</a></td>
<td><tt>780d5816865f60b88209059c6c2e7d02</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-da-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-da-1.5.1.tar.bz2</a></td>
<td><tt>aa38e3e0f04a930e89543cfb79c6184d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-de-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-de-1.5.1.tar.bz2</a></td>
<td><tt>dcd8043ab5b5d2642e4302f1f89fc639</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-el-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-el-1.5.1.tar.bz2</a></td>
<td><tt>350963ba95241e2576c077d4558d7fcb</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-en_GB-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.5.1.tar.bz2</a></td>
<td><tt>b7ae8b4aee9810f2b78235962f7f1dc2</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-eo-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-eo-1.5.1.tar.bz2</a></td>
<td><tt>71c42a69ea9c417494d1603bc3b646b8</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-es-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-es-1.5.1.tar.bz2</a></td>
<td><tt>70b926928aa1a2facb3409f144191967</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-et-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-et-1.5.1.tar.bz2</a></td>
<td><tt>23311d668c05da159ea12240f950e763</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-eu-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-eu-1.5.1.tar.bz2</a></td>
<td><tt>39f2c93001a037b79eda7e3f9611ea8a</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-fi-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.5.1.tar.bz2</a></td>
<td><tt>f72750aa5c9cd5aa3814715ff36acd33</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-fr-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.5.1.tar.bz2</a></td>
<td><tt>d63d63daa55fa32e5c93b72c902cd4d1</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ga-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ga-1.5.1.tar.bz2</a></td>
<td><tt>42615504255afdbadcbaafb197a6adb4</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-he-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-he-1.5.1.tar.bz2</a></td>
<td><tt>a20e78860f0975b65ed59720924591ca</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-hi-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-hi-1.5.1.tar.bz2</a></td>
<td><tt>37de7254e2d6610ad395c260cb002201</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-hu-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.5.1.tar.bz2</a></td>
<td><tt>8a8d4f7adaaed89063c4971c9bbfbf43</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-is-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-is-1.5.1.tar.bz2</a></td>
<td><tt>33cf09b995ffde0c28a794ce3f6c6d51</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-it-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-it-1.5.1.tar.bz2</a></td>
<td><tt>71cf4cad9272090e6469a96736bd785e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ja-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ja-1.5.1.tar.bz2</a></td>
<td><tt>8f7893e842afd51368bd18c37b221f57</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-lt-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-lt-1.5.1.tar.bz2</a></td>
<td><tt>6ece374294c001730552883defb0a53c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-mk-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-mk-1.5.1.tar.bz2</a></td>
<td><tt>6adad6081c79ac9dc3edcae7bb5a9494</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ms-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ms-1.5.1.tar.bz2</a></td>
<td><tt>43f77ffa86d70b1fb42cf4bc2312e783</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-nb-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.5.1.tar.bz2</a></td>
<td><tt>ff774ceadd4c42b80ab138c4446d8843</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-nl-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.5.1.tar.bz2</a></td>
<td><tt>f76f2b7b8a65a528d3d0514f5f1a0cbf</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-nn-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-nn-1.5.1.tar.bz2</a></td>
<td><tt>12a451ca1384c776045a86aa3f0fecb5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-pl-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.5.1.tar.bz2</a></td>
<td><tt>5580950ba10229b65563ae8b9c29e8c4</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-pt-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.5.1.tar.bz2</a></td>
<td><tt>549c4668a4ec2fbc71a2fadb9597ea8f</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-pt_BR-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.5.1.tar.bz2</a></td>
<td><tt>5882aeae172ccfebbf68bad8f4dc0ced</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ro-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ro-1.5.1.tar.bz2</a></td>
<td><tt>b01b4652edcd49e2d1f77db8040a2552</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ru-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.5.1.tar.bz2</a></td>
<td><tt>7a484f7d54125398516cf54a2139e84d</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-se-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-se-1.5.1.tar.bz2</a></td>
<td><tt>ae4b1cabf24dcf7a89fbef573b07301a</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-sk-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-sk-1.5.1.tar.bz2</a></td>
<td><tt>11a9def76b738074d5a70bf81a5e5b4b</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-sl-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.5.1.tar.bz2</a></td>
<td><tt>4520614986d6fb70b1d4b8eb117815a5</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-sr-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.5.1.tar.bz2</a></td>
<td><tt>a825f39361da5599bcd572907eb9d068</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-sr@Latn-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.5.1.tar.bz2</a></td>
<td><tt>0413072d626a8b6291f65504f76d93f6</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-sv-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.5.1.tar.bz2</a></td>
<td><tt>4afcc6585df0a171e90b595c3d3311ae</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-ta-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-ta-1.5.1.tar.bz2</a></td>
<td><tt>536e66f3b85923771f2af964b51a465e</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-tg-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-tg-1.5.1.tar.bz2</a></td>
<td><tt>a38ec98b0f6437ddb93196f369a09485</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-tr-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-tr-1.5.1.tar.bz2</a></td>
<td><tt>0026e7f0b40b76a700792bf3a8a40427</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-uk-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-uk-1.5.1.tar.bz2</a></td>
<td><tt>114018e8d5e5935c8d47c717dbb3523c</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-uz-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-uz-1.5.1.tar.bz2</a></td>
<td><tt>b4ce57436f31a2c5b63572b27b1c3582</tt></td></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.5.1/src/koffice-l10n/koffice-l10n-zh_CN-1.5.1.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.5.1.tar.bz2</a></td>
<td><tt>f691b1667472c36f8c8ec3fb69ac11ea</tt></td></tr>
</table>
<p>*: XDelta patches</p>
