<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>General</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-1.6.1.tar.bz2">
koffice-1.6.1.tar.bz2</a></td>
<td><tt>f7b90b46b79019edc60761a6bff2d387</tt></td></tr>
<tr><td>Catalan</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ca-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-ca-1.6.1.tar.bz2</a></td>
<td><tt>2af9ee48900b76f13c7b205f9f44e454</tt></td></tr>
<tr><td>Czech</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-cs-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-cs-1.6.1.tar.bz2</a></td>
<td><tt>a90d191f1d84bd5c8090ca6e004253c4</tt></td></tr>
<tr><td>Welsh</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-cy-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-cy-1.6.1.tar.bz2</a></td>
<td><tt>4f5d6aef468aeb4b80c6b079e1399110</tt></td></tr>
<tr><td>Danish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-da-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-da-1.6.1.tar.bz2</a></td>
<td><tt>34ac13ce5bf8452f5f8b44686d03781a</tt></td></tr>
<tr><td>German</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-de-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-de-1.6.1.tar.bz2</a></td>
<td><tt>9ec1030ec8f55b4689a4664a3032050d</tt></td></tr>
<tr><td>Greek</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-el-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-el-1.6.1.tar.bz2</a></td>
<td><tt>c2028907c0675534694b5bad4c85ac0f</tt></td></tr>
<tr><td>British English</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-en_GB-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-en_GB-1.6.1.tar.bz2</a></td>
<td><tt>0c8edcc2fb6570ff7629e610580cac2f</tt></td></tr>
<tr><td>Spanish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-es-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-es-1.6.1.tar.bz2</a></td>
<td><tt>e3095320b087fdbaf9dea4ca7384c4e7</tt></td></tr>
<tr><td>Estonian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-et-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-et-1.6.1.tar.bz2</a></td>
<td><tt>d7e32d741c284880ff01530d956cd524</tt></td></tr>
<tr><td>Basque</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-eu-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-eu-1.6.1.tar.bz2</a></td>
<td><tt>33bb005893d82eeebbc1dc62495e018a</tt></td></tr>
<tr><td>Finnish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-fi-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-fi-1.6.1.tar.bz2</a></td>
<td><tt>dc0b99fe0b1c2f0bdc5823804cf5f7f7</tt></td></tr>
<tr><td>French</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-fr-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-fr-1.6.1.tar.bz2</a></td>
<td><tt>74a658f3f323f016b202cc4e2063da19</tt></td></tr>
<tr><td>Hungarian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-hu-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-hu-1.6.1.tar.bz2</a></td>
<td><tt>406eef87386bea965c9d0ec224b0a6aa</tt></td></tr>
<tr><td>Italian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-it-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-it-1.6.1.tar.bz2</a></td>
<td><tt>5fc389a6885af2acce7e5b9b48a9ce12</tt></td></tr>
<tr><td>Japanese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ja-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-ja-1.6.1.tar.bz2</a></td>
<td><tt>39ba5b3618221ee6fa896aa16aa9f6a9</tt></td></tr>
<tr><td>Latvian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-lv-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-lv-1.6.1.tar.bz2</a></td>
<td><tt>512650fbc0638ac0f0bae2864f295cca</tt></td></tr>
<tr><td>Malay</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ms-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-ms-1.6.1.tar.bz2</a></td>
<td><tt>ff1d6abe79bf4b4239ebaccc2509c35e</tt></td></tr>
<tr><td>Norwegian Bokm&aring;l</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-nb-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-nb-1.6.1.tar.bz2</a></td>
<td><tt>65d3a4d15e8911faf43d1aa9c6f7b6a7</tt></td></tr>
<tr><td>Dutch</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-nl-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-nl-1.6.1.tar.bz2</a></td>
<td><tt>006bc0ff8b292fc8836c989d244a45bc</tt></td></tr>
<tr><td>Polish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-pl-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-pl-1.6.1.tar.bz2</a></td>
<td><tt>ca6e0bd7de872e51f342cd153598981b</tt></td></tr>
<tr><td>Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-pt-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-pt-1.6.1.tar.bz2</a></td>
<td><tt>c4e59783b4b93a50c7e5e9b53c864caa</tt></td></tr>
<tr><td>Brazilian Portuguese</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-pt_BR-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-pt_BR-1.6.1.tar.bz2</a></td>
<td><tt>71efdf80a256b20baece5e58f2d4527a</tt></td></tr>
<tr><td>Russian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-ru-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-ru-1.6.1.tar.bz2</a></td>
<td><tt>d72bb7ce7fe685c4c92940dca4cf4bf8</tt></td></tr>
<tr><td>Slovak</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sk-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-sk-1.6.1.tar.bz2</a></td>
<td><tt>63b2d698040b2f5ece72e7ca67407669</tt></td></tr>
<tr><td>Slovenian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sl-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-sl-1.6.1.tar.bz2</a></td>
<td><tt>0c40d723b64bf15fbb8c78ebce17dcb3</tt></td></tr>
<tr><td>Serbian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sr-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-sr-1.6.1.tar.bz2</a></td>
<td><tt>ff1137b214460cfc6c647643da08e098</tt></td></tr>
<tr><td>Serbian Latin</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sr@Latn-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-sr@Latn-1.6.1.tar.bz2</a></td>
<td><tt>ed4eab803a7c0443ff3c4839e32757d1</tt></td></tr>
<tr><td>Swedish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-sv-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-sv-1.6.1.tar.bz2</a></td>
<td><tt>fd5ebf8d8480797f84121f9efcb00823</tt></td></tr>
<tr><td>Turkish</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-tr-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-tr-1.6.1.tar.bz2</a></td>
<td><tt>909ed845836e7219a4cf6710ee128846</tt></td></tr>
<tr><td>Ukrainian</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-uk-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-uk-1.6.1.tar.bz2</a></td>
<td><tt>dcab018c147831f47543b082f1beb5a5</tt></td></tr>
<tr><td>Chinese Simplified</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-zh_CN-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-zh_CN-1.6.1.tar.bz2</a></td>
<td><tt>055cf1eed59bc1e491063d4ffa883d9b</tt></td></tr>
<tr><td>Chinese Traditional</td>
<td><a href="http://download.kde.org/stable/koffice-1.6.1/src/koffice-l10n/koffice-l10n-zh_TW-1.6.1.tar.bz2">
koffice-l10n/koffice-l10n-zh_TW-1.6.1.tar.bz2</a></td>
<td><tt>230b02b893873f1fd55f002509549793</tt></td></tr>
</table>
<p>*: XDelta patches</p>
