<table border="0" cellpadding="4" cellspacing="0">
<tr><th align="left">Description</th><th align="left">Location</th><th align="left">MD5&nbsp;Sum</th></tr>
<tr><td>KOffice 1.6 beta 1 (source)</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-beta1/koffice-1.5.91.tar.bz2">
koffice-1.5.91.tar.bz2</a></td>
<td><tt>c7aeaf362210ff2e52d610bdbe2c91fd</tt></td></tr>
<tr><td>MS Access import plugin</td>
<td><a href="http://download.kde.org/unstable/koffice-1.6-beta1/keximdb-1.1.0.tar.gz">
keximdb-1.1.0.tar.gz</a></td>
<td><tt>0e960fe9344d5be1232c12fb984e60a9</tt></td></tr>
</table>
