<?php
$this->addLink("Information", "index.php");
$this->addLink("Koffice 1.3beta2", "1.3beta2-release.php");
$this->addLink("KOffice 1.3beta1", "1.3beta1-release.php");
$this->addLink("KOffice 1.2.1", "1.2.1-release.php");
$this->addLink("KOffice 1.2", "1.2-release.php");
$this->addLink("KOffice 1.2rc1", "1.2rc1-release.php");
$this->addLink("KOffice 1.2beta2", "1.2beta2-release.php");
$this->addLink("KOffice 1.2beta1", "1.2beta1-release.php");
$this->addLink("KOffice 1.1.1", "1.1.1-release.php");
$this->addLink("KOffice 1.1", "1.1-release.php");
?>
