<?php
  $appinfo = new AppInfo("Kugar");
  $appinfo->setIcon( "pics/cr48-app-kugar.png", "48", "48");
  $appinfo->setVersion($kugarversion);
  $appinfo->setLicense("gpl");
  $appinfo->setCopyright("2002", "the Kugar Team");
  $appinfo->addAuthor("Keith Davis", "i&#x6e;f&#111;&#x40;m&#00117;&#00116;&#x69;&#110;y&#98;ay&#115;oft&#x77;a&#114;e&#46;&#00099;o&#109;");
  $appinfo->addContributor("Alexander Dymo", "&#099;&#0108;&#x6f;u&#100;&#116;em&#x70;le&#x40;&#x6d;ks&#97;t.net");
  $appinfo->addContributor("Joseph Wenninger", "&#106;ow&#101;&#110;n&#0064;kd&#101;&#x2e;&#x6f;&#114;g");
  $appinfo->addContributor("Per Winkvist", "per.w&#105;&#x6e;kv&#00105;st&#064;&#0099;e&#x6c;lnet&#x77;&#x6f;r&#x6b;&#046;&#x63;&#x6f;m");
?>