<?php
  $appinfo = new AppInfo("KSpread");
  $appinfo->setIcon( "pics/hi48-app-kspread.png", "48", "48");
  $appinfo->setVersion($kspreadversion);
  $appinfo->setLicense("lgpl");
  $appinfo->setCopyright("1998", "the KSpread Team");
  $appinfo->addAuthor("Torben Weis", "&#119;e&#105;&#115;&#64;&#107;de.org");
  $appinfo->addContributor("Laurent Montel", "mont&#0101;&#00108;&#x40;&#107;&#0100;e.org");
  $appinfo->addContributor("Philipp Mueller", "philipp.m&#117;&#101;&#00108;&#0108;er&#64;gm&#00120;.de");
  $appinfo->addContributor("Ariya Hidayat", "ar&#00105;y&#x61;&#x40;&#107;&#x64;&#x65;&#46;o&#0114;g");
  $appinfo->addContributor("Norbet Andres", "&#00110;a&#00110;dre&#x73;&#0064;web&#x2e;d&#101;"); 
  $appinfo->addContributor("Luk&aacute;&scaron; Tinkl", "l&#117;&#x6b;a&#x73;&#x40;kd&#101;.&#111;&#x72;&#103;"); 
  $appinfo->addContributor("Meni Livne", "&#108;&#x69;v&#x6e;e&#00064;k&#0100;e&#46;org"); 
  $appinfo->addContributor("Raphael Langerhorst", "raphael.&#108;a&#x6e;&#103;&#x65;r&#x68;&#00111;&#x72;st&#x40;&#107;&#x64;&#x65;m&#x61;&#x69;&#108;&#x2e;ne&#116;"); 
  $appinfo->addContributor("Tomas Mecir", "&#109;ec&#x69;r&#116;&#64;g&#109;&#x61;il&#00046;com"); 
  $appinfo->addContributor("Inge Wallin", "&#105;ng&#00101;&#64;&#x6c;&#121;sa&#x74;or&#x2e;l&#105;u&#x2e;s&#x65;"); 
?>
