%-------------------------- MS FONTS ----------------------------------------

%-------------------- Fontmap entries to convert kword names to correct names.


/Arial            /ArialMT        ;
/Arial-Bold             /Arial_BoldMT   ;
/Arial-BoldItalic               /Arial_BoldItalicMT     ;
/Arial-Italic           /Arial_ItalicMT ;
/ArialBlack-Roman               /Arial_Black    ;
/ComicSansMs-Roman              /ComicSansMS    ;
/ComicSansMs-Bold               /ComicSansMS_Bold       ;
/Georgia-Roman          /Georgia        ;
/Georgia-Bold           /Georgia_Bold   ;
/Georgia-Italic         /Georgia_Italic ;
/Georgia-BoldItalic             /Georgia_BoldItalic     ;
/Impact-Roman					/Impact	;
/Monotype.com-Roman             /Monotypecom    ;
/TrebuchetMs-Roman              /TrebuchetMS    ;
/TrebuchetMs-Bold               /TrebuchetMS_Bold       ;
/TrebuchetMs-BoldItalic         /Trebuchet_BoldItalic   ;
/TrebuchetMs-Italic             /TrebuchetMS_Italic     ;
/Verdana-Roman          /Verdana        ;
/Verdana-Bold           /Verdana_Bold   ;
/Verdana-Italic         /Verdana_Italic ;
/Verdana-BoldItalic             /Verdana_BoldItalic     ;
/Wingdings-Roman                /Wingdings_Regular      ;

% --------------------- Fontmap entries to tell ghostscript about MS fonts

/ArialMT	(/usr/share/fonts/ttfonts/windows/ARIAL.TTF);
/Arial_BoldMT	(/usr/share/fonts/ttfonts/windows/ARIALBD.TTF);
/Arial_BoldItalicMT	(/usr/share/fonts/ttfonts/windows/ARIALBI.TTF);
/Arial_ItalicMT	(/usr/share/fonts/ttfonts/windows/ARIALI.TTF);
/Arial_Black	(/usr/share/fonts/ttfonts/windows/ARIBLK.TTF);
/ComicSansMS	(/usr/share/fonts/ttfonts/windows/COMIC.TTF);
/ComicSansMS_Bold	(/usr/share/fonts/ttfonts/windows/COMICBD.TTF);
/Georgia	(/usr/share/fonts/ttfonts/windows/GEORGIA.TTF);
/Georgia_Bold	(/usr/share/fonts/ttfonts/windows/GEORGIAB.TTF);
/Georgia_Italic	(/usr/share/fonts/ttfonts/windows/GEORGIAI.TTF);
/Georgia_BoldItalic	(/usr/share/fonts/ttfonts/windows/GEORGIAZ.TTF);
/Impact	(/usr/share/fonts/ttfonts/windows/IMPACT.TTF);
/Monotypecom	(/usr/share/fonts/ttfonts/windows/MONOTYPE.TTF);
/TrebuchetMS	(/usr/share/fonts/ttfonts/windows/TREBUC.TTF);
/TrebuchetMS_Bold	(/usr/share/fonts/ttfonts/windows/TREBUCBD.TTF);
/Trebuchet_BoldItalic	(/usr/share/fonts/ttfonts/windows/TREBUCBI.TTF);
/TrebuchetMS_Italic	(/usr/share/fonts/ttfonts/windows/TREBUCIT.TTF);
/Verdana	(/usr/share/fonts/ttfonts/windows/VERDANA.TTF);
/Verdana_Bold	(/usr/share/fonts/ttfonts/windows/VERDANAB.TTF);
/Verdana_Italic	(/usr/share/fonts/ttfonts/windows/VERDANAI.TTF);
/Verdana_BoldItalic	(/usr/share/fonts/ttfonts/windows/VERDANAZ.TTF);
/Wingdings_Regular	(/usr/share/fonts/ttfonts/windows/WINGDING.TTF);

%------------------------ END MS FONTS ----------------------------------
