 <h2><a name="pdfexport">PDF Export</a></h2>
 <p>All KOffice applications can export (create) PDF files.  The
 process for exporting to PDF is the same as in most other KDE
 applications:</p>
 <ul>
   <li>Select <em>File->Print</em> from the menu;</li>
   <li>In the <em>Printer Name</em> box, choose the <em>Print to File
   (PDF)</em> option (illustrated below);
     <img src="../images/pdf.png" style="margin: 1em;" /></li>
   <li>Enter a file name in the <em>Output File</em> box (or use the
     button on the right of the <em>Output File</em> field for a standard file
     window;</li>
   <li>Click <em>Print.</em></li>
 </ul>
